package com.kf.data.mybatis.mapper.online;

import com.kf.data.mybatis.entity.online.KfCompanyDishonestyOnline;
import com.kf.data.mybatis.entity.online.KfCompanyDishonestyOnlineExample;
import com.kf.data.mybatis.entity.online.KfCompanyDishonestyOnlineWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface KfCompanyDishonestyOnlineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kf_company_dishonesty
     *
     * @mbggenerated Fri Mar 16 15:26:30 CST 2018
     */
    int countByExample(KfCompanyDishonestyOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kf_company_dishonesty
     *
     * @mbggenerated Fri Mar 16 15:26:30 CST 2018
     */
    int deleteByExample(KfCompanyDishonestyOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kf_company_dishonesty
     *
     * @mbggenerated Fri Mar 16 15:26:30 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kf_company_dishonesty
     *
     * @mbggenerated Fri Mar 16 15:26:30 CST 2018
     */
    int insert(KfCompanyDishonestyOnlineWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kf_company_dishonesty
     *
     * @mbggenerated Fri Mar 16 15:26:30 CST 2018
     */
    int insertSelective(KfCompanyDishonestyOnlineWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kf_company_dishonesty
     *
     * @mbggenerated Fri Mar 16 15:26:30 CST 2018
     */
    List<KfCompanyDishonestyOnlineWithBLOBs> selectByExampleWithBLOBs(KfCompanyDishonestyOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kf_company_dishonesty
     *
     * @mbggenerated Fri Mar 16 15:26:30 CST 2018
     */
    List<KfCompanyDishonestyOnline> selectByExample(KfCompanyDishonestyOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kf_company_dishonesty
     *
     * @mbggenerated Fri Mar 16 15:26:30 CST 2018
     */
    KfCompanyDishonestyOnlineWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kf_company_dishonesty
     *
     * @mbggenerated Fri Mar 16 15:26:30 CST 2018
     */
    int updateByExampleSelective(@Param("record") KfCompanyDishonestyOnlineWithBLOBs record, @Param("example") KfCompanyDishonestyOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kf_company_dishonesty
     *
     * @mbggenerated Fri Mar 16 15:26:30 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") KfCompanyDishonestyOnlineWithBLOBs record, @Param("example") KfCompanyDishonestyOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kf_company_dishonesty
     *
     * @mbggenerated Fri Mar 16 15:26:30 CST 2018
     */
    int updateByExample(@Param("record") KfCompanyDishonestyOnline record, @Param("example") KfCompanyDishonestyOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kf_company_dishonesty
     *
     * @mbggenerated Fri Mar 16 15:26:30 CST 2018
     */
    int updateByPrimaryKeySelective(KfCompanyDishonestyOnlineWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kf_company_dishonesty
     *
     * @mbggenerated Fri Mar 16 15:26:30 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(KfCompanyDishonestyOnlineWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kf_company_dishonesty
     *
     * @mbggenerated Fri Mar 16 15:26:30 CST 2018
     */
    int updateByPrimaryKey(KfCompanyDishonestyOnline record);
}