package com.kf.data.mybatis.mapper.online;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.kf.data.mybatis.entity.online.NeeqCompanyBusinessModelOnline;
import com.kf.data.mybatis.entity.online.NeeqCompanyBusinessModelOnlineExample;

public interface NeeqCompanyBusinessModelOnlineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_business_model
     *
     * @mbggenerated Wed Mar 14 10:06:58 CST 2018
     */
    int countByExample(NeeqCompanyBusinessModelOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_business_model
     *
     * @mbggenerated Wed Mar 14 10:06:58 CST 2018
     */
    int deleteByExample(NeeqCompanyBusinessModelOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_business_model
     *
     * @mbggenerated Wed Mar 14 10:06:58 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_business_model
     *
     * @mbggenerated Wed Mar 14 10:06:58 CST 2018
     */
    int insert(NeeqCompanyBusinessModelOnline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_business_model
     *
     * @mbggenerated Wed Mar 14 10:06:58 CST 2018
     */
    int insertSelective(NeeqCompanyBusinessModelOnline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_business_model
     *
     * @mbggenerated Wed Mar 14 10:06:58 CST 2018
     */
    List<NeeqCompanyBusinessModelOnline> selectByExampleWithBLOBs(NeeqCompanyBusinessModelOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_business_model
     *
     * @mbggenerated Wed Mar 14 10:06:58 CST 2018
     */
    List<NeeqCompanyBusinessModelOnline> selectByExample(NeeqCompanyBusinessModelOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_business_model
     *
     * @mbggenerated Wed Mar 14 10:06:58 CST 2018
     */
    NeeqCompanyBusinessModelOnline selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_business_model
     *
     * @mbggenerated Wed Mar 14 10:06:58 CST 2018
     */
    int updateByExampleSelective(@Param("record") NeeqCompanyBusinessModelOnline record, @Param("example") NeeqCompanyBusinessModelOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_business_model
     *
     * @mbggenerated Wed Mar 14 10:06:58 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") NeeqCompanyBusinessModelOnline record, @Param("example") NeeqCompanyBusinessModelOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_business_model
     *
     * @mbggenerated Wed Mar 14 10:06:58 CST 2018
     */
    int updateByExample(@Param("record") NeeqCompanyBusinessModelOnline record, @Param("example") NeeqCompanyBusinessModelOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_business_model
     *
     * @mbggenerated Wed Mar 14 10:06:58 CST 2018
     */
    int updateByPrimaryKeySelective(NeeqCompanyBusinessModelOnline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_business_model
     *
     * @mbggenerated Wed Mar 14 10:06:58 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(NeeqCompanyBusinessModelOnline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_business_model
     *
     * @mbggenerated Wed Mar 14 10:06:58 CST 2018
     */
    int updateByPrimaryKey(NeeqCompanyBusinessModelOnline record);
}