package com.kf.data.mybatis.mapper.online;

import com.kf.data.mybatis.entity.online.NeeqSecompanyMarketMakingHisOnline;
import com.kf.data.mybatis.entity.online.NeeqSecompanyMarketMakingHisOnlineExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NeeqSecompanyMarketMakingHisOnlineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_secompany_market_making_his
     *
     * @mbggenerated Fri Mar 23 11:19:07 CST 2018
     */
    int countByExample(NeeqSecompanyMarketMakingHisOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_secompany_market_making_his
     *
     * @mbggenerated Fri Mar 23 11:19:07 CST 2018
     */
    int deleteByExample(NeeqSecompanyMarketMakingHisOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_secompany_market_making_his
     *
     * @mbggenerated Fri Mar 23 11:19:07 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_secompany_market_making_his
     *
     * @mbggenerated Fri Mar 23 11:19:07 CST 2018
     */
    int insert(NeeqSecompanyMarketMakingHisOnline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_secompany_market_making_his
     *
     * @mbggenerated Fri Mar 23 11:19:07 CST 2018
     */
    int insertSelective(NeeqSecompanyMarketMakingHisOnline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_secompany_market_making_his
     *
     * @mbggenerated Fri Mar 23 11:19:07 CST 2018
     */
    List<NeeqSecompanyMarketMakingHisOnline> selectByExample(NeeqSecompanyMarketMakingHisOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_secompany_market_making_his
     *
     * @mbggenerated Fri Mar 23 11:19:07 CST 2018
     */
    NeeqSecompanyMarketMakingHisOnline selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_secompany_market_making_his
     *
     * @mbggenerated Fri Mar 23 11:19:07 CST 2018
     */
    int updateByExampleSelective(@Param("record") NeeqSecompanyMarketMakingHisOnline record, @Param("example") NeeqSecompanyMarketMakingHisOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_secompany_market_making_his
     *
     * @mbggenerated Fri Mar 23 11:19:07 CST 2018
     */
    int updateByExample(@Param("record") NeeqSecompanyMarketMakingHisOnline record, @Param("example") NeeqSecompanyMarketMakingHisOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_secompany_market_making_his
     *
     * @mbggenerated Fri Mar 23 11:19:07 CST 2018
     */
    int updateByPrimaryKeySelective(NeeqSecompanyMarketMakingHisOnline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_secompany_market_making_his
     *
     * @mbggenerated Fri Mar 23 11:19:07 CST 2018
     */
    int updateByPrimaryKey(NeeqSecompanyMarketMakingHisOnline record);
}