package com.kf.data.mybatis.mapper.online;

import com.kf.data.mybatis.entity.online.NeeqNoticeRiskTipsChgOnline;
import com.kf.data.mybatis.entity.online.NeeqNoticeRiskTipsChgOnlineExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NeeqNoticeRiskTipsChgOnlineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_notice_risk_tips_chg
     *
     * @mbggenerated Fri Mar 16 14:10:02 CST 2018
     */
    int countByExample(NeeqNoticeRiskTipsChgOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_notice_risk_tips_chg
     *
     * @mbggenerated Fri Mar 16 14:10:02 CST 2018
     */
    int deleteByExample(NeeqNoticeRiskTipsChgOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_notice_risk_tips_chg
     *
     * @mbggenerated Fri Mar 16 14:10:02 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_notice_risk_tips_chg
     *
     * @mbggenerated Fri Mar 16 14:10:02 CST 2018
     */
    int insert(NeeqNoticeRiskTipsChgOnline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_notice_risk_tips_chg
     *
     * @mbggenerated Fri Mar 16 14:10:02 CST 2018
     */
    int insertSelective(NeeqNoticeRiskTipsChgOnline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_notice_risk_tips_chg
     *
     * @mbggenerated Fri Mar 16 14:10:02 CST 2018
     */
    List<NeeqNoticeRiskTipsChgOnline> selectByExampleWithBLOBs(NeeqNoticeRiskTipsChgOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_notice_risk_tips_chg
     *
     * @mbggenerated Fri Mar 16 14:10:02 CST 2018
     */
    List<NeeqNoticeRiskTipsChgOnline> selectByExample(NeeqNoticeRiskTipsChgOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_notice_risk_tips_chg
     *
     * @mbggenerated Fri Mar 16 14:10:02 CST 2018
     */
    NeeqNoticeRiskTipsChgOnline selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_notice_risk_tips_chg
     *
     * @mbggenerated Fri Mar 16 14:10:02 CST 2018
     */
    int updateByExampleSelective(@Param("record") NeeqNoticeRiskTipsChgOnline record, @Param("example") NeeqNoticeRiskTipsChgOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_notice_risk_tips_chg
     *
     * @mbggenerated Fri Mar 16 14:10:02 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") NeeqNoticeRiskTipsChgOnline record, @Param("example") NeeqNoticeRiskTipsChgOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_notice_risk_tips_chg
     *
     * @mbggenerated Fri Mar 16 14:10:02 CST 2018
     */
    int updateByExample(@Param("record") NeeqNoticeRiskTipsChgOnline record, @Param("example") NeeqNoticeRiskTipsChgOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_notice_risk_tips_chg
     *
     * @mbggenerated Fri Mar 16 14:10:02 CST 2018
     */
    int updateByPrimaryKeySelective(NeeqNoticeRiskTipsChgOnline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_notice_risk_tips_chg
     *
     * @mbggenerated Fri Mar 16 14:10:02 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(NeeqNoticeRiskTipsChgOnline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_notice_risk_tips_chg
     *
     * @mbggenerated Fri Mar 16 14:10:02 CST 2018
     */
    int updateByPrimaryKey(NeeqNoticeRiskTipsChgOnline record);
}