package com.kf.data.mybatis.mapper.online;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.kf.data.mybatis.entity.online.NeeqSecompanyBaseOnline;
import com.kf.data.mybatis.entity.online.NeeqSecompanyBaseOnlineExample;
import com.kf.data.mybatis.entity.online.NeeqSecompanyBaseOnlineWithBLOBs;

public interface NeeqSecompanyBaseOnlineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_news
     *
     * @mbggenerated Wed Mar 14 10:37:18 CST 2018
     */
    int countByExample(NeeqSecompanyBaseOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_news
     *
     * @mbggenerated Wed Mar 14 10:37:18 CST 2018
     */
    int deleteByExample(NeeqSecompanyBaseOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_news
     *
     * @mbggenerated Wed Mar 14 10:37:18 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_news
     *
     * @mbggenerated Wed Mar 14 10:37:18 CST 2018
     */
    int insert(NeeqSecompanyBaseOnlineWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_news
     *
     * @mbggenerated Wed Mar 14 10:37:18 CST 2018
     */
    int insertSelective(NeeqSecompanyBaseOnlineWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_news
     *
     * @mbggenerated Wed Mar 14 10:37:18 CST 2018
     */
    List<NeeqSecompanyBaseOnlineWithBLOBs> selectByExampleWithBLOBs(NeeqSecompanyBaseOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_news
     *
     * @mbggenerated Wed Mar 14 10:37:18 CST 2018
     */
    List<NeeqSecompanyBaseOnline> selectByExample(NeeqSecompanyBaseOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_news
     *
     * @mbggenerated Wed Mar 14 10:37:18 CST 2018
     */
    NeeqSecompanyBaseOnlineWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_news
     *
     * @mbggenerated Wed Mar 14 10:37:18 CST 2018
     */
    int updateByExampleSelective(@Param("record") NeeqSecompanyBaseOnlineWithBLOBs record, @Param("example") NeeqSecompanyBaseOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_news
     *
     * @mbggenerated Wed Mar 14 10:37:18 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") NeeqSecompanyBaseOnlineWithBLOBs record, @Param("example") NeeqSecompanyBaseOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_news
     *
     * @mbggenerated Wed Mar 14 10:37:18 CST 2018
     */
    int updateByExample(@Param("record") NeeqSecompanyBaseOnline record, @Param("example") NeeqSecompanyBaseOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_news
     *
     * @mbggenerated Wed Mar 14 10:37:18 CST 2018
     */
    int updateByPrimaryKeySelective(NeeqSecompanyBaseOnlineWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_news
     *
     * @mbggenerated Wed Mar 14 10:37:18 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(NeeqSecompanyBaseOnlineWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_news
     *
     * @mbggenerated Wed Mar 14 10:37:18 CST 2018
     */
    int updateByPrimaryKey(NeeqSecompanyBaseOnline record);
}