package com.kf.data.mybatis.mapper.online;

import com.kf.data.mybatis.entity.online.NeeqCompanyExecutiveResumeOnline;
import com.kf.data.mybatis.entity.online.NeeqCompanyExecutiveResumeOnlineExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NeeqCompanyExecutiveResumeOnlineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_executive_resume
     *
     * @mbggenerated Wed Mar 14 17:12:39 CST 2018
     */
    int countByExample(NeeqCompanyExecutiveResumeOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_executive_resume
     *
     * @mbggenerated Wed Mar 14 17:12:39 CST 2018
     */
    int deleteByExample(NeeqCompanyExecutiveResumeOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_executive_resume
     *
     * @mbggenerated Wed Mar 14 17:12:39 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_executive_resume
     *
     * @mbggenerated Wed Mar 14 17:12:39 CST 2018
     */
    int insert(NeeqCompanyExecutiveResumeOnline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_executive_resume
     *
     * @mbggenerated Wed Mar 14 17:12:39 CST 2018
     */
    int insertSelective(NeeqCompanyExecutiveResumeOnline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_executive_resume
     *
     * @mbggenerated Wed Mar 14 17:12:39 CST 2018
     */
    List<NeeqCompanyExecutiveResumeOnline> selectByExampleWithBLOBs(NeeqCompanyExecutiveResumeOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_executive_resume
     *
     * @mbggenerated Wed Mar 14 17:12:39 CST 2018
     */
    List<NeeqCompanyExecutiveResumeOnline> selectByExample(NeeqCompanyExecutiveResumeOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_executive_resume
     *
     * @mbggenerated Wed Mar 14 17:12:39 CST 2018
     */
    NeeqCompanyExecutiveResumeOnline selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_executive_resume
     *
     * @mbggenerated Wed Mar 14 17:12:39 CST 2018
     */
    int updateByExampleSelective(@Param("record") NeeqCompanyExecutiveResumeOnline record, @Param("example") NeeqCompanyExecutiveResumeOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_executive_resume
     *
     * @mbggenerated Wed Mar 14 17:12:39 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") NeeqCompanyExecutiveResumeOnline record, @Param("example") NeeqCompanyExecutiveResumeOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_executive_resume
     *
     * @mbggenerated Wed Mar 14 17:12:39 CST 2018
     */
    int updateByExample(@Param("record") NeeqCompanyExecutiveResumeOnline record, @Param("example") NeeqCompanyExecutiveResumeOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_executive_resume
     *
     * @mbggenerated Wed Mar 14 17:12:39 CST 2018
     */
    int updateByPrimaryKeySelective(NeeqCompanyExecutiveResumeOnline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_executive_resume
     *
     * @mbggenerated Wed Mar 14 17:12:39 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(NeeqCompanyExecutiveResumeOnline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_executive_resume
     *
     * @mbggenerated Wed Mar 14 17:12:39 CST 2018
     */
    int updateByPrimaryKey(NeeqCompanyExecutiveResumeOnline record);
}