package com.kf.data.mybatis.mapper.online;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.kf.data.mybatis.entity.online.NeeqCompanyDomainRecordOnline;
import com.kf.data.mybatis.entity.online.NeeqCompanyDomainRecordOnlineExample;

public interface NeeqCompanyDomainRecordOnlineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_domain_record
     *
     * @mbggenerated Wed Mar 14 10:18:11 CST 2018
     */
    int countByExample(NeeqCompanyDomainRecordOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_domain_record
     *
     * @mbggenerated Wed Mar 14 10:18:11 CST 2018
     */
    int deleteByExample(NeeqCompanyDomainRecordOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_domain_record
     *
     * @mbggenerated Wed Mar 14 10:18:11 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_domain_record
     *
     * @mbggenerated Wed Mar 14 10:18:11 CST 2018
     */
    int insert(NeeqCompanyDomainRecordOnline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_domain_record
     *
     * @mbggenerated Wed Mar 14 10:18:11 CST 2018
     */
    int insertSelective(NeeqCompanyDomainRecordOnline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_domain_record
     *
     * @mbggenerated Wed Mar 14 10:18:11 CST 2018
     */
    List<NeeqCompanyDomainRecordOnline> selectByExample(NeeqCompanyDomainRecordOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_domain_record
     *
     * @mbggenerated Wed Mar 14 10:18:11 CST 2018
     */
    NeeqCompanyDomainRecordOnline selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_domain_record
     *
     * @mbggenerated Wed Mar 14 10:18:11 CST 2018
     */
    int updateByExampleSelective(@Param("record") NeeqCompanyDomainRecordOnline record, @Param("example") NeeqCompanyDomainRecordOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_domain_record
     *
     * @mbggenerated Wed Mar 14 10:18:11 CST 2018
     */
    int updateByExample(@Param("record") NeeqCompanyDomainRecordOnline record, @Param("example") NeeqCompanyDomainRecordOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_domain_record
     *
     * @mbggenerated Wed Mar 14 10:18:11 CST 2018
     */
    int updateByPrimaryKeySelective(NeeqCompanyDomainRecordOnline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_domain_record
     *
     * @mbggenerated Wed Mar 14 10:18:11 CST 2018
     */
    int updateByPrimaryKey(NeeqCompanyDomainRecordOnline record);
}