package com.kf.data.mybatis.mapper.online;

import com.kf.data.mybatis.entity.online.NeeqCompanyStockPledgeOnline;
import com.kf.data.mybatis.entity.online.NeeqCompanyStockPledgeOnlineExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NeeqCompanyStockPledgeOnlineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_stock_pledge
     *
     * @mbggenerated Fri Mar 16 16:09:47 CST 2018
     */
    int countByExample(NeeqCompanyStockPledgeOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_stock_pledge
     *
     * @mbggenerated Fri Mar 16 16:09:47 CST 2018
     */
    int deleteByExample(NeeqCompanyStockPledgeOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_stock_pledge
     *
     * @mbggenerated Fri Mar 16 16:09:47 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_stock_pledge
     *
     * @mbggenerated Fri Mar 16 16:09:47 CST 2018
     */
    int insert(NeeqCompanyStockPledgeOnline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_stock_pledge
     *
     * @mbggenerated Fri Mar 16 16:09:47 CST 2018
     */
    int insertSelective(NeeqCompanyStockPledgeOnline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_stock_pledge
     *
     * @mbggenerated Fri Mar 16 16:09:47 CST 2018
     */
    List<NeeqCompanyStockPledgeOnline> selectByExample(NeeqCompanyStockPledgeOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_stock_pledge
     *
     * @mbggenerated Fri Mar 16 16:09:47 CST 2018
     */
    NeeqCompanyStockPledgeOnline selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_stock_pledge
     *
     * @mbggenerated Fri Mar 16 16:09:47 CST 2018
     */
    int updateByExampleSelective(@Param("record") NeeqCompanyStockPledgeOnline record, @Param("example") NeeqCompanyStockPledgeOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_stock_pledge
     *
     * @mbggenerated Fri Mar 16 16:09:47 CST 2018
     */
    int updateByExample(@Param("record") NeeqCompanyStockPledgeOnline record, @Param("example") NeeqCompanyStockPledgeOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_stock_pledge
     *
     * @mbggenerated Fri Mar 16 16:09:47 CST 2018
     */
    int updateByPrimaryKeySelective(NeeqCompanyStockPledgeOnline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_stock_pledge
     *
     * @mbggenerated Fri Mar 16 16:09:47 CST 2018
     */
    int updateByPrimaryKey(NeeqCompanyStockPledgeOnline record);
}