package com.kf.data.mybatis.mapper.online;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.kf.data.mybatis.entity.online.NeeqEventsInvestOnline;
import com.kf.data.mybatis.entity.online.NeeqEventsInvestOnlineExample;

public interface NeeqEventsInvestOnlineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_events_invest
     *
     * @mbggenerated Wed Mar 14 10:09:35 CST 2018
     */
    int countByExample(NeeqEventsInvestOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_events_invest
     *
     * @mbggenerated Wed Mar 14 10:09:35 CST 2018
     */
    int deleteByExample(NeeqEventsInvestOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_events_invest
     *
     * @mbggenerated Wed Mar 14 10:09:35 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_events_invest
     *
     * @mbggenerated Wed Mar 14 10:09:35 CST 2018
     */
    int insert(NeeqEventsInvestOnline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_events_invest
     *
     * @mbggenerated Wed Mar 14 10:09:35 CST 2018
     */
    int insertSelective(NeeqEventsInvestOnline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_events_invest
     *
     * @mbggenerated Wed Mar 14 10:09:35 CST 2018
     */
    List<NeeqEventsInvestOnline> selectByExampleWithBLOBs(NeeqEventsInvestOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_events_invest
     *
     * @mbggenerated Wed Mar 14 10:09:35 CST 2018
     */
    List<NeeqEventsInvestOnline> selectByExample(NeeqEventsInvestOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_events_invest
     *
     * @mbggenerated Wed Mar 14 10:09:35 CST 2018
     */
    NeeqEventsInvestOnline selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_events_invest
     *
     * @mbggenerated Wed Mar 14 10:09:35 CST 2018
     */
    int updateByExampleSelective(@Param("record") NeeqEventsInvestOnline record, @Param("example") NeeqEventsInvestOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_events_invest
     *
     * @mbggenerated Wed Mar 14 10:09:35 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") NeeqEventsInvestOnline record, @Param("example") NeeqEventsInvestOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_events_invest
     *
     * @mbggenerated Wed Mar 14 10:09:35 CST 2018
     */
    int updateByExample(@Param("record") NeeqEventsInvestOnline record, @Param("example") NeeqEventsInvestOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_events_invest
     *
     * @mbggenerated Wed Mar 14 10:09:35 CST 2018
     */
    int updateByPrimaryKeySelective(NeeqEventsInvestOnline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_events_invest
     *
     * @mbggenerated Wed Mar 14 10:09:35 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(NeeqEventsInvestOnline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_events_invest
     *
     * @mbggenerated Wed Mar 14 10:09:35 CST 2018
     */
    int updateByPrimaryKey(NeeqEventsInvestOnline record);
}