package com.kf.data.mybatis.mapper.online;

import com.kf.data.mybatis.entity.online.NeeqLawFirmBaseOnline;
import com.kf.data.mybatis.entity.online.NeeqLawFirmBaseOnlineExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NeeqLawFirmBaseOnlineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_law_firm_base
     *
     * @mbggenerated Fri Mar 23 10:44:20 CST 2018
     */
    int countByExample(NeeqLawFirmBaseOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_law_firm_base
     *
     * @mbggenerated Fri Mar 23 10:44:20 CST 2018
     */
    int deleteByExample(NeeqLawFirmBaseOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_law_firm_base
     *
     * @mbggenerated Fri Mar 23 10:44:20 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_law_firm_base
     *
     * @mbggenerated Fri Mar 23 10:44:20 CST 2018
     */
    int insert(NeeqLawFirmBaseOnline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_law_firm_base
     *
     * @mbggenerated Fri Mar 23 10:44:20 CST 2018
     */
    int insertSelective(NeeqLawFirmBaseOnline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_law_firm_base
     *
     * @mbggenerated Fri Mar 23 10:44:20 CST 2018
     */
    List<NeeqLawFirmBaseOnline> selectByExample(NeeqLawFirmBaseOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_law_firm_base
     *
     * @mbggenerated Fri Mar 23 10:44:20 CST 2018
     */
    NeeqLawFirmBaseOnline selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_law_firm_base
     *
     * @mbggenerated Fri Mar 23 10:44:20 CST 2018
     */
    int updateByExampleSelective(@Param("record") NeeqLawFirmBaseOnline record, @Param("example") NeeqLawFirmBaseOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_law_firm_base
     *
     * @mbggenerated Fri Mar 23 10:44:20 CST 2018
     */
    int updateByExample(@Param("record") NeeqLawFirmBaseOnline record, @Param("example") NeeqLawFirmBaseOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_law_firm_base
     *
     * @mbggenerated Fri Mar 23 10:44:20 CST 2018
     */
    int updateByPrimaryKeySelective(NeeqLawFirmBaseOnline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_law_firm_base
     *
     * @mbggenerated Fri Mar 23 10:44:20 CST 2018
     */
    int updateByPrimaryKey(NeeqLawFirmBaseOnline record);
}