package com.kf.data.mybatis.mapper.online;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.kf.data.mybatis.entity.online.NeeqNoticeRiskTipsOnline;
import com.kf.data.mybatis.entity.online.NeeqNoticeRiskTipsOnlineExample;

public interface NeeqNoticeRiskTipsOnlineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_notice_risk_tips
     *
     * @mbggenerated Wed Mar 14 10:10:27 CST 2018
     */
    int countByExample(NeeqNoticeRiskTipsOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_notice_risk_tips
     *
     * @mbggenerated Wed Mar 14 10:10:27 CST 2018
     */
    int deleteByExample(NeeqNoticeRiskTipsOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_notice_risk_tips
     *
     * @mbggenerated Wed Mar 14 10:10:27 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_notice_risk_tips
     *
     * @mbggenerated Wed Mar 14 10:10:27 CST 2018
     */
    int insert(NeeqNoticeRiskTipsOnline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_notice_risk_tips
     *
     * @mbggenerated Wed Mar 14 10:10:27 CST 2018
     */
    int insertSelective(NeeqNoticeRiskTipsOnline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_notice_risk_tips
     *
     * @mbggenerated Wed Mar 14 10:10:27 CST 2018
     */
    List<NeeqNoticeRiskTipsOnline> selectByExampleWithBLOBs(NeeqNoticeRiskTipsOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_notice_risk_tips
     *
     * @mbggenerated Wed Mar 14 10:10:27 CST 2018
     */
    List<NeeqNoticeRiskTipsOnline> selectByExample(NeeqNoticeRiskTipsOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_notice_risk_tips
     *
     * @mbggenerated Wed Mar 14 10:10:27 CST 2018
     */
    NeeqNoticeRiskTipsOnline selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_notice_risk_tips
     *
     * @mbggenerated Wed Mar 14 10:10:27 CST 2018
     */
    int updateByExampleSelective(@Param("record") NeeqNoticeRiskTipsOnline record, @Param("example") NeeqNoticeRiskTipsOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_notice_risk_tips
     *
     * @mbggenerated Wed Mar 14 10:10:27 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") NeeqNoticeRiskTipsOnline record, @Param("example") NeeqNoticeRiskTipsOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_notice_risk_tips
     *
     * @mbggenerated Wed Mar 14 10:10:27 CST 2018
     */
    int updateByExample(@Param("record") NeeqNoticeRiskTipsOnline record, @Param("example") NeeqNoticeRiskTipsOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_notice_risk_tips
     *
     * @mbggenerated Wed Mar 14 10:10:27 CST 2018
     */
    int updateByPrimaryKeySelective(NeeqNoticeRiskTipsOnline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_notice_risk_tips
     *
     * @mbggenerated Wed Mar 14 10:10:27 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(NeeqNoticeRiskTipsOnline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_notice_risk_tips
     *
     * @mbggenerated Wed Mar 14 10:10:27 CST 2018
     */
    int updateByPrimaryKey(NeeqNoticeRiskTipsOnline record);
}