package com.kf.data.mybatis.mapper.online;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.kf.data.mybatis.entity.online.NeeqCompanyJudicialAuctionOnline;
import com.kf.data.mybatis.entity.online.NeeqCompanyJudicialAuctionOnlineExample;

public interface NeeqCompanyJudicialAuctionOnlineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_judicial_auction
     *
     * @mbggenerated Wed Mar 14 10:14:01 CST 2018
     */
    int countByExample(NeeqCompanyJudicialAuctionOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_judicial_auction
     *
     * @mbggenerated Wed Mar 14 10:14:01 CST 2018
     */
    int deleteByExample(NeeqCompanyJudicialAuctionOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_judicial_auction
     *
     * @mbggenerated Wed Mar 14 10:14:01 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_judicial_auction
     *
     * @mbggenerated Wed Mar 14 10:14:01 CST 2018
     */
    int insert(NeeqCompanyJudicialAuctionOnline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_judicial_auction
     *
     * @mbggenerated Wed Mar 14 10:14:01 CST 2018
     */
    int insertSelective(NeeqCompanyJudicialAuctionOnline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_judicial_auction
     *
     * @mbggenerated Wed Mar 14 10:14:01 CST 2018
     */
    List<NeeqCompanyJudicialAuctionOnline> selectByExampleWithBLOBs(NeeqCompanyJudicialAuctionOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_judicial_auction
     *
     * @mbggenerated Wed Mar 14 10:14:01 CST 2018
     */
    List<NeeqCompanyJudicialAuctionOnline> selectByExample(NeeqCompanyJudicialAuctionOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_judicial_auction
     *
     * @mbggenerated Wed Mar 14 10:14:01 CST 2018
     */
    NeeqCompanyJudicialAuctionOnline selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_judicial_auction
     *
     * @mbggenerated Wed Mar 14 10:14:01 CST 2018
     */
    int updateByExampleSelective(@Param("record") NeeqCompanyJudicialAuctionOnline record, @Param("example") NeeqCompanyJudicialAuctionOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_judicial_auction
     *
     * @mbggenerated Wed Mar 14 10:14:01 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") NeeqCompanyJudicialAuctionOnline record, @Param("example") NeeqCompanyJudicialAuctionOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_judicial_auction
     *
     * @mbggenerated Wed Mar 14 10:14:01 CST 2018
     */
    int updateByExample(@Param("record") NeeqCompanyJudicialAuctionOnline record, @Param("example") NeeqCompanyJudicialAuctionOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_judicial_auction
     *
     * @mbggenerated Wed Mar 14 10:14:01 CST 2018
     */
    int updateByPrimaryKeySelective(NeeqCompanyJudicialAuctionOnline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_judicial_auction
     *
     * @mbggenerated Wed Mar 14 10:14:01 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(NeeqCompanyJudicialAuctionOnline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_judicial_auction
     *
     * @mbggenerated Wed Mar 14 10:14:01 CST 2018
     */
    int updateByPrimaryKey(NeeqCompanyJudicialAuctionOnline record);
}