package com.kf.data.mybatis.mapper.online;

import com.kf.data.mybatis.entity.online.NeeqCompanyMainBusinessOnline;
import com.kf.data.mybatis.entity.online.NeeqCompanyMainBusinessOnlineExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NeeqCompanyMainBusinessOnlineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_main_business
     *
     * @mbggenerated Thu Mar 15 13:45:43 CST 2018
     */
    int countByExample(NeeqCompanyMainBusinessOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_main_business
     *
     * @mbggenerated Thu Mar 15 13:45:43 CST 2018
     */
    int deleteByExample(NeeqCompanyMainBusinessOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_main_business
     *
     * @mbggenerated Thu Mar 15 13:45:43 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_main_business
     *
     * @mbggenerated Thu Mar 15 13:45:43 CST 2018
     */
    int insert(NeeqCompanyMainBusinessOnline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_main_business
     *
     * @mbggenerated Thu Mar 15 13:45:43 CST 2018
     */
    int insertSelective(NeeqCompanyMainBusinessOnline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_main_business
     *
     * @mbggenerated Thu Mar 15 13:45:43 CST 2018
     */
    List<NeeqCompanyMainBusinessOnline> selectByExampleWithBLOBs(NeeqCompanyMainBusinessOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_main_business
     *
     * @mbggenerated Thu Mar 15 13:45:43 CST 2018
     */
    List<NeeqCompanyMainBusinessOnline> selectByExample(NeeqCompanyMainBusinessOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_main_business
     *
     * @mbggenerated Thu Mar 15 13:45:43 CST 2018
     */
    NeeqCompanyMainBusinessOnline selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_main_business
     *
     * @mbggenerated Thu Mar 15 13:45:43 CST 2018
     */
    int updateByExampleSelective(@Param("record") NeeqCompanyMainBusinessOnline record, @Param("example") NeeqCompanyMainBusinessOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_main_business
     *
     * @mbggenerated Thu Mar 15 13:45:43 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") NeeqCompanyMainBusinessOnline record, @Param("example") NeeqCompanyMainBusinessOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_main_business
     *
     * @mbggenerated Thu Mar 15 13:45:43 CST 2018
     */
    int updateByExample(@Param("record") NeeqCompanyMainBusinessOnline record, @Param("example") NeeqCompanyMainBusinessOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_main_business
     *
     * @mbggenerated Thu Mar 15 13:45:43 CST 2018
     */
    int updateByPrimaryKeySelective(NeeqCompanyMainBusinessOnline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_main_business
     *
     * @mbggenerated Thu Mar 15 13:45:43 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(NeeqCompanyMainBusinessOnline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_main_business
     *
     * @mbggenerated Thu Mar 15 13:45:43 CST 2018
     */
    int updateByPrimaryKey(NeeqCompanyMainBusinessOnline record);
}