package com.kf.data.mybatis.mapper.online;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.kf.data.mybatis.entity.online.NeeqCompanyAbnormalOperationOnline;
import com.kf.data.mybatis.entity.online.NeeqCompanyAbnormalOperationOnlineExample;
import com.kf.data.mybatis.entity.online.NeeqCompanyAbnormalOperationOnlineWithBLOBs;

public interface NeeqCompanyAbnormalOperationOnlineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_abnormal_operation
     *
     * @mbggenerated Wed Mar 14 10:11:53 CST 2018
     */
    int countByExample(NeeqCompanyAbnormalOperationOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_abnormal_operation
     *
     * @mbggenerated Wed Mar 14 10:11:53 CST 2018
     */
    int deleteByExample(NeeqCompanyAbnormalOperationOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_abnormal_operation
     *
     * @mbggenerated Wed Mar 14 10:11:53 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_abnormal_operation
     *
     * @mbggenerated Wed Mar 14 10:11:53 CST 2018
     */
    int insert(NeeqCompanyAbnormalOperationOnlineWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_abnormal_operation
     *
     * @mbggenerated Wed Mar 14 10:11:53 CST 2018
     */
    int insertSelective(NeeqCompanyAbnormalOperationOnlineWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_abnormal_operation
     *
     * @mbggenerated Wed Mar 14 10:11:53 CST 2018
     */
    List<NeeqCompanyAbnormalOperationOnlineWithBLOBs> selectByExampleWithBLOBs(NeeqCompanyAbnormalOperationOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_abnormal_operation
     *
     * @mbggenerated Wed Mar 14 10:11:53 CST 2018
     */
    List<NeeqCompanyAbnormalOperationOnline> selectByExample(NeeqCompanyAbnormalOperationOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_abnormal_operation
     *
     * @mbggenerated Wed Mar 14 10:11:53 CST 2018
     */
    NeeqCompanyAbnormalOperationOnlineWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_abnormal_operation
     *
     * @mbggenerated Wed Mar 14 10:11:53 CST 2018
     */
    int updateByExampleSelective(@Param("record") NeeqCompanyAbnormalOperationOnlineWithBLOBs record, @Param("example") NeeqCompanyAbnormalOperationOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_abnormal_operation
     *
     * @mbggenerated Wed Mar 14 10:11:53 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") NeeqCompanyAbnormalOperationOnlineWithBLOBs record, @Param("example") NeeqCompanyAbnormalOperationOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_abnormal_operation
     *
     * @mbggenerated Wed Mar 14 10:11:53 CST 2018
     */
    int updateByExample(@Param("record") NeeqCompanyAbnormalOperationOnline record, @Param("example") NeeqCompanyAbnormalOperationOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_abnormal_operation
     *
     * @mbggenerated Wed Mar 14 10:11:53 CST 2018
     */
    int updateByPrimaryKeySelective(NeeqCompanyAbnormalOperationOnlineWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_abnormal_operation
     *
     * @mbggenerated Wed Mar 14 10:11:53 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(NeeqCompanyAbnormalOperationOnlineWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_abnormal_operation
     *
     * @mbggenerated Wed Mar 14 10:11:53 CST 2018
     */
    int updateByPrimaryKey(NeeqCompanyAbnormalOperationOnline record);
}