package com.kf.data.mybatis.mapper.online;

import com.kf.data.mybatis.entity.online.NeeqBaseCompanyOnline;
import com.kf.data.mybatis.entity.online.NeeqBaseCompanyOnlineExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NeeqBaseCompanyOnlineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_base_company
     *
     * @mbggenerated Tue Mar 20 18:13:03 CST 2018
     */
    int countByExample(NeeqBaseCompanyOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_base_company
     *
     * @mbggenerated Tue Mar 20 18:13:03 CST 2018
     */
    int deleteByExample(NeeqBaseCompanyOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_base_company
     *
     * @mbggenerated Tue Mar 20 18:13:03 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_base_company
     *
     * @mbggenerated Tue Mar 20 18:13:03 CST 2018
     */
    int insert(NeeqBaseCompanyOnline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_base_company
     *
     * @mbggenerated Tue Mar 20 18:13:03 CST 2018
     */
    int insertSelective(NeeqBaseCompanyOnline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_base_company
     *
     * @mbggenerated Tue Mar 20 18:13:03 CST 2018
     */
    List<NeeqBaseCompanyOnline> selectByExampleWithBLOBs(NeeqBaseCompanyOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_base_company
     *
     * @mbggenerated Tue Mar 20 18:13:03 CST 2018
     */
    List<NeeqBaseCompanyOnline> selectByExample(NeeqBaseCompanyOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_base_company
     *
     * @mbggenerated Tue Mar 20 18:13:03 CST 2018
     */
    NeeqBaseCompanyOnline selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_base_company
     *
     * @mbggenerated Tue Mar 20 18:13:03 CST 2018
     */
    int updateByExampleSelective(@Param("record") NeeqBaseCompanyOnline record, @Param("example") NeeqBaseCompanyOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_base_company
     *
     * @mbggenerated Tue Mar 20 18:13:03 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") NeeqBaseCompanyOnline record, @Param("example") NeeqBaseCompanyOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_base_company
     *
     * @mbggenerated Tue Mar 20 18:13:03 CST 2018
     */
    int updateByExample(@Param("record") NeeqBaseCompanyOnline record, @Param("example") NeeqBaseCompanyOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_base_company
     *
     * @mbggenerated Tue Mar 20 18:13:03 CST 2018
     */
    int updateByPrimaryKeySelective(NeeqBaseCompanyOnline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_base_company
     *
     * @mbggenerated Tue Mar 20 18:13:03 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(NeeqBaseCompanyOnline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_base_company
     *
     * @mbggenerated Tue Mar 20 18:13:03 CST 2018
     */
    int updateByPrimaryKey(NeeqBaseCompanyOnline record);
}