package com.kf.data.mybatis.mapper.online;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.kf.data.mybatis.entity.online.NeeqEventsTenderBidOnline;
import com.kf.data.mybatis.entity.online.NeeqEventsTenderBidOnlineExample;

public interface NeeqEventsTenderBidOnlineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_events_tender_bid
     *
     * @mbggenerated Wed Mar 14 10:34:31 CST 2018
     */
    int countByExample(NeeqEventsTenderBidOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_events_tender_bid
     *
     * @mbggenerated Wed Mar 14 10:34:31 CST 2018
     */
    int deleteByExample(NeeqEventsTenderBidOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_events_tender_bid
     *
     * @mbggenerated Wed Mar 14 10:34:31 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_events_tender_bid
     *
     * @mbggenerated Wed Mar 14 10:34:31 CST 2018
     */
    int insert(NeeqEventsTenderBidOnline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_events_tender_bid
     *
     * @mbggenerated Wed Mar 14 10:34:31 CST 2018
     */
    int insertSelective(NeeqEventsTenderBidOnline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_events_tender_bid
     *
     * @mbggenerated Wed Mar 14 10:34:31 CST 2018
     */
    List<NeeqEventsTenderBidOnline> selectByExampleWithBLOBs(NeeqEventsTenderBidOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_events_tender_bid
     *
     * @mbggenerated Wed Mar 14 10:34:31 CST 2018
     */
    List<NeeqEventsTenderBidOnline> selectByExample(NeeqEventsTenderBidOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_events_tender_bid
     *
     * @mbggenerated Wed Mar 14 10:34:31 CST 2018
     */
    NeeqEventsTenderBidOnline selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_events_tender_bid
     *
     * @mbggenerated Wed Mar 14 10:34:31 CST 2018
     */
    int updateByExampleSelective(@Param("record") NeeqEventsTenderBidOnline record, @Param("example") NeeqEventsTenderBidOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_events_tender_bid
     *
     * @mbggenerated Wed Mar 14 10:34:31 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") NeeqEventsTenderBidOnline record, @Param("example") NeeqEventsTenderBidOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_events_tender_bid
     *
     * @mbggenerated Wed Mar 14 10:34:31 CST 2018
     */
    int updateByExample(@Param("record") NeeqEventsTenderBidOnline record, @Param("example") NeeqEventsTenderBidOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_events_tender_bid
     *
     * @mbggenerated Wed Mar 14 10:34:31 CST 2018
     */
    int updateByPrimaryKeySelective(NeeqEventsTenderBidOnline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_events_tender_bid
     *
     * @mbggenerated Wed Mar 14 10:34:31 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(NeeqEventsTenderBidOnline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_events_tender_bid
     *
     * @mbggenerated Wed Mar 14 10:34:31 CST 2018
     */
    int updateByPrimaryKey(NeeqEventsTenderBidOnline record);
}