package com.kf.data.mybatis.mapper.online;

import com.kf.data.mybatis.entity.online.NeeqCompanyExecutorOnline;
import com.kf.data.mybatis.entity.online.NeeqCompanyExecutorOnlineExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NeeqCompanyExecutorOnlineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_executor
     *
     * @mbggenerated Thu Mar 22 09:51:40 CST 2018
     */
    int countByExample(NeeqCompanyExecutorOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_executor
     *
     * @mbggenerated Thu Mar 22 09:51:40 CST 2018
     */
    int deleteByExample(NeeqCompanyExecutorOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_executor
     *
     * @mbggenerated Thu Mar 22 09:51:40 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_executor
     *
     * @mbggenerated Thu Mar 22 09:51:40 CST 2018
     */
    int insert(NeeqCompanyExecutorOnline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_executor
     *
     * @mbggenerated Thu Mar 22 09:51:40 CST 2018
     */
    int insertSelective(NeeqCompanyExecutorOnline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_executor
     *
     * @mbggenerated Thu Mar 22 09:51:40 CST 2018
     */
    List<NeeqCompanyExecutorOnline> selectByExample(NeeqCompanyExecutorOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_executor
     *
     * @mbggenerated Thu Mar 22 09:51:40 CST 2018
     */
    NeeqCompanyExecutorOnline selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_executor
     *
     * @mbggenerated Thu Mar 22 09:51:40 CST 2018
     */
    int updateByExampleSelective(@Param("record") NeeqCompanyExecutorOnline record, @Param("example") NeeqCompanyExecutorOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_executor
     *
     * @mbggenerated Thu Mar 22 09:51:40 CST 2018
     */
    int updateByExample(@Param("record") NeeqCompanyExecutorOnline record, @Param("example") NeeqCompanyExecutorOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_executor
     *
     * @mbggenerated Thu Mar 22 09:51:40 CST 2018
     */
    int updateByPrimaryKeySelective(NeeqCompanyExecutorOnline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_executor
     *
     * @mbggenerated Thu Mar 22 09:51:40 CST 2018
     */
    int updateByPrimaryKey(NeeqCompanyExecutorOnline record);
}