package com.kf.data.mybatis.mapper.online;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.kf.data.mybatis.entity.online.NeeqCompanyBusinessIncomeOnline;
import com.kf.data.mybatis.entity.online.NeeqCompanyBusinessIncomeOnlineExample;

public interface NeeqCompanyBusinessIncomeOnlineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_business_income
     *
     * @mbggenerated Wed Mar 14 10:05:30 CST 2018
     */
    int countByExample(NeeqCompanyBusinessIncomeOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_business_income
     *
     * @mbggenerated Wed Mar 14 10:05:30 CST 2018
     */
    int deleteByExample(NeeqCompanyBusinessIncomeOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_business_income
     *
     * @mbggenerated Wed Mar 14 10:05:30 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_business_income
     *
     * @mbggenerated Wed Mar 14 10:05:30 CST 2018
     */
    int insert(NeeqCompanyBusinessIncomeOnline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_business_income
     *
     * @mbggenerated Wed Mar 14 10:05:30 CST 2018
     */
    int insertSelective(NeeqCompanyBusinessIncomeOnline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_business_income
     *
     * @mbggenerated Wed Mar 14 10:05:30 CST 2018
     */
    List<NeeqCompanyBusinessIncomeOnline> selectByExample(NeeqCompanyBusinessIncomeOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_business_income
     *
     * @mbggenerated Wed Mar 14 10:05:30 CST 2018
     */
    NeeqCompanyBusinessIncomeOnline selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_business_income
     *
     * @mbggenerated Wed Mar 14 10:05:30 CST 2018
     */
    int updateByExampleSelective(@Param("record") NeeqCompanyBusinessIncomeOnline record, @Param("example") NeeqCompanyBusinessIncomeOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_business_income
     *
     * @mbggenerated Wed Mar 14 10:05:30 CST 2018
     */
    int updateByExample(@Param("record") NeeqCompanyBusinessIncomeOnline record, @Param("example") NeeqCompanyBusinessIncomeOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_business_income
     *
     * @mbggenerated Wed Mar 14 10:05:30 CST 2018
     */
    int updateByPrimaryKeySelective(NeeqCompanyBusinessIncomeOnline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_business_income
     *
     * @mbggenerated Wed Mar 14 10:05:30 CST 2018
     */
    int updateByPrimaryKey(NeeqCompanyBusinessIncomeOnline record);
}