package com.kf.data.mybatis.mapper.online;

import com.kf.data.mybatis.entity.online.NeeqCompanyChattelMortgageOnline;
import com.kf.data.mybatis.entity.online.NeeqCompanyChattelMortgageOnlineExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NeeqCompanyChattelMortgageOnlineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_chattel_mortgage
     *
     * @mbggenerated Fri Mar 16 16:00:59 CST 2018
     */
    int countByExample(NeeqCompanyChattelMortgageOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_chattel_mortgage
     *
     * @mbggenerated Fri Mar 16 16:00:59 CST 2018
     */
    int deleteByExample(NeeqCompanyChattelMortgageOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_chattel_mortgage
     *
     * @mbggenerated Fri Mar 16 16:00:59 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_chattel_mortgage
     *
     * @mbggenerated Fri Mar 16 16:00:59 CST 2018
     */
    int insert(NeeqCompanyChattelMortgageOnline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_chattel_mortgage
     *
     * @mbggenerated Fri Mar 16 16:00:59 CST 2018
     */
    int insertSelective(NeeqCompanyChattelMortgageOnline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_chattel_mortgage
     *
     * @mbggenerated Fri Mar 16 16:00:59 CST 2018
     */
    List<NeeqCompanyChattelMortgageOnline> selectByExample(NeeqCompanyChattelMortgageOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_chattel_mortgage
     *
     * @mbggenerated Fri Mar 16 16:00:59 CST 2018
     */
    NeeqCompanyChattelMortgageOnline selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_chattel_mortgage
     *
     * @mbggenerated Fri Mar 16 16:00:59 CST 2018
     */
    int updateByExampleSelective(@Param("record") NeeqCompanyChattelMortgageOnline record, @Param("example") NeeqCompanyChattelMortgageOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_chattel_mortgage
     *
     * @mbggenerated Fri Mar 16 16:00:59 CST 2018
     */
    int updateByExample(@Param("record") NeeqCompanyChattelMortgageOnline record, @Param("example") NeeqCompanyChattelMortgageOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_chattel_mortgage
     *
     * @mbggenerated Fri Mar 16 16:00:59 CST 2018
     */
    int updateByPrimaryKeySelective(NeeqCompanyChattelMortgageOnline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_chattel_mortgage
     *
     * @mbggenerated Fri Mar 16 16:00:59 CST 2018
     */
    int updateByPrimaryKey(NeeqCompanyChattelMortgageOnline record);
}