package com.kf.data.mybatis.mapper.online;

import com.kf.data.mybatis.entity.online.NeeqFinanceIndicator2016Online;
import com.kf.data.mybatis.entity.online.NeeqFinanceIndicator2016OnlineExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NeeqFinanceIndicator2016OnlineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_finance_indicator_2016
     *
     * @mbggenerated Fri Mar 23 16:54:25 CST 2018
     */
    int countByExample(NeeqFinanceIndicator2016OnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_finance_indicator_2016
     *
     * @mbggenerated Fri Mar 23 16:54:25 CST 2018
     */
    int deleteByExample(NeeqFinanceIndicator2016OnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_finance_indicator_2016
     *
     * @mbggenerated Fri Mar 23 16:54:25 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_finance_indicator_2016
     *
     * @mbggenerated Fri Mar 23 16:54:25 CST 2018
     */
    int insert(NeeqFinanceIndicator2016Online record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_finance_indicator_2016
     *
     * @mbggenerated Fri Mar 23 16:54:25 CST 2018
     */
    int insertSelective(NeeqFinanceIndicator2016Online record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_finance_indicator_2016
     *
     * @mbggenerated Fri Mar 23 16:54:25 CST 2018
     */
    List<NeeqFinanceIndicator2016Online> selectByExample(NeeqFinanceIndicator2016OnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_finance_indicator_2016
     *
     * @mbggenerated Fri Mar 23 16:54:25 CST 2018
     */
    NeeqFinanceIndicator2016Online selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_finance_indicator_2016
     *
     * @mbggenerated Fri Mar 23 16:54:25 CST 2018
     */
    int updateByExampleSelective(@Param("record") NeeqFinanceIndicator2016Online record, @Param("example") NeeqFinanceIndicator2016OnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_finance_indicator_2016
     *
     * @mbggenerated Fri Mar 23 16:54:25 CST 2018
     */
    int updateByExample(@Param("record") NeeqFinanceIndicator2016Online record, @Param("example") NeeqFinanceIndicator2016OnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_finance_indicator_2016
     *
     * @mbggenerated Fri Mar 23 16:54:25 CST 2018
     */
    int updateByPrimaryKeySelective(NeeqFinanceIndicator2016Online record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_finance_indicator_2016
     *
     * @mbggenerated Fri Mar 23 16:54:25 CST 2018
     */
    int updateByPrimaryKey(NeeqFinanceIndicator2016Online record);
}