package com.kf.data.mybatis.mapper.online;

import com.kf.data.mybatis.entity.online.NeeqCompanyTagOnline;
import com.kf.data.mybatis.entity.online.NeeqCompanyTagOnlineExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NeeqCompanyTagOnlineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_tag
     *
     * @mbggenerated Tue Mar 20 18:49:47 CST 2018
     */
    int countByExample(NeeqCompanyTagOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_tag
     *
     * @mbggenerated Tue Mar 20 18:49:47 CST 2018
     */
    int deleteByExample(NeeqCompanyTagOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_tag
     *
     * @mbggenerated Tue Mar 20 18:49:47 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_tag
     *
     * @mbggenerated Tue Mar 20 18:49:47 CST 2018
     */
    int insert(NeeqCompanyTagOnline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_tag
     *
     * @mbggenerated Tue Mar 20 18:49:47 CST 2018
     */
    int insertSelective(NeeqCompanyTagOnline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_tag
     *
     * @mbggenerated Tue Mar 20 18:49:47 CST 2018
     */
    List<NeeqCompanyTagOnline> selectByExampleWithBLOBs(NeeqCompanyTagOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_tag
     *
     * @mbggenerated Tue Mar 20 18:49:47 CST 2018
     */
    List<NeeqCompanyTagOnline> selectByExample(NeeqCompanyTagOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_tag
     *
     * @mbggenerated Tue Mar 20 18:49:47 CST 2018
     */
    NeeqCompanyTagOnline selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_tag
     *
     * @mbggenerated Tue Mar 20 18:49:47 CST 2018
     */
    int updateByExampleSelective(@Param("record") NeeqCompanyTagOnline record, @Param("example") NeeqCompanyTagOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_tag
     *
     * @mbggenerated Tue Mar 20 18:49:47 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") NeeqCompanyTagOnline record, @Param("example") NeeqCompanyTagOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_tag
     *
     * @mbggenerated Tue Mar 20 18:49:47 CST 2018
     */
    int updateByExample(@Param("record") NeeqCompanyTagOnline record, @Param("example") NeeqCompanyTagOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_tag
     *
     * @mbggenerated Tue Mar 20 18:49:47 CST 2018
     */
    int updateByPrimaryKeySelective(NeeqCompanyTagOnline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_tag
     *
     * @mbggenerated Tue Mar 20 18:49:47 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(NeeqCompanyTagOnline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_tag
     *
     * @mbggenerated Tue Mar 20 18:49:47 CST 2018
     */
    int updateByPrimaryKey(NeeqCompanyTagOnline record);
}