package com.kf.data.mybatis.mapper.online;

import com.kf.data.mybatis.entity.online.NeeqSecompanyPunishOnline;
import com.kf.data.mybatis.entity.online.NeeqSecompanyPunishOnlineExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NeeqSecompanyPunishOnlineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_secompany_punish
     *
     * @mbggenerated Fri Mar 23 11:24:08 CST 2018
     */
    int countByExample(NeeqSecompanyPunishOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_secompany_punish
     *
     * @mbggenerated Fri Mar 23 11:24:08 CST 2018
     */
    int deleteByExample(NeeqSecompanyPunishOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_secompany_punish
     *
     * @mbggenerated Fri Mar 23 11:24:08 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_secompany_punish
     *
     * @mbggenerated Fri Mar 23 11:24:08 CST 2018
     */
    int insert(NeeqSecompanyPunishOnline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_secompany_punish
     *
     * @mbggenerated Fri Mar 23 11:24:08 CST 2018
     */
    int insertSelective(NeeqSecompanyPunishOnline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_secompany_punish
     *
     * @mbggenerated Fri Mar 23 11:24:08 CST 2018
     */
    List<NeeqSecompanyPunishOnline> selectByExampleWithBLOBs(NeeqSecompanyPunishOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_secompany_punish
     *
     * @mbggenerated Fri Mar 23 11:24:08 CST 2018
     */
    List<NeeqSecompanyPunishOnline> selectByExample(NeeqSecompanyPunishOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_secompany_punish
     *
     * @mbggenerated Fri Mar 23 11:24:08 CST 2018
     */
    NeeqSecompanyPunishOnline selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_secompany_punish
     *
     * @mbggenerated Fri Mar 23 11:24:08 CST 2018
     */
    int updateByExampleSelective(@Param("record") NeeqSecompanyPunishOnline record, @Param("example") NeeqSecompanyPunishOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_secompany_punish
     *
     * @mbggenerated Fri Mar 23 11:24:08 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") NeeqSecompanyPunishOnline record, @Param("example") NeeqSecompanyPunishOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_secompany_punish
     *
     * @mbggenerated Fri Mar 23 11:24:08 CST 2018
     */
    int updateByExample(@Param("record") NeeqSecompanyPunishOnline record, @Param("example") NeeqSecompanyPunishOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_secompany_punish
     *
     * @mbggenerated Fri Mar 23 11:24:08 CST 2018
     */
    int updateByPrimaryKeySelective(NeeqSecompanyPunishOnline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_secompany_punish
     *
     * @mbggenerated Fri Mar 23 11:24:08 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(NeeqSecompanyPunishOnline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_secompany_punish
     *
     * @mbggenerated Fri Mar 23 11:24:08 CST 2018
     */
    int updateByPrimaryKey(NeeqSecompanyPunishOnline record);
}