package com.kf.data.mybatis.mapper.online;

import com.kf.data.mybatis.entity.online.NeeqFinanceIndicator2014Online;
import com.kf.data.mybatis.entity.online.NeeqFinanceIndicator2014OnlineExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NeeqFinanceIndicator2014OnlineMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table neeq_finance_indicator_2014
	 * @mbggenerated  Fri Mar 23 16:54:34 CST 2018
	 */
	int countByExample(NeeqFinanceIndicator2014OnlineExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table neeq_finance_indicator_2014
	 * @mbggenerated  Fri Mar 23 16:54:34 CST 2018
	 */
	int deleteByExample(NeeqFinanceIndicator2014OnlineExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table neeq_finance_indicator_2014
	 * @mbggenerated  Fri Mar 23 16:54:34 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table neeq_finance_indicator_2014
	 * @mbggenerated  Fri Mar 23 16:54:34 CST 2018
	 */
	int insert(NeeqFinanceIndicator2014Online record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table neeq_finance_indicator_2014
	 * @mbggenerated  Fri Mar 23 16:54:34 CST 2018
	 */
	int insertSelective(NeeqFinanceIndicator2014Online record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table neeq_finance_indicator_2014
	 * @mbggenerated  Fri Mar 23 16:54:34 CST 2018
	 */
	List<NeeqFinanceIndicator2014Online> selectByExample(NeeqFinanceIndicator2014OnlineExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table neeq_finance_indicator_2014
	 * @mbggenerated  Fri Mar 23 16:54:34 CST 2018
	 */
	NeeqFinanceIndicator2014Online selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table neeq_finance_indicator_2014
	 * @mbggenerated  Fri Mar 23 16:54:34 CST 2018
	 */
	int updateByExampleSelective(@Param("record") NeeqFinanceIndicator2014Online record,
			@Param("example") NeeqFinanceIndicator2014OnlineExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table neeq_finance_indicator_2014
	 * @mbggenerated  Fri Mar 23 16:54:34 CST 2018
	 */
	int updateByExample(@Param("record") NeeqFinanceIndicator2014Online record,
			@Param("example") NeeqFinanceIndicator2014OnlineExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table neeq_finance_indicator_2014
	 * @mbggenerated  Fri Mar 23 16:54:34 CST 2018
	 */
	int updateByPrimaryKeySelective(NeeqFinanceIndicator2014Online record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table neeq_finance_indicator_2014
	 * @mbggenerated  Fri Mar 23 16:54:34 CST 2018
	 */
	int updateByPrimaryKey(NeeqFinanceIndicator2014Online record);
}