package com.kf.data.mybatis.mapper.online;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.kf.data.mybatis.entity.online.NeeqNoticeOnline;
import com.kf.data.mybatis.entity.online.NeeqNoticeOnlineExample;

public interface NeeqNoticeOnlineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_notice
     *
     * @mbggenerated Wed Mar 14 10:35:27 CST 2018
     */
    int countByExample(NeeqNoticeOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_notice
     *
     * @mbggenerated Wed Mar 14 10:35:27 CST 2018
     */
    int deleteByExample(NeeqNoticeOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_notice
     *
     * @mbggenerated Wed Mar 14 10:35:27 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_notice
     *
     * @mbggenerated Wed Mar 14 10:35:27 CST 2018
     */
    int insert(NeeqNoticeOnline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_notice
     *
     * @mbggenerated Wed Mar 14 10:35:27 CST 2018
     */
    int insertSelective(NeeqNoticeOnline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_notice
     *
     * @mbggenerated Wed Mar 14 10:35:27 CST 2018
     */
    List<NeeqNoticeOnline> selectByExampleWithBLOBs(NeeqNoticeOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_notice
     *
     * @mbggenerated Wed Mar 14 10:35:27 CST 2018
     */
    List<NeeqNoticeOnline> selectByExample(NeeqNoticeOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_notice
     *
     * @mbggenerated Wed Mar 14 10:35:27 CST 2018
     */
    NeeqNoticeOnline selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_notice
     *
     * @mbggenerated Wed Mar 14 10:35:27 CST 2018
     */
    int updateByExampleSelective(@Param("record") NeeqNoticeOnline record, @Param("example") NeeqNoticeOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_notice
     *
     * @mbggenerated Wed Mar 14 10:35:27 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") NeeqNoticeOnline record, @Param("example") NeeqNoticeOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_notice
     *
     * @mbggenerated Wed Mar 14 10:35:27 CST 2018
     */
    int updateByExample(@Param("record") NeeqNoticeOnline record, @Param("example") NeeqNoticeOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_notice
     *
     * @mbggenerated Wed Mar 14 10:35:27 CST 2018
     */
    int updateByPrimaryKeySelective(NeeqNoticeOnline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_notice
     *
     * @mbggenerated Wed Mar 14 10:35:27 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(NeeqNoticeOnline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_notice
     *
     * @mbggenerated Wed Mar 14 10:35:27 CST 2018
     */
    int updateByPrimaryKey(NeeqNoticeOnline record);
}