package com.kf.data.mybatis.mapper.online;

import com.kf.data.mybatis.entity.online.NeeqCompanyAccountingFirmOnline;
import com.kf.data.mybatis.entity.online.NeeqCompanyAccountingFirmOnlineExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NeeqCompanyAccountingFirmOnlineMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table neeq_company_accounting_firm
	 * @mbggenerated  Thu Mar 22 17:18:54 CST 2018
	 */
	int countByExample(NeeqCompanyAccountingFirmOnlineExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table neeq_company_accounting_firm
	 * @mbggenerated  Thu Mar 22 17:18:54 CST 2018
	 */
	int deleteByExample(NeeqCompanyAccountingFirmOnlineExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table neeq_company_accounting_firm
	 * @mbggenerated  Thu Mar 22 17:18:54 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table neeq_company_accounting_firm
	 * @mbggenerated  Thu Mar 22 17:18:54 CST 2018
	 */
	int insert(NeeqCompanyAccountingFirmOnline record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table neeq_company_accounting_firm
	 * @mbggenerated  Thu Mar 22 17:18:54 CST 2018
	 */
	int insertSelective(NeeqCompanyAccountingFirmOnline record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table neeq_company_accounting_firm
	 * @mbggenerated  Thu Mar 22 17:18:54 CST 2018
	 */
	List<NeeqCompanyAccountingFirmOnline> selectByExample(NeeqCompanyAccountingFirmOnlineExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table neeq_company_accounting_firm
	 * @mbggenerated  Thu Mar 22 17:18:54 CST 2018
	 */
	NeeqCompanyAccountingFirmOnline selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table neeq_company_accounting_firm
	 * @mbggenerated  Thu Mar 22 17:18:54 CST 2018
	 */
	int updateByExampleSelective(@Param("record") NeeqCompanyAccountingFirmOnline record,
			@Param("example") NeeqCompanyAccountingFirmOnlineExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table neeq_company_accounting_firm
	 * @mbggenerated  Thu Mar 22 17:18:54 CST 2018
	 */
	int updateByExample(@Param("record") NeeqCompanyAccountingFirmOnline record,
			@Param("example") NeeqCompanyAccountingFirmOnlineExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table neeq_company_accounting_firm
	 * @mbggenerated  Thu Mar 22 17:18:54 CST 2018
	 */
	int updateByPrimaryKeySelective(NeeqCompanyAccountingFirmOnline record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table neeq_company_accounting_firm
	 * @mbggenerated  Thu Mar 22 17:18:54 CST 2018
	 */
	int updateByPrimaryKey(NeeqCompanyAccountingFirmOnline record);
}