package com.kf.data.mybatis.mapper.online;

import com.kf.data.mybatis.entity.online.NeeqCompanyTaxArrearsOnline;
import com.kf.data.mybatis.entity.online.NeeqCompanyTaxArrearsOnlineExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NeeqCompanyTaxArrearsOnlineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_tax_arrears
     *
     * @mbggenerated Thu Mar 22 10:04:16 CST 2018
     */
    int countByExample(NeeqCompanyTaxArrearsOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_tax_arrears
     *
     * @mbggenerated Thu Mar 22 10:04:16 CST 2018
     */
    int deleteByExample(NeeqCompanyTaxArrearsOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_tax_arrears
     *
     * @mbggenerated Thu Mar 22 10:04:16 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_tax_arrears
     *
     * @mbggenerated Thu Mar 22 10:04:16 CST 2018
     */
    int insert(NeeqCompanyTaxArrearsOnline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_tax_arrears
     *
     * @mbggenerated Thu Mar 22 10:04:16 CST 2018
     */
    int insertSelective(NeeqCompanyTaxArrearsOnline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_tax_arrears
     *
     * @mbggenerated Thu Mar 22 10:04:16 CST 2018
     */
    List<NeeqCompanyTaxArrearsOnline> selectByExample(NeeqCompanyTaxArrearsOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_tax_arrears
     *
     * @mbggenerated Thu Mar 22 10:04:16 CST 2018
     */
    NeeqCompanyTaxArrearsOnline selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_tax_arrears
     *
     * @mbggenerated Thu Mar 22 10:04:16 CST 2018
     */
    int updateByExampleSelective(@Param("record") NeeqCompanyTaxArrearsOnline record, @Param("example") NeeqCompanyTaxArrearsOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_tax_arrears
     *
     * @mbggenerated Thu Mar 22 10:04:16 CST 2018
     */
    int updateByExample(@Param("record") NeeqCompanyTaxArrearsOnline record, @Param("example") NeeqCompanyTaxArrearsOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_tax_arrears
     *
     * @mbggenerated Thu Mar 22 10:04:16 CST 2018
     */
    int updateByPrimaryKeySelective(NeeqCompanyTaxArrearsOnline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_tax_arrears
     *
     * @mbggenerated Thu Mar 22 10:04:16 CST 2018
     */
    int updateByPrimaryKey(NeeqCompanyTaxArrearsOnline record);
}