package com.kf.data.mybatis.mapper.online;

import com.kf.data.mybatis.entity.online.NeeqCompanyImExportOnline;
import com.kf.data.mybatis.entity.online.NeeqCompanyImExportOnlineExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NeeqCompanyImExportOnlineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_im_ex_port
     *
     * @mbggenerated Thu Mar 22 11:46:59 CST 2018
     */
    int countByExample(NeeqCompanyImExportOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_im_ex_port
     *
     * @mbggenerated Thu Mar 22 11:46:59 CST 2018
     */
    int deleteByExample(NeeqCompanyImExportOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_im_ex_port
     *
     * @mbggenerated Thu Mar 22 11:46:59 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_im_ex_port
     *
     * @mbggenerated Thu Mar 22 11:46:59 CST 2018
     */
    int insert(NeeqCompanyImExportOnline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_im_ex_port
     *
     * @mbggenerated Thu Mar 22 11:46:59 CST 2018
     */
    int insertSelective(NeeqCompanyImExportOnline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_im_ex_port
     *
     * @mbggenerated Thu Mar 22 11:46:59 CST 2018
     */
    List<NeeqCompanyImExportOnline> selectByExample(NeeqCompanyImExportOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_im_ex_port
     *
     * @mbggenerated Thu Mar 22 11:46:59 CST 2018
     */
    NeeqCompanyImExportOnline selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_im_ex_port
     *
     * @mbggenerated Thu Mar 22 11:46:59 CST 2018
     */
    int updateByExampleSelective(@Param("record") NeeqCompanyImExportOnline record, @Param("example") NeeqCompanyImExportOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_im_ex_port
     *
     * @mbggenerated Thu Mar 22 11:46:59 CST 2018
     */
    int updateByExample(@Param("record") NeeqCompanyImExportOnline record, @Param("example") NeeqCompanyImExportOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_im_ex_port
     *
     * @mbggenerated Thu Mar 22 11:46:59 CST 2018
     */
    int updateByPrimaryKeySelective(NeeqCompanyImExportOnline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_im_ex_port
     *
     * @mbggenerated Thu Mar 22 11:46:59 CST 2018
     */
    int updateByPrimaryKey(NeeqCompanyImExportOnline record);
}