package com.kf.data.mybatis.mapper.online;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.kf.data.mybatis.entity.online.NeeqCompanyIndirectFinancingOnline;
import com.kf.data.mybatis.entity.online.NeeqCompanyIndirectFinancingOnlineExample;

public interface NeeqCompanyIndirectFinancingOnlineMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table neeq_company_indirect_financing
	 * @mbggenerated  Wed Mar 14 09:56:21 CST 2018
	 */
	int countByExample(NeeqCompanyIndirectFinancingOnlineExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table neeq_company_indirect_financing
	 * @mbggenerated  Wed Mar 14 09:56:21 CST 2018
	 */
	int deleteByExample(NeeqCompanyIndirectFinancingOnlineExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table neeq_company_indirect_financing
	 * @mbggenerated  Wed Mar 14 09:56:21 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table neeq_company_indirect_financing
	 * @mbggenerated  Wed Mar 14 09:56:21 CST 2018
	 */
	int insert(NeeqCompanyIndirectFinancingOnline record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table neeq_company_indirect_financing
	 * @mbggenerated  Wed Mar 14 09:56:21 CST 2018
	 */
	int insertSelective(NeeqCompanyIndirectFinancingOnline record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table neeq_company_indirect_financing
	 * @mbggenerated  Wed Mar 14 09:56:21 CST 2018
	 */
	List<NeeqCompanyIndirectFinancingOnline> selectByExample(NeeqCompanyIndirectFinancingOnlineExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table neeq_company_indirect_financing
	 * @mbggenerated  Wed Mar 14 09:56:21 CST 2018
	 */
	NeeqCompanyIndirectFinancingOnline selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table neeq_company_indirect_financing
	 * @mbggenerated  Wed Mar 14 09:56:21 CST 2018
	 */
	int updateByExampleSelective(@Param("record") NeeqCompanyIndirectFinancingOnline record,
			@Param("example") NeeqCompanyIndirectFinancingOnlineExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table neeq_company_indirect_financing
	 * @mbggenerated  Wed Mar 14 09:56:21 CST 2018
	 */
	int updateByExample(@Param("record") NeeqCompanyIndirectFinancingOnline record,
			@Param("example") NeeqCompanyIndirectFinancingOnlineExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table neeq_company_indirect_financing
	 * @mbggenerated  Wed Mar 14 09:56:21 CST 2018
	 */
	int updateByPrimaryKeySelective(NeeqCompanyIndirectFinancingOnline record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table neeq_company_indirect_financing
	 * @mbggenerated  Wed Mar 14 09:56:21 CST 2018
	 */
	int updateByPrimaryKey(NeeqCompanyIndirectFinancingOnline record);
}