package com.kf.data.mybatis.mapper.online;

import com.kf.data.mybatis.entity.online.NeeqCompanyCheckOnline;
import com.kf.data.mybatis.entity.online.NeeqCompanyCheckOnlineExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NeeqCompanyCheckOnlineMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table neeq_company_check
	 * @mbggenerated  Thu Mar 22 11:49:10 CST 2018
	 */
	int countByExample(NeeqCompanyCheckOnlineExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table neeq_company_check
	 * @mbggenerated  Thu Mar 22 11:49:10 CST 2018
	 */
	int deleteByExample(NeeqCompanyCheckOnlineExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table neeq_company_check
	 * @mbggenerated  Thu Mar 22 11:49:10 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table neeq_company_check
	 * @mbggenerated  Thu Mar 22 11:49:10 CST 2018
	 */
	int insert(NeeqCompanyCheckOnline record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table neeq_company_check
	 * @mbggenerated  Thu Mar 22 11:49:10 CST 2018
	 */
	int insertSelective(NeeqCompanyCheckOnline record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table neeq_company_check
	 * @mbggenerated  Thu Mar 22 11:49:10 CST 2018
	 */
	List<NeeqCompanyCheckOnline> selectByExample(NeeqCompanyCheckOnlineExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table neeq_company_check
	 * @mbggenerated  Thu Mar 22 11:49:10 CST 2018
	 */
	NeeqCompanyCheckOnline selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table neeq_company_check
	 * @mbggenerated  Thu Mar 22 11:49:10 CST 2018
	 */
	int updateByExampleSelective(@Param("record") NeeqCompanyCheckOnline record,
			@Param("example") NeeqCompanyCheckOnlineExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table neeq_company_check
	 * @mbggenerated  Thu Mar 22 11:49:10 CST 2018
	 */
	int updateByExample(@Param("record") NeeqCompanyCheckOnline record,
			@Param("example") NeeqCompanyCheckOnlineExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table neeq_company_check
	 * @mbggenerated  Thu Mar 22 11:49:10 CST 2018
	 */
	int updateByPrimaryKeySelective(NeeqCompanyCheckOnline record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table neeq_company_check
	 * @mbggenerated  Thu Mar 22 11:49:10 CST 2018
	 */
	int updateByPrimaryKey(NeeqCompanyCheckOnline record);
}