package com.kf.data.mybatis.mapper.online;

import com.kf.data.mybatis.entity.online.NeeqCompanyLawFirmOnline;
import com.kf.data.mybatis.entity.online.NeeqCompanyLawFirmOnlineExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NeeqCompanyLawFirmOnlineMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table neeq_company_law_firm
	 * @mbggenerated  Thu Mar 22 17:20:14 CST 2018
	 */
	int countByExample(NeeqCompanyLawFirmOnlineExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table neeq_company_law_firm
	 * @mbggenerated  Thu Mar 22 17:20:14 CST 2018
	 */
	int deleteByExample(NeeqCompanyLawFirmOnlineExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table neeq_company_law_firm
	 * @mbggenerated  Thu Mar 22 17:20:14 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table neeq_company_law_firm
	 * @mbggenerated  Thu Mar 22 17:20:14 CST 2018
	 */
	int insert(NeeqCompanyLawFirmOnline record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table neeq_company_law_firm
	 * @mbggenerated  Thu Mar 22 17:20:14 CST 2018
	 */
	int insertSelective(NeeqCompanyLawFirmOnline record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table neeq_company_law_firm
	 * @mbggenerated  Thu Mar 22 17:20:14 CST 2018
	 */
	List<NeeqCompanyLawFirmOnline> selectByExample(NeeqCompanyLawFirmOnlineExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table neeq_company_law_firm
	 * @mbggenerated  Thu Mar 22 17:20:14 CST 2018
	 */
	NeeqCompanyLawFirmOnline selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table neeq_company_law_firm
	 * @mbggenerated  Thu Mar 22 17:20:14 CST 2018
	 */
	int updateByExampleSelective(@Param("record") NeeqCompanyLawFirmOnline record,
			@Param("example") NeeqCompanyLawFirmOnlineExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table neeq_company_law_firm
	 * @mbggenerated  Thu Mar 22 17:20:14 CST 2018
	 */
	int updateByExample(@Param("record") NeeqCompanyLawFirmOnline record,
			@Param("example") NeeqCompanyLawFirmOnlineExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table neeq_company_law_firm
	 * @mbggenerated  Thu Mar 22 17:20:14 CST 2018
	 */
	int updateByPrimaryKeySelective(NeeqCompanyLawFirmOnline record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table neeq_company_law_firm
	 * @mbggenerated  Thu Mar 22 17:20:14 CST 2018
	 */
	int updateByPrimaryKey(NeeqCompanyLawFirmOnline record);
}