package com.kf.data.mybatis.mapper.online;

import com.kf.data.mybatis.entity.online.NeeqCompanyCaseOnline;
import com.kf.data.mybatis.entity.online.NeeqCompanyCaseOnlineExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NeeqCompanyCaseOnlineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_case
     *
     * @mbggenerated Fri Mar 16 16:32:46 CST 2018
     */
    int countByExample(NeeqCompanyCaseOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_case
     *
     * @mbggenerated Fri Mar 16 16:32:46 CST 2018
     */
    int deleteByExample(NeeqCompanyCaseOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_case
     *
     * @mbggenerated Fri Mar 16 16:32:46 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_case
     *
     * @mbggenerated Fri Mar 16 16:32:46 CST 2018
     */
    int insert(NeeqCompanyCaseOnline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_case
     *
     * @mbggenerated Fri Mar 16 16:32:46 CST 2018
     */
    int insertSelective(NeeqCompanyCaseOnline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_case
     *
     * @mbggenerated Fri Mar 16 16:32:46 CST 2018
     */
    List<NeeqCompanyCaseOnline> selectByExampleWithBLOBs(NeeqCompanyCaseOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_case
     *
     * @mbggenerated Fri Mar 16 16:32:46 CST 2018
     */
    List<NeeqCompanyCaseOnline> selectByExample(NeeqCompanyCaseOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_case
     *
     * @mbggenerated Fri Mar 16 16:32:46 CST 2018
     */
    NeeqCompanyCaseOnline selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_case
     *
     * @mbggenerated Fri Mar 16 16:32:46 CST 2018
     */
    int updateByExampleSelective(@Param("record") NeeqCompanyCaseOnline record, @Param("example") NeeqCompanyCaseOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_case
     *
     * @mbggenerated Fri Mar 16 16:32:46 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") NeeqCompanyCaseOnline record, @Param("example") NeeqCompanyCaseOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_case
     *
     * @mbggenerated Fri Mar 16 16:32:46 CST 2018
     */
    int updateByExample(@Param("record") NeeqCompanyCaseOnline record, @Param("example") NeeqCompanyCaseOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_case
     *
     * @mbggenerated Fri Mar 16 16:32:46 CST 2018
     */
    int updateByPrimaryKeySelective(NeeqCompanyCaseOnline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_case
     *
     * @mbggenerated Fri Mar 16 16:32:46 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(NeeqCompanyCaseOnline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_case
     *
     * @mbggenerated Fri Mar 16 16:32:46 CST 2018
     */
    int updateByPrimaryKey(NeeqCompanyCaseOnline record);
}