package com.kf.data.mybatis.mapper.online;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.kf.data.mybatis.entity.online.NeeqCompanyMajorSupplierOnline;
import com.kf.data.mybatis.entity.online.NeeqCompanyMajorSupplierOnlineExample;

public interface NeeqCompanyMajorSupplierOnlineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_major_supplier
     *
     * @mbggenerated Wed Mar 14 10:06:25 CST 2018
     */
    int countByExample(NeeqCompanyMajorSupplierOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_major_supplier
     *
     * @mbggenerated Wed Mar 14 10:06:25 CST 2018
     */
    int deleteByExample(NeeqCompanyMajorSupplierOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_major_supplier
     *
     * @mbggenerated Wed Mar 14 10:06:25 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_major_supplier
     *
     * @mbggenerated Wed Mar 14 10:06:25 CST 2018
     */
    int insert(NeeqCompanyMajorSupplierOnline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_major_supplier
     *
     * @mbggenerated Wed Mar 14 10:06:25 CST 2018
     */
    int insertSelective(NeeqCompanyMajorSupplierOnline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_major_supplier
     *
     * @mbggenerated Wed Mar 14 10:06:25 CST 2018
     */
    List<NeeqCompanyMajorSupplierOnline> selectByExample(NeeqCompanyMajorSupplierOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_major_supplier
     *
     * @mbggenerated Wed Mar 14 10:06:25 CST 2018
     */
    NeeqCompanyMajorSupplierOnline selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_major_supplier
     *
     * @mbggenerated Wed Mar 14 10:06:25 CST 2018
     */
    int updateByExampleSelective(@Param("record") NeeqCompanyMajorSupplierOnline record, @Param("example") NeeqCompanyMajorSupplierOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_major_supplier
     *
     * @mbggenerated Wed Mar 14 10:06:25 CST 2018
     */
    int updateByExample(@Param("record") NeeqCompanyMajorSupplierOnline record, @Param("example") NeeqCompanyMajorSupplierOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_major_supplier
     *
     * @mbggenerated Wed Mar 14 10:06:25 CST 2018
     */
    int updateByPrimaryKeySelective(NeeqCompanyMajorSupplierOnline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_major_supplier
     *
     * @mbggenerated Wed Mar 14 10:06:25 CST 2018
     */
    int updateByPrimaryKey(NeeqCompanyMajorSupplierOnline record);
}