package com.kf.data.mybatis.mapper.online;

import com.kf.data.mybatis.entity.online.TdxUpIndexOnline;
import com.kf.data.mybatis.entity.online.TdxUpIndexOnlineExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TdxUpIndexOnlineMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tdx_up_index
	 * @mbggenerated  Wed Mar 14 17:36:47 CST 2018
	 */
	int countByExample(TdxUpIndexOnlineExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tdx_up_index
	 * @mbggenerated  Wed Mar 14 17:36:47 CST 2018
	 */
	int deleteByExample(TdxUpIndexOnlineExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tdx_up_index
	 * @mbggenerated  Wed Mar 14 17:36:47 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tdx_up_index
	 * @mbggenerated  Wed Mar 14 17:36:47 CST 2018
	 */
	int insert(TdxUpIndexOnline record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tdx_up_index
	 * @mbggenerated  Wed Mar 14 17:36:47 CST 2018
	 */
	int insertSelective(TdxUpIndexOnline record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tdx_up_index
	 * @mbggenerated  Wed Mar 14 17:36:47 CST 2018
	 */
	List<TdxUpIndexOnline> selectByExample(TdxUpIndexOnlineExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tdx_up_index
	 * @mbggenerated  Wed Mar 14 17:36:47 CST 2018
	 */
	TdxUpIndexOnline selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tdx_up_index
	 * @mbggenerated  Wed Mar 14 17:36:47 CST 2018
	 */
	int updateByExampleSelective(@Param("record") TdxUpIndexOnline record,
			@Param("example") TdxUpIndexOnlineExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tdx_up_index
	 * @mbggenerated  Wed Mar 14 17:36:47 CST 2018
	 */
	int updateByExample(@Param("record") TdxUpIndexOnline record, @Param("example") TdxUpIndexOnlineExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tdx_up_index
	 * @mbggenerated  Wed Mar 14 17:36:47 CST 2018
	 */
	int updateByPrimaryKeySelective(TdxUpIndexOnline record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tdx_up_index
	 * @mbggenerated  Wed Mar 14 17:36:47 CST 2018
	 */
	int updateByPrimaryKey(TdxUpIndexOnline record);
}