package com.kf.data.mybatis.entity.tdx;

public class TdxCompanySaicWithBLOBs extends TdxCompanySaic {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tdx_company_saic.business_scope
     *
     * @mbggenerated Wed Mar 21 11:43:13 CST 2018
     */
    private String businessScope;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tdx_company_saic.main_business
     *
     * @mbggenerated Wed Mar 21 11:43:13 CST 2018
     */
    private String mainBusiness;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tdx_company_saic.business_scope
     *
     * @return the value of tdx_company_saic.business_scope
     *
     * @mbggenerated Wed Mar 21 11:43:13 CST 2018
     */
    public String getBusinessScope() {
        return businessScope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tdx_company_saic.business_scope
     *
     * @param businessScope the value for tdx_company_saic.business_scope
     *
     * @mbggenerated Wed Mar 21 11:43:13 CST 2018
     */
    public void setBusinessScope(String businessScope) {
        this.businessScope = businessScope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tdx_company_saic.main_business
     *
     * @return the value of tdx_company_saic.main_business
     *
     * @mbggenerated Wed Mar 21 11:43:13 CST 2018
     */
    public String getMainBusiness() {
        return mainBusiness;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tdx_company_saic.main_business
     *
     * @param mainBusiness the value for tdx_company_saic.main_business
     *
     * @mbggenerated Wed Mar 21 11:43:13 CST 2018
     */
    public void setMainBusiness(String mainBusiness) {
        this.mainBusiness = mainBusiness;
    }
}