package com.kf.data.mybatis.entity.tdx;

import java.util.Date;

public class TdxCompanyInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tdx_company_info.id
	 * @mbggenerated  Tue Mar 27 14:55:57 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tdx_company_info.company_id
	 * @mbggenerated  Tue Mar 27 14:55:57 CST 2018
	 */
	private String companyId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tdx_company_info.company_name
	 * @mbggenerated  Tue Mar 27 14:55:57 CST 2018
	 */
	private String companyName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tdx_company_info.short_name
	 * @mbggenerated  Tue Mar 27 14:55:57 CST 2018
	 */
	private String shortName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tdx_company_info.his_name
	 * @mbggenerated  Tue Mar 27 14:55:57 CST 2018
	 */
	private String hisName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tdx_company_info.registration_date
	 * @mbggenerated  Tue Mar 27 14:55:57 CST 2018
	 */
	private String registrationDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tdx_company_info.area
	 * @mbggenerated  Tue Mar 27 14:55:57 CST 2018
	 */
	private String area;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tdx_company_info.address
	 * @mbggenerated  Tue Mar 27 14:55:57 CST 2018
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tdx_company_info.web
	 * @mbggenerated  Tue Mar 27 14:55:57 CST 2018
	 */
	private String web;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tdx_company_info.up_time
	 * @mbggenerated  Tue Mar 27 14:55:57 CST 2018
	 */
	private Date upTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tdx_company_info.city_name
	 * @mbggenerated  Tue Mar 27 14:55:57 CST 2018
	 */
	private String cityName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tdx_company_info.stock_code
	 * @mbggenerated  Tue Mar 27 14:55:57 CST 2018
	 */
	private Integer stockCode;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tdx_company_info.id
	 * @return  the value of tdx_company_info.id
	 * @mbggenerated  Tue Mar 27 14:55:57 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tdx_company_info.id
	 * @param id  the value for tdx_company_info.id
	 * @mbggenerated  Tue Mar 27 14:55:57 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tdx_company_info.company_id
	 * @return  the value of tdx_company_info.company_id
	 * @mbggenerated  Tue Mar 27 14:55:57 CST 2018
	 */
	public String getCompanyId() {
		return companyId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tdx_company_info.company_id
	 * @param companyId  the value for tdx_company_info.company_id
	 * @mbggenerated  Tue Mar 27 14:55:57 CST 2018
	 */
	public void setCompanyId(String companyId) {
		this.companyId = companyId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tdx_company_info.company_name
	 * @return  the value of tdx_company_info.company_name
	 * @mbggenerated  Tue Mar 27 14:55:57 CST 2018
	 */
	public String getCompanyName() {
		return companyName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tdx_company_info.company_name
	 * @param companyName  the value for tdx_company_info.company_name
	 * @mbggenerated  Tue Mar 27 14:55:57 CST 2018
	 */
	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tdx_company_info.short_name
	 * @return  the value of tdx_company_info.short_name
	 * @mbggenerated  Tue Mar 27 14:55:57 CST 2018
	 */
	public String getShortName() {
		return shortName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tdx_company_info.short_name
	 * @param shortName  the value for tdx_company_info.short_name
	 * @mbggenerated  Tue Mar 27 14:55:57 CST 2018
	 */
	public void setShortName(String shortName) {
		this.shortName = shortName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tdx_company_info.his_name
	 * @return  the value of tdx_company_info.his_name
	 * @mbggenerated  Tue Mar 27 14:55:57 CST 2018
	 */
	public String getHisName() {
		return hisName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tdx_company_info.his_name
	 * @param hisName  the value for tdx_company_info.his_name
	 * @mbggenerated  Tue Mar 27 14:55:57 CST 2018
	 */
	public void setHisName(String hisName) {
		this.hisName = hisName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tdx_company_info.registration_date
	 * @return  the value of tdx_company_info.registration_date
	 * @mbggenerated  Tue Mar 27 14:55:57 CST 2018
	 */
	public String getRegistrationDate() {
		return registrationDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tdx_company_info.registration_date
	 * @param registrationDate  the value for tdx_company_info.registration_date
	 * @mbggenerated  Tue Mar 27 14:55:57 CST 2018
	 */
	public void setRegistrationDate(String registrationDate) {
		this.registrationDate = registrationDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tdx_company_info.area
	 * @return  the value of tdx_company_info.area
	 * @mbggenerated  Tue Mar 27 14:55:57 CST 2018
	 */
	public String getArea() {
		return area;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tdx_company_info.area
	 * @param area  the value for tdx_company_info.area
	 * @mbggenerated  Tue Mar 27 14:55:57 CST 2018
	 */
	public void setArea(String area) {
		this.area = area;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tdx_company_info.address
	 * @return  the value of tdx_company_info.address
	 * @mbggenerated  Tue Mar 27 14:55:57 CST 2018
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tdx_company_info.address
	 * @param address  the value for tdx_company_info.address
	 * @mbggenerated  Tue Mar 27 14:55:57 CST 2018
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tdx_company_info.web
	 * @return  the value of tdx_company_info.web
	 * @mbggenerated  Tue Mar 27 14:55:57 CST 2018
	 */
	public String getWeb() {
		return web;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tdx_company_info.web
	 * @param web  the value for tdx_company_info.web
	 * @mbggenerated  Tue Mar 27 14:55:57 CST 2018
	 */
	public void setWeb(String web) {
		this.web = web;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tdx_company_info.up_time
	 * @return  the value of tdx_company_info.up_time
	 * @mbggenerated  Tue Mar 27 14:55:57 CST 2018
	 */
	public Date getUpTime() {
		return upTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tdx_company_info.up_time
	 * @param upTime  the value for tdx_company_info.up_time
	 * @mbggenerated  Tue Mar 27 14:55:57 CST 2018
	 */
	public void setUpTime(Date upTime) {
		this.upTime = upTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tdx_company_info.city_name
	 * @return  the value of tdx_company_info.city_name
	 * @mbggenerated  Tue Mar 27 14:55:57 CST 2018
	 */
	public String getCityName() {
		return cityName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tdx_company_info.city_name
	 * @param cityName  the value for tdx_company_info.city_name
	 * @mbggenerated  Tue Mar 27 14:55:57 CST 2018
	 */
	public void setCityName(String cityName) {
		this.cityName = cityName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tdx_company_info.stock_code
	 * @return  the value of tdx_company_info.stock_code
	 * @mbggenerated  Tue Mar 27 14:55:57 CST 2018
	 */
	public Integer getStockCode() {
		return stockCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tdx_company_info.stock_code
	 * @param stockCode  the value for tdx_company_info.stock_code
	 * @mbggenerated  Tue Mar 27 14:55:57 CST 2018
	 */
	public void setStockCode(Integer stockCode) {
		this.stockCode = stockCode;
	}
}