package com.kf.data.mybatis.entity.tdx;

import java.util.Date;

public class TdxCompanyCheck {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tdx_company_check.id
     *
     * @mbggenerated Thu Mar 22 15:24:48 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tdx_company_check.company_id
     *
     * @mbggenerated Thu Mar 22 15:24:48 CST 2018
     */
    private String companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tdx_company_check.company_name
     *
     * @mbggenerated Thu Mar 22 15:24:48 CST 2018
     */
    private String companyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tdx_company_check.date
     *
     * @mbggenerated Thu Mar 22 15:24:48 CST 2018
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tdx_company_check.check_agency
     *
     * @mbggenerated Thu Mar 22 15:24:48 CST 2018
     */
    private String checkAgency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tdx_company_check.type
     *
     * @mbggenerated Thu Mar 22 15:24:48 CST 2018
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tdx_company_check.result
     *
     * @mbggenerated Thu Mar 22 15:24:48 CST 2018
     */
    private String result;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tdx_company_check.updated_at
     *
     * @mbggenerated Thu Mar 22 15:24:48 CST 2018
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tdx_company_check.id
     *
     * @return the value of tdx_company_check.id
     *
     * @mbggenerated Thu Mar 22 15:24:48 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tdx_company_check.id
     *
     * @param id the value for tdx_company_check.id
     *
     * @mbggenerated Thu Mar 22 15:24:48 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tdx_company_check.company_id
     *
     * @return the value of tdx_company_check.company_id
     *
     * @mbggenerated Thu Mar 22 15:24:48 CST 2018
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tdx_company_check.company_id
     *
     * @param companyId the value for tdx_company_check.company_id
     *
     * @mbggenerated Thu Mar 22 15:24:48 CST 2018
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tdx_company_check.company_name
     *
     * @return the value of tdx_company_check.company_name
     *
     * @mbggenerated Thu Mar 22 15:24:48 CST 2018
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tdx_company_check.company_name
     *
     * @param companyName the value for tdx_company_check.company_name
     *
     * @mbggenerated Thu Mar 22 15:24:48 CST 2018
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tdx_company_check.date
     *
     * @return the value of tdx_company_check.date
     *
     * @mbggenerated Thu Mar 22 15:24:48 CST 2018
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tdx_company_check.date
     *
     * @param date the value for tdx_company_check.date
     *
     * @mbggenerated Thu Mar 22 15:24:48 CST 2018
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tdx_company_check.check_agency
     *
     * @return the value of tdx_company_check.check_agency
     *
     * @mbggenerated Thu Mar 22 15:24:48 CST 2018
     */
    public String getCheckAgency() {
        return checkAgency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tdx_company_check.check_agency
     *
     * @param checkAgency the value for tdx_company_check.check_agency
     *
     * @mbggenerated Thu Mar 22 15:24:48 CST 2018
     */
    public void setCheckAgency(String checkAgency) {
        this.checkAgency = checkAgency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tdx_company_check.type
     *
     * @return the value of tdx_company_check.type
     *
     * @mbggenerated Thu Mar 22 15:24:48 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tdx_company_check.type
     *
     * @param type the value for tdx_company_check.type
     *
     * @mbggenerated Thu Mar 22 15:24:48 CST 2018
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tdx_company_check.result
     *
     * @return the value of tdx_company_check.result
     *
     * @mbggenerated Thu Mar 22 15:24:48 CST 2018
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tdx_company_check.result
     *
     * @param result the value for tdx_company_check.result
     *
     * @mbggenerated Thu Mar 22 15:24:48 CST 2018
     */
    public void setResult(String result) {
        this.result = result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tdx_company_check.updated_at
     *
     * @return the value of tdx_company_check.updated_at
     *
     * @mbggenerated Thu Mar 22 15:24:48 CST 2018
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tdx_company_check.updated_at
     *
     * @param updatedAt the value for tdx_company_check.updated_at
     *
     * @mbggenerated Thu Mar 22 15:24:48 CST 2018
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}