package com.kf.data.mybatis.entity.tdx;

import java.util.Date;

public class TdxCompanyBusinessModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tdx_company_business_model.id
     *
     * @mbggenerated Thu Mar 15 18:02:52 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tdx_company_business_model.company_id
     *
     * @mbggenerated Thu Mar 15 18:02:52 CST 2018
     */
    private String companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tdx_company_business_model.company_name
     *
     * @mbggenerated Thu Mar 15 18:02:52 CST 2018
     */
    private String companyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tdx_company_business_model.stock_code
     *
     * @mbggenerated Thu Mar 15 18:02:52 CST 2018
     */
    private String stockCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tdx_company_business_model.report_date
     *
     * @mbggenerated Thu Mar 15 18:02:52 CST 2018
     */
    private Date reportDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tdx_company_business_model.updated_at
     *
     * @mbggenerated Thu Mar 15 18:02:52 CST 2018
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tdx_company_business_model.model_introduction
     *
     * @mbggenerated Thu Mar 15 18:02:52 CST 2018
     */
    private String modelIntroduction;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tdx_company_business_model.id
     *
     * @return the value of tdx_company_business_model.id
     *
     * @mbggenerated Thu Mar 15 18:02:52 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tdx_company_business_model.id
     *
     * @param id the value for tdx_company_business_model.id
     *
     * @mbggenerated Thu Mar 15 18:02:52 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tdx_company_business_model.company_id
     *
     * @return the value of tdx_company_business_model.company_id
     *
     * @mbggenerated Thu Mar 15 18:02:52 CST 2018
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tdx_company_business_model.company_id
     *
     * @param companyId the value for tdx_company_business_model.company_id
     *
     * @mbggenerated Thu Mar 15 18:02:52 CST 2018
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tdx_company_business_model.company_name
     *
     * @return the value of tdx_company_business_model.company_name
     *
     * @mbggenerated Thu Mar 15 18:02:52 CST 2018
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tdx_company_business_model.company_name
     *
     * @param companyName the value for tdx_company_business_model.company_name
     *
     * @mbggenerated Thu Mar 15 18:02:52 CST 2018
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tdx_company_business_model.stock_code
     *
     * @return the value of tdx_company_business_model.stock_code
     *
     * @mbggenerated Thu Mar 15 18:02:52 CST 2018
     */
    public String getStockCode() {
        return stockCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tdx_company_business_model.stock_code
     *
     * @param stockCode the value for tdx_company_business_model.stock_code
     *
     * @mbggenerated Thu Mar 15 18:02:52 CST 2018
     */
    public void setStockCode(String stockCode) {
        this.stockCode = stockCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tdx_company_business_model.report_date
     *
     * @return the value of tdx_company_business_model.report_date
     *
     * @mbggenerated Thu Mar 15 18:02:52 CST 2018
     */
    public Date getReportDate() {
        return reportDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tdx_company_business_model.report_date
     *
     * @param reportDate the value for tdx_company_business_model.report_date
     *
     * @mbggenerated Thu Mar 15 18:02:52 CST 2018
     */
    public void setReportDate(Date reportDate) {
        this.reportDate = reportDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tdx_company_business_model.updated_at
     *
     * @return the value of tdx_company_business_model.updated_at
     *
     * @mbggenerated Thu Mar 15 18:02:52 CST 2018
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tdx_company_business_model.updated_at
     *
     * @param updatedAt the value for tdx_company_business_model.updated_at
     *
     * @mbggenerated Thu Mar 15 18:02:52 CST 2018
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tdx_company_business_model.model_introduction
     *
     * @return the value of tdx_company_business_model.model_introduction
     *
     * @mbggenerated Thu Mar 15 18:02:52 CST 2018
     */
    public String getModelIntroduction() {
        return modelIntroduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tdx_company_business_model.model_introduction
     *
     * @param modelIntroduction the value for tdx_company_business_model.model_introduction
     *
     * @mbggenerated Thu Mar 15 18:02:52 CST 2018
     */
    public void setModelIntroduction(String modelIntroduction) {
        this.modelIntroduction = modelIntroduction;
    }
}