package com.kf.data.mybatis.entity.tdx;

import java.util.Date;

public class TdxEventsInvest {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tdx_events_invest.id
	 * @mbggenerated  Wed Mar 21 11:26:11 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tdx_events_invest.event_id
	 * @mbggenerated  Wed Mar 21 11:26:11 CST 2018
	 */
	private String eventId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tdx_events_invest.event_name
	 * @mbggenerated  Wed Mar 21 11:26:11 CST 2018
	 */
	private String eventName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tdx_events_invest.event_date
	 * @mbggenerated  Wed Mar 21 11:26:11 CST 2018
	 */
	private String eventDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tdx_events_invest.investment_amount
	 * @mbggenerated  Wed Mar 21 11:26:11 CST 2018
	 */
	private String investmentAmount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tdx_events_invest.invest_ratio
	 * @mbggenerated  Wed Mar 21 11:26:11 CST 2018
	 */
	private Double investRatio;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tdx_events_invest.company_id
	 * @mbggenerated  Wed Mar 21 11:26:11 CST 2018
	 */
	private String companyId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tdx_events_invest.company_name
	 * @mbggenerated  Wed Mar 21 11:26:11 CST 2018
	 */
	private String companyName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tdx_events_invest.step
	 * @mbggenerated  Wed Mar 21 11:26:11 CST 2018
	 */
	private String step;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tdx_events_invest.up_time
	 * @mbggenerated  Wed Mar 21 11:26:11 CST 2018
	 */
	private Date upTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tdx_events_invest.description
	 * @mbggenerated  Wed Mar 21 11:26:11 CST 2018
	 */
	private String description;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tdx_events_invest.id
	 * @return  the value of tdx_events_invest.id
	 * @mbggenerated  Wed Mar 21 11:26:11 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tdx_events_invest.id
	 * @param id  the value for tdx_events_invest.id
	 * @mbggenerated  Wed Mar 21 11:26:11 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tdx_events_invest.event_id
	 * @return  the value of tdx_events_invest.event_id
	 * @mbggenerated  Wed Mar 21 11:26:11 CST 2018
	 */
	public String getEventId() {
		return eventId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tdx_events_invest.event_id
	 * @param eventId  the value for tdx_events_invest.event_id
	 * @mbggenerated  Wed Mar 21 11:26:11 CST 2018
	 */
	public void setEventId(String eventId) {
		this.eventId = eventId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tdx_events_invest.event_name
	 * @return  the value of tdx_events_invest.event_name
	 * @mbggenerated  Wed Mar 21 11:26:11 CST 2018
	 */
	public String getEventName() {
		return eventName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tdx_events_invest.event_name
	 * @param eventName  the value for tdx_events_invest.event_name
	 * @mbggenerated  Wed Mar 21 11:26:11 CST 2018
	 */
	public void setEventName(String eventName) {
		this.eventName = eventName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tdx_events_invest.event_date
	 * @return  the value of tdx_events_invest.event_date
	 * @mbggenerated  Wed Mar 21 11:26:11 CST 2018
	 */
	public String getEventDate() {
		return eventDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tdx_events_invest.event_date
	 * @param eventDate  the value for tdx_events_invest.event_date
	 * @mbggenerated  Wed Mar 21 11:26:11 CST 2018
	 */
	public void setEventDate(String eventDate) {
		this.eventDate = eventDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tdx_events_invest.investment_amount
	 * @return  the value of tdx_events_invest.investment_amount
	 * @mbggenerated  Wed Mar 21 11:26:11 CST 2018
	 */
	public String getInvestmentAmount() {
		return investmentAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tdx_events_invest.investment_amount
	 * @param investmentAmount  the value for tdx_events_invest.investment_amount
	 * @mbggenerated  Wed Mar 21 11:26:11 CST 2018
	 */
	public void setInvestmentAmount(String investmentAmount) {
		this.investmentAmount = investmentAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tdx_events_invest.invest_ratio
	 * @return  the value of tdx_events_invest.invest_ratio
	 * @mbggenerated  Wed Mar 21 11:26:11 CST 2018
	 */
	public Double getInvestRatio() {
		return investRatio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tdx_events_invest.invest_ratio
	 * @param investRatio  the value for tdx_events_invest.invest_ratio
	 * @mbggenerated  Wed Mar 21 11:26:11 CST 2018
	 */
	public void setInvestRatio(Double investRatio) {
		this.investRatio = investRatio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tdx_events_invest.company_id
	 * @return  the value of tdx_events_invest.company_id
	 * @mbggenerated  Wed Mar 21 11:26:11 CST 2018
	 */
	public String getCompanyId() {
		return companyId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tdx_events_invest.company_id
	 * @param companyId  the value for tdx_events_invest.company_id
	 * @mbggenerated  Wed Mar 21 11:26:11 CST 2018
	 */
	public void setCompanyId(String companyId) {
		this.companyId = companyId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tdx_events_invest.company_name
	 * @return  the value of tdx_events_invest.company_name
	 * @mbggenerated  Wed Mar 21 11:26:11 CST 2018
	 */
	public String getCompanyName() {
		return companyName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tdx_events_invest.company_name
	 * @param companyName  the value for tdx_events_invest.company_name
	 * @mbggenerated  Wed Mar 21 11:26:11 CST 2018
	 */
	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tdx_events_invest.step
	 * @return  the value of tdx_events_invest.step
	 * @mbggenerated  Wed Mar 21 11:26:11 CST 2018
	 */
	public String getStep() {
		return step;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tdx_events_invest.step
	 * @param step  the value for tdx_events_invest.step
	 * @mbggenerated  Wed Mar 21 11:26:11 CST 2018
	 */
	public void setStep(String step) {
		this.step = step;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tdx_events_invest.up_time
	 * @return  the value of tdx_events_invest.up_time
	 * @mbggenerated  Wed Mar 21 11:26:11 CST 2018
	 */
	public Date getUpTime() {
		return upTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tdx_events_invest.up_time
	 * @param upTime  the value for tdx_events_invest.up_time
	 * @mbggenerated  Wed Mar 21 11:26:11 CST 2018
	 */
	public void setUpTime(Date upTime) {
		this.upTime = upTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tdx_events_invest.description
	 * @return  the value of tdx_events_invest.description
	 * @mbggenerated  Wed Mar 21 11:26:11 CST 2018
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tdx_events_invest.description
	 * @param description  the value for tdx_events_invest.description
	 * @mbggenerated  Wed Mar 21 11:26:11 CST 2018
	 */
	public void setDescription(String description) {
		this.description = description;
	}
}