package com.kf.data.mybatis.entity.tdx;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class TdxEventsIssueEffectExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tdx_events_issue_effect
     *
     * @mbggenerated Tue Mar 20 17:52:12 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tdx_events_issue_effect
     *
     * @mbggenerated Tue Mar 20 17:52:12 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tdx_events_issue_effect
     *
     * @mbggenerated Tue Mar 20 17:52:12 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_events_issue_effect
     *
     * @mbggenerated Tue Mar 20 17:52:12 CST 2018
     */
    public TdxEventsIssueEffectExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_events_issue_effect
     *
     * @mbggenerated Tue Mar 20 17:52:12 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_events_issue_effect
     *
     * @mbggenerated Tue Mar 20 17:52:12 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_events_issue_effect
     *
     * @mbggenerated Tue Mar 20 17:52:12 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_events_issue_effect
     *
     * @mbggenerated Tue Mar 20 17:52:12 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_events_issue_effect
     *
     * @mbggenerated Tue Mar 20 17:52:12 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_events_issue_effect
     *
     * @mbggenerated Tue Mar 20 17:52:12 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_events_issue_effect
     *
     * @mbggenerated Tue Mar 20 17:52:12 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_events_issue_effect
     *
     * @mbggenerated Tue Mar 20 17:52:12 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_events_issue_effect
     *
     * @mbggenerated Tue Mar 20 17:52:12 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_events_issue_effect
     *
     * @mbggenerated Tue Mar 20 17:52:12 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tdx_events_issue_effect
     *
     * @mbggenerated Tue Mar 20 17:52:12 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andStockCodeIsNull() {
            addCriterion("stock_code is null");
            return (Criteria) this;
        }

        public Criteria andStockCodeIsNotNull() {
            addCriterion("stock_code is not null");
            return (Criteria) this;
        }

        public Criteria andStockCodeEqualTo(String value) {
            addCriterion("stock_code =", value, "stockCode");
            return (Criteria) this;
        }

        public Criteria andStockCodeNotEqualTo(String value) {
            addCriterion("stock_code <>", value, "stockCode");
            return (Criteria) this;
        }

        public Criteria andStockCodeGreaterThan(String value) {
            addCriterion("stock_code >", value, "stockCode");
            return (Criteria) this;
        }

        public Criteria andStockCodeGreaterThanOrEqualTo(String value) {
            addCriterion("stock_code >=", value, "stockCode");
            return (Criteria) this;
        }

        public Criteria andStockCodeLessThan(String value) {
            addCriterion("stock_code <", value, "stockCode");
            return (Criteria) this;
        }

        public Criteria andStockCodeLessThanOrEqualTo(String value) {
            addCriterion("stock_code <=", value, "stockCode");
            return (Criteria) this;
        }

        public Criteria andStockCodeLike(String value) {
            addCriterion("stock_code like", value, "stockCode");
            return (Criteria) this;
        }

        public Criteria andStockCodeNotLike(String value) {
            addCriterion("stock_code not like", value, "stockCode");
            return (Criteria) this;
        }

        public Criteria andStockCodeIn(List<String> values) {
            addCriterion("stock_code in", values, "stockCode");
            return (Criteria) this;
        }

        public Criteria andStockCodeNotIn(List<String> values) {
            addCriterion("stock_code not in", values, "stockCode");
            return (Criteria) this;
        }

        public Criteria andStockCodeBetween(String value1, String value2) {
            addCriterion("stock_code between", value1, value2, "stockCode");
            return (Criteria) this;
        }

        public Criteria andStockCodeNotBetween(String value1, String value2) {
            addCriterion("stock_code not between", value1, value2, "stockCode");
            return (Criteria) this;
        }

        public Criteria andCompanyIdIsNull() {
            addCriterion("company_id is null");
            return (Criteria) this;
        }

        public Criteria andCompanyIdIsNotNull() {
            addCriterion("company_id is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyIdEqualTo(String value) {
            addCriterion("company_id =", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotEqualTo(String value) {
            addCriterion("company_id <>", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdGreaterThan(String value) {
            addCriterion("company_id >", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdGreaterThanOrEqualTo(String value) {
            addCriterion("company_id >=", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdLessThan(String value) {
            addCriterion("company_id <", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdLessThanOrEqualTo(String value) {
            addCriterion("company_id <=", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdLike(String value) {
            addCriterion("company_id like", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotLike(String value) {
            addCriterion("company_id not like", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdIn(List<String> values) {
            addCriterion("company_id in", values, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotIn(List<String> values) {
            addCriterion("company_id not in", values, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdBetween(String value1, String value2) {
            addCriterion("company_id between", value1, value2, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotBetween(String value1, String value2) {
            addCriterion("company_id not between", value1, value2, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyNameIsNull() {
            addCriterion("company_name is null");
            return (Criteria) this;
        }

        public Criteria andCompanyNameIsNotNull() {
            addCriterion("company_name is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyNameEqualTo(String value) {
            addCriterion("company_name =", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotEqualTo(String value) {
            addCriterion("company_name <>", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameGreaterThan(String value) {
            addCriterion("company_name >", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameGreaterThanOrEqualTo(String value) {
            addCriterion("company_name >=", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameLessThan(String value) {
            addCriterion("company_name <", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameLessThanOrEqualTo(String value) {
            addCriterion("company_name <=", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameLike(String value) {
            addCriterion("company_name like", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotLike(String value) {
            addCriterion("company_name not like", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameIn(List<String> values) {
            addCriterion("company_name in", values, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotIn(List<String> values) {
            addCriterion("company_name not in", values, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameBetween(String value1, String value2) {
            addCriterion("company_name between", value1, value2, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotBetween(String value1, String value2) {
            addCriterion("company_name not between", value1, value2, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyShortnameIsNull() {
            addCriterion("company_shortname is null");
            return (Criteria) this;
        }

        public Criteria andCompanyShortnameIsNotNull() {
            addCriterion("company_shortname is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyShortnameEqualTo(String value) {
            addCriterion("company_shortname =", value, "companyShortname");
            return (Criteria) this;
        }

        public Criteria andCompanyShortnameNotEqualTo(String value) {
            addCriterion("company_shortname <>", value, "companyShortname");
            return (Criteria) this;
        }

        public Criteria andCompanyShortnameGreaterThan(String value) {
            addCriterion("company_shortname >", value, "companyShortname");
            return (Criteria) this;
        }

        public Criteria andCompanyShortnameGreaterThanOrEqualTo(String value) {
            addCriterion("company_shortname >=", value, "companyShortname");
            return (Criteria) this;
        }

        public Criteria andCompanyShortnameLessThan(String value) {
            addCriterion("company_shortname <", value, "companyShortname");
            return (Criteria) this;
        }

        public Criteria andCompanyShortnameLessThanOrEqualTo(String value) {
            addCriterion("company_shortname <=", value, "companyShortname");
            return (Criteria) this;
        }

        public Criteria andCompanyShortnameLike(String value) {
            addCriterion("company_shortname like", value, "companyShortname");
            return (Criteria) this;
        }

        public Criteria andCompanyShortnameNotLike(String value) {
            addCriterion("company_shortname not like", value, "companyShortname");
            return (Criteria) this;
        }

        public Criteria andCompanyShortnameIn(List<String> values) {
            addCriterion("company_shortname in", values, "companyShortname");
            return (Criteria) this;
        }

        public Criteria andCompanyShortnameNotIn(List<String> values) {
            addCriterion("company_shortname not in", values, "companyShortname");
            return (Criteria) this;
        }

        public Criteria andCompanyShortnameBetween(String value1, String value2) {
            addCriterion("company_shortname between", value1, value2, "companyShortname");
            return (Criteria) this;
        }

        public Criteria andCompanyShortnameNotBetween(String value1, String value2) {
            addCriterion("company_shortname not between", value1, value2, "companyShortname");
            return (Criteria) this;
        }

        public Criteria andDateEffectIsNull() {
            addCriterion("date_effect is null");
            return (Criteria) this;
        }

        public Criteria andDateEffectIsNotNull() {
            addCriterion("date_effect is not null");
            return (Criteria) this;
        }

        public Criteria andDateEffectEqualTo(Date value) {
            addCriterionForJDBCDate("date_effect =", value, "dateEffect");
            return (Criteria) this;
        }

        public Criteria andDateEffectNotEqualTo(Date value) {
            addCriterionForJDBCDate("date_effect <>", value, "dateEffect");
            return (Criteria) this;
        }

        public Criteria andDateEffectGreaterThan(Date value) {
            addCriterionForJDBCDate("date_effect >", value, "dateEffect");
            return (Criteria) this;
        }

        public Criteria andDateEffectGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("date_effect >=", value, "dateEffect");
            return (Criteria) this;
        }

        public Criteria andDateEffectLessThan(Date value) {
            addCriterionForJDBCDate("date_effect <", value, "dateEffect");
            return (Criteria) this;
        }

        public Criteria andDateEffectLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("date_effect <=", value, "dateEffect");
            return (Criteria) this;
        }

        public Criteria andDateEffectIn(List<Date> values) {
            addCriterionForJDBCDate("date_effect in", values, "dateEffect");
            return (Criteria) this;
        }

        public Criteria andDateEffectNotIn(List<Date> values) {
            addCriterionForJDBCDate("date_effect not in", values, "dateEffect");
            return (Criteria) this;
        }

        public Criteria andDateEffectBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("date_effect between", value1, value2, "dateEffect");
            return (Criteria) this;
        }

        public Criteria andDateEffectNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("date_effect not between", value1, value2, "dateEffect");
            return (Criteria) this;
        }

        public Criteria andDatePlanIsNull() {
            addCriterion("date_plan is null");
            return (Criteria) this;
        }

        public Criteria andDatePlanIsNotNull() {
            addCriterion("date_plan is not null");
            return (Criteria) this;
        }

        public Criteria andDatePlanEqualTo(Date value) {
            addCriterionForJDBCDate("date_plan =", value, "datePlan");
            return (Criteria) this;
        }

        public Criteria andDatePlanNotEqualTo(Date value) {
            addCriterionForJDBCDate("date_plan <>", value, "datePlan");
            return (Criteria) this;
        }

        public Criteria andDatePlanGreaterThan(Date value) {
            addCriterionForJDBCDate("date_plan >", value, "datePlan");
            return (Criteria) this;
        }

        public Criteria andDatePlanGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("date_plan >=", value, "datePlan");
            return (Criteria) this;
        }

        public Criteria andDatePlanLessThan(Date value) {
            addCriterionForJDBCDate("date_plan <", value, "datePlan");
            return (Criteria) this;
        }

        public Criteria andDatePlanLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("date_plan <=", value, "datePlan");
            return (Criteria) this;
        }

        public Criteria andDatePlanIn(List<Date> values) {
            addCriterionForJDBCDate("date_plan in", values, "datePlan");
            return (Criteria) this;
        }

        public Criteria andDatePlanNotIn(List<Date> values) {
            addCriterionForJDBCDate("date_plan not in", values, "datePlan");
            return (Criteria) this;
        }

        public Criteria andDatePlanBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("date_plan between", value1, value2, "datePlan");
            return (Criteria) this;
        }

        public Criteria andDatePlanNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("date_plan not between", value1, value2, "datePlan");
            return (Criteria) this;
        }

        public Criteria andIfDependentIsNull() {
            addCriterion("if_dependent is null");
            return (Criteria) this;
        }

        public Criteria andIfDependentIsNotNull() {
            addCriterion("if_dependent is not null");
            return (Criteria) this;
        }

        public Criteria andIfDependentEqualTo(String value) {
            addCriterion("if_dependent =", value, "ifDependent");
            return (Criteria) this;
        }

        public Criteria andIfDependentNotEqualTo(String value) {
            addCriterion("if_dependent <>", value, "ifDependent");
            return (Criteria) this;
        }

        public Criteria andIfDependentGreaterThan(String value) {
            addCriterion("if_dependent >", value, "ifDependent");
            return (Criteria) this;
        }

        public Criteria andIfDependentGreaterThanOrEqualTo(String value) {
            addCriterion("if_dependent >=", value, "ifDependent");
            return (Criteria) this;
        }

        public Criteria andIfDependentLessThan(String value) {
            addCriterion("if_dependent <", value, "ifDependent");
            return (Criteria) this;
        }

        public Criteria andIfDependentLessThanOrEqualTo(String value) {
            addCriterion("if_dependent <=", value, "ifDependent");
            return (Criteria) this;
        }

        public Criteria andIfDependentLike(String value) {
            addCriterion("if_dependent like", value, "ifDependent");
            return (Criteria) this;
        }

        public Criteria andIfDependentNotLike(String value) {
            addCriterion("if_dependent not like", value, "ifDependent");
            return (Criteria) this;
        }

        public Criteria andIfDependentIn(List<String> values) {
            addCriterion("if_dependent in", values, "ifDependent");
            return (Criteria) this;
        }

        public Criteria andIfDependentNotIn(List<String> values) {
            addCriterion("if_dependent not in", values, "ifDependent");
            return (Criteria) this;
        }

        public Criteria andIfDependentBetween(String value1, String value2) {
            addCriterion("if_dependent between", value1, value2, "ifDependent");
            return (Criteria) this;
        }

        public Criteria andIfDependentNotBetween(String value1, String value2) {
            addCriterion("if_dependent not between", value1, value2, "ifDependent");
            return (Criteria) this;
        }

        public Criteria andIfStockTradeIsNull() {
            addCriterion("if_stock_trade is null");
            return (Criteria) this;
        }

        public Criteria andIfStockTradeIsNotNull() {
            addCriterion("if_stock_trade is not null");
            return (Criteria) this;
        }

        public Criteria andIfStockTradeEqualTo(String value) {
            addCriterion("if_stock_trade =", value, "ifStockTrade");
            return (Criteria) this;
        }

        public Criteria andIfStockTradeNotEqualTo(String value) {
            addCriterion("if_stock_trade <>", value, "ifStockTrade");
            return (Criteria) this;
        }

        public Criteria andIfStockTradeGreaterThan(String value) {
            addCriterion("if_stock_trade >", value, "ifStockTrade");
            return (Criteria) this;
        }

        public Criteria andIfStockTradeGreaterThanOrEqualTo(String value) {
            addCriterion("if_stock_trade >=", value, "ifStockTrade");
            return (Criteria) this;
        }

        public Criteria andIfStockTradeLessThan(String value) {
            addCriterion("if_stock_trade <", value, "ifStockTrade");
            return (Criteria) this;
        }

        public Criteria andIfStockTradeLessThanOrEqualTo(String value) {
            addCriterion("if_stock_trade <=", value, "ifStockTrade");
            return (Criteria) this;
        }

        public Criteria andIfStockTradeLike(String value) {
            addCriterion("if_stock_trade like", value, "ifStockTrade");
            return (Criteria) this;
        }

        public Criteria andIfStockTradeNotLike(String value) {
            addCriterion("if_stock_trade not like", value, "ifStockTrade");
            return (Criteria) this;
        }

        public Criteria andIfStockTradeIn(List<String> values) {
            addCriterion("if_stock_trade in", values, "ifStockTrade");
            return (Criteria) this;
        }

        public Criteria andIfStockTradeNotIn(List<String> values) {
            addCriterion("if_stock_trade not in", values, "ifStockTrade");
            return (Criteria) this;
        }

        public Criteria andIfStockTradeBetween(String value1, String value2) {
            addCriterion("if_stock_trade between", value1, value2, "ifStockTrade");
            return (Criteria) this;
        }

        public Criteria andIfStockTradeNotBetween(String value1, String value2) {
            addCriterion("if_stock_trade not between", value1, value2, "ifStockTrade");
            return (Criteria) this;
        }

        public Criteria andObjNameIsNull() {
            addCriterion("obj_name is null");
            return (Criteria) this;
        }

        public Criteria andObjNameIsNotNull() {
            addCriterion("obj_name is not null");
            return (Criteria) this;
        }

        public Criteria andObjNameEqualTo(String value) {
            addCriterion("obj_name =", value, "objName");
            return (Criteria) this;
        }

        public Criteria andObjNameNotEqualTo(String value) {
            addCriterion("obj_name <>", value, "objName");
            return (Criteria) this;
        }

        public Criteria andObjNameGreaterThan(String value) {
            addCriterion("obj_name >", value, "objName");
            return (Criteria) this;
        }

        public Criteria andObjNameGreaterThanOrEqualTo(String value) {
            addCriterion("obj_name >=", value, "objName");
            return (Criteria) this;
        }

        public Criteria andObjNameLessThan(String value) {
            addCriterion("obj_name <", value, "objName");
            return (Criteria) this;
        }

        public Criteria andObjNameLessThanOrEqualTo(String value) {
            addCriterion("obj_name <=", value, "objName");
            return (Criteria) this;
        }

        public Criteria andObjNameLike(String value) {
            addCriterion("obj_name like", value, "objName");
            return (Criteria) this;
        }

        public Criteria andObjNameNotLike(String value) {
            addCriterion("obj_name not like", value, "objName");
            return (Criteria) this;
        }

        public Criteria andObjNameIn(List<String> values) {
            addCriterion("obj_name in", values, "objName");
            return (Criteria) this;
        }

        public Criteria andObjNameNotIn(List<String> values) {
            addCriterion("obj_name not in", values, "objName");
            return (Criteria) this;
        }

        public Criteria andObjNameBetween(String value1, String value2) {
            addCriterion("obj_name between", value1, value2, "objName");
            return (Criteria) this;
        }

        public Criteria andObjNameNotBetween(String value1, String value2) {
            addCriterion("obj_name not between", value1, value2, "objName");
            return (Criteria) this;
        }

        public Criteria andPricingRuleIsNull() {
            addCriterion("pricing_rule is null");
            return (Criteria) this;
        }

        public Criteria andPricingRuleIsNotNull() {
            addCriterion("pricing_rule is not null");
            return (Criteria) this;
        }

        public Criteria andPricingRuleEqualTo(String value) {
            addCriterion("pricing_rule =", value, "pricingRule");
            return (Criteria) this;
        }

        public Criteria andPricingRuleNotEqualTo(String value) {
            addCriterion("pricing_rule <>", value, "pricingRule");
            return (Criteria) this;
        }

        public Criteria andPricingRuleGreaterThan(String value) {
            addCriterion("pricing_rule >", value, "pricingRule");
            return (Criteria) this;
        }

        public Criteria andPricingRuleGreaterThanOrEqualTo(String value) {
            addCriterion("pricing_rule >=", value, "pricingRule");
            return (Criteria) this;
        }

        public Criteria andPricingRuleLessThan(String value) {
            addCriterion("pricing_rule <", value, "pricingRule");
            return (Criteria) this;
        }

        public Criteria andPricingRuleLessThanOrEqualTo(String value) {
            addCriterion("pricing_rule <=", value, "pricingRule");
            return (Criteria) this;
        }

        public Criteria andPricingRuleLike(String value) {
            addCriterion("pricing_rule like", value, "pricingRule");
            return (Criteria) this;
        }

        public Criteria andPricingRuleNotLike(String value) {
            addCriterion("pricing_rule not like", value, "pricingRule");
            return (Criteria) this;
        }

        public Criteria andPricingRuleIn(List<String> values) {
            addCriterion("pricing_rule in", values, "pricingRule");
            return (Criteria) this;
        }

        public Criteria andPricingRuleNotIn(List<String> values) {
            addCriterion("pricing_rule not in", values, "pricingRule");
            return (Criteria) this;
        }

        public Criteria andPricingRuleBetween(String value1, String value2) {
            addCriterion("pricing_rule between", value1, value2, "pricingRule");
            return (Criteria) this;
        }

        public Criteria andPricingRuleNotBetween(String value1, String value2) {
            addCriterion("pricing_rule not between", value1, value2, "pricingRule");
            return (Criteria) this;
        }

        public Criteria andFundTotalIsNull() {
            addCriterion("fund_total is null");
            return (Criteria) this;
        }

        public Criteria andFundTotalIsNotNull() {
            addCriterion("fund_total is not null");
            return (Criteria) this;
        }

        public Criteria andFundTotalEqualTo(Double value) {
            addCriterion("fund_total =", value, "fundTotal");
            return (Criteria) this;
        }

        public Criteria andFundTotalNotEqualTo(Double value) {
            addCriterion("fund_total <>", value, "fundTotal");
            return (Criteria) this;
        }

        public Criteria andFundTotalGreaterThan(Double value) {
            addCriterion("fund_total >", value, "fundTotal");
            return (Criteria) this;
        }

        public Criteria andFundTotalGreaterThanOrEqualTo(Double value) {
            addCriterion("fund_total >=", value, "fundTotal");
            return (Criteria) this;
        }

        public Criteria andFundTotalLessThan(Double value) {
            addCriterion("fund_total <", value, "fundTotal");
            return (Criteria) this;
        }

        public Criteria andFundTotalLessThanOrEqualTo(Double value) {
            addCriterion("fund_total <=", value, "fundTotal");
            return (Criteria) this;
        }

        public Criteria andFundTotalIn(List<Double> values) {
            addCriterion("fund_total in", values, "fundTotal");
            return (Criteria) this;
        }

        public Criteria andFundTotalNotIn(List<Double> values) {
            addCriterion("fund_total not in", values, "fundTotal");
            return (Criteria) this;
        }

        public Criteria andFundTotalBetween(Double value1, Double value2) {
            addCriterion("fund_total between", value1, value2, "fundTotal");
            return (Criteria) this;
        }

        public Criteria andFundTotalNotBetween(Double value1, Double value2) {
            addCriterion("fund_total not between", value1, value2, "fundTotal");
            return (Criteria) this;
        }

        public Criteria andFundCashIsNull() {
            addCriterion("fund_cash is null");
            return (Criteria) this;
        }

        public Criteria andFundCashIsNotNull() {
            addCriterion("fund_cash is not null");
            return (Criteria) this;
        }

        public Criteria andFundCashEqualTo(Double value) {
            addCriterion("fund_cash =", value, "fundCash");
            return (Criteria) this;
        }

        public Criteria andFundCashNotEqualTo(Double value) {
            addCriterion("fund_cash <>", value, "fundCash");
            return (Criteria) this;
        }

        public Criteria andFundCashGreaterThan(Double value) {
            addCriterion("fund_cash >", value, "fundCash");
            return (Criteria) this;
        }

        public Criteria andFundCashGreaterThanOrEqualTo(Double value) {
            addCriterion("fund_cash >=", value, "fundCash");
            return (Criteria) this;
        }

        public Criteria andFundCashLessThan(Double value) {
            addCriterion("fund_cash <", value, "fundCash");
            return (Criteria) this;
        }

        public Criteria andFundCashLessThanOrEqualTo(Double value) {
            addCriterion("fund_cash <=", value, "fundCash");
            return (Criteria) this;
        }

        public Criteria andFundCashIn(List<Double> values) {
            addCriterion("fund_cash in", values, "fundCash");
            return (Criteria) this;
        }

        public Criteria andFundCashNotIn(List<Double> values) {
            addCriterion("fund_cash not in", values, "fundCash");
            return (Criteria) this;
        }

        public Criteria andFundCashBetween(Double value1, Double value2) {
            addCriterion("fund_cash between", value1, value2, "fundCash");
            return (Criteria) this;
        }

        public Criteria andFundCashNotBetween(Double value1, Double value2) {
            addCriterion("fund_cash not between", value1, value2, "fundCash");
            return (Criteria) this;
        }

        public Criteria andQuantIsNull() {
            addCriterion("quant is null");
            return (Criteria) this;
        }

        public Criteria andQuantIsNotNull() {
            addCriterion("quant is not null");
            return (Criteria) this;
        }

        public Criteria andQuantEqualTo(Double value) {
            addCriterion("quant =", value, "quant");
            return (Criteria) this;
        }

        public Criteria andQuantNotEqualTo(Double value) {
            addCriterion("quant <>", value, "quant");
            return (Criteria) this;
        }

        public Criteria andQuantGreaterThan(Double value) {
            addCriterion("quant >", value, "quant");
            return (Criteria) this;
        }

        public Criteria andQuantGreaterThanOrEqualTo(Double value) {
            addCriterion("quant >=", value, "quant");
            return (Criteria) this;
        }

        public Criteria andQuantLessThan(Double value) {
            addCriterion("quant <", value, "quant");
            return (Criteria) this;
        }

        public Criteria andQuantLessThanOrEqualTo(Double value) {
            addCriterion("quant <=", value, "quant");
            return (Criteria) this;
        }

        public Criteria andQuantIn(List<Double> values) {
            addCriterion("quant in", values, "quant");
            return (Criteria) this;
        }

        public Criteria andQuantNotIn(List<Double> values) {
            addCriterion("quant not in", values, "quant");
            return (Criteria) this;
        }

        public Criteria andQuantBetween(Double value1, Double value2) {
            addCriterion("quant between", value1, value2, "quant");
            return (Criteria) this;
        }

        public Criteria andQuantNotBetween(Double value1, Double value2) {
            addCriterion("quant not between", value1, value2, "quant");
            return (Criteria) this;
        }

        public Criteria andPriceIsNull() {
            addCriterion("price is null");
            return (Criteria) this;
        }

        public Criteria andPriceIsNotNull() {
            addCriterion("price is not null");
            return (Criteria) this;
        }

        public Criteria andPriceEqualTo(Double value) {
            addCriterion("price =", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotEqualTo(Double value) {
            addCriterion("price <>", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThan(Double value) {
            addCriterion("price >", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThanOrEqualTo(Double value) {
            addCriterion("price >=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThan(Double value) {
            addCriterion("price <", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThanOrEqualTo(Double value) {
            addCriterion("price <=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceIn(List<Double> values) {
            addCriterion("price in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotIn(List<Double> values) {
            addCriterion("price not in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceBetween(Double value1, Double value2) {
            addCriterion("price between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotBetween(Double value1, Double value2) {
            addCriterion("price not between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andPriceCloseIsNull() {
            addCriterion("price_close is null");
            return (Criteria) this;
        }

        public Criteria andPriceCloseIsNotNull() {
            addCriterion("price_close is not null");
            return (Criteria) this;
        }

        public Criteria andPriceCloseEqualTo(Double value) {
            addCriterion("price_close =", value, "priceClose");
            return (Criteria) this;
        }

        public Criteria andPriceCloseNotEqualTo(Double value) {
            addCriterion("price_close <>", value, "priceClose");
            return (Criteria) this;
        }

        public Criteria andPriceCloseGreaterThan(Double value) {
            addCriterion("price_close >", value, "priceClose");
            return (Criteria) this;
        }

        public Criteria andPriceCloseGreaterThanOrEqualTo(Double value) {
            addCriterion("price_close >=", value, "priceClose");
            return (Criteria) this;
        }

        public Criteria andPriceCloseLessThan(Double value) {
            addCriterion("price_close <", value, "priceClose");
            return (Criteria) this;
        }

        public Criteria andPriceCloseLessThanOrEqualTo(Double value) {
            addCriterion("price_close <=", value, "priceClose");
            return (Criteria) this;
        }

        public Criteria andPriceCloseIn(List<Double> values) {
            addCriterion("price_close in", values, "priceClose");
            return (Criteria) this;
        }

        public Criteria andPriceCloseNotIn(List<Double> values) {
            addCriterion("price_close not in", values, "priceClose");
            return (Criteria) this;
        }

        public Criteria andPriceCloseBetween(Double value1, Double value2) {
            addCriterion("price_close between", value1, value2, "priceClose");
            return (Criteria) this;
        }

        public Criteria andPriceCloseNotBetween(Double value1, Double value2) {
            addCriterion("price_close not between", value1, value2, "priceClose");
            return (Criteria) this;
        }

        public Criteria andRatioChangeIsNull() {
            addCriterion("ratio_change is null");
            return (Criteria) this;
        }

        public Criteria andRatioChangeIsNotNull() {
            addCriterion("ratio_change is not null");
            return (Criteria) this;
        }

        public Criteria andRatioChangeEqualTo(Double value) {
            addCriterion("ratio_change =", value, "ratioChange");
            return (Criteria) this;
        }

        public Criteria andRatioChangeNotEqualTo(Double value) {
            addCriterion("ratio_change <>", value, "ratioChange");
            return (Criteria) this;
        }

        public Criteria andRatioChangeGreaterThan(Double value) {
            addCriterion("ratio_change >", value, "ratioChange");
            return (Criteria) this;
        }

        public Criteria andRatioChangeGreaterThanOrEqualTo(Double value) {
            addCriterion("ratio_change >=", value, "ratioChange");
            return (Criteria) this;
        }

        public Criteria andRatioChangeLessThan(Double value) {
            addCriterion("ratio_change <", value, "ratioChange");
            return (Criteria) this;
        }

        public Criteria andRatioChangeLessThanOrEqualTo(Double value) {
            addCriterion("ratio_change <=", value, "ratioChange");
            return (Criteria) this;
        }

        public Criteria andRatioChangeIn(List<Double> values) {
            addCriterion("ratio_change in", values, "ratioChange");
            return (Criteria) this;
        }

        public Criteria andRatioChangeNotIn(List<Double> values) {
            addCriterion("ratio_change not in", values, "ratioChange");
            return (Criteria) this;
        }

        public Criteria andRatioChangeBetween(Double value1, Double value2) {
            addCriterion("ratio_change between", value1, value2, "ratioChange");
            return (Criteria) this;
        }

        public Criteria andRatioChangeNotBetween(Double value1, Double value2) {
            addCriterion("ratio_change not between", value1, value2, "ratioChange");
            return (Criteria) this;
        }

        public Criteria andDtDelayPayIsNull() {
            addCriterion("dt_delay_pay is null");
            return (Criteria) this;
        }

        public Criteria andDtDelayPayIsNotNull() {
            addCriterion("dt_delay_pay is not null");
            return (Criteria) this;
        }

        public Criteria andDtDelayPayEqualTo(Date value) {
            addCriterionForJDBCDate("dt_delay_pay =", value, "dtDelayPay");
            return (Criteria) this;
        }

        public Criteria andDtDelayPayNotEqualTo(Date value) {
            addCriterionForJDBCDate("dt_delay_pay <>", value, "dtDelayPay");
            return (Criteria) this;
        }

        public Criteria andDtDelayPayGreaterThan(Date value) {
            addCriterionForJDBCDate("dt_delay_pay >", value, "dtDelayPay");
            return (Criteria) this;
        }

        public Criteria andDtDelayPayGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("dt_delay_pay >=", value, "dtDelayPay");
            return (Criteria) this;
        }

        public Criteria andDtDelayPayLessThan(Date value) {
            addCriterionForJDBCDate("dt_delay_pay <", value, "dtDelayPay");
            return (Criteria) this;
        }

        public Criteria andDtDelayPayLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("dt_delay_pay <=", value, "dtDelayPay");
            return (Criteria) this;
        }

        public Criteria andDtDelayPayIn(List<Date> values) {
            addCriterionForJDBCDate("dt_delay_pay in", values, "dtDelayPay");
            return (Criteria) this;
        }

        public Criteria andDtDelayPayNotIn(List<Date> values) {
            addCriterionForJDBCDate("dt_delay_pay not in", values, "dtDelayPay");
            return (Criteria) this;
        }

        public Criteria andDtDelayPayBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("dt_delay_pay between", value1, value2, "dtDelayPay");
            return (Criteria) this;
        }

        public Criteria andDtDelayPayNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("dt_delay_pay not between", value1, value2, "dtDelayPay");
            return (Criteria) this;
        }

        public Criteria andDateBuyIsNull() {
            addCriterion("date_buy is null");
            return (Criteria) this;
        }

        public Criteria andDateBuyIsNotNull() {
            addCriterion("date_buy is not null");
            return (Criteria) this;
        }

        public Criteria andDateBuyEqualTo(Date value) {
            addCriterionForJDBCDate("date_buy =", value, "dateBuy");
            return (Criteria) this;
        }

        public Criteria andDateBuyNotEqualTo(Date value) {
            addCriterionForJDBCDate("date_buy <>", value, "dateBuy");
            return (Criteria) this;
        }

        public Criteria andDateBuyGreaterThan(Date value) {
            addCriterionForJDBCDate("date_buy >", value, "dateBuy");
            return (Criteria) this;
        }

        public Criteria andDateBuyGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("date_buy >=", value, "dateBuy");
            return (Criteria) this;
        }

        public Criteria andDateBuyLessThan(Date value) {
            addCriterionForJDBCDate("date_buy <", value, "dateBuy");
            return (Criteria) this;
        }

        public Criteria andDateBuyLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("date_buy <=", value, "dateBuy");
            return (Criteria) this;
        }

        public Criteria andDateBuyIn(List<Date> values) {
            addCriterionForJDBCDate("date_buy in", values, "dateBuy");
            return (Criteria) this;
        }

        public Criteria andDateBuyNotIn(List<Date> values) {
            addCriterionForJDBCDate("date_buy not in", values, "dateBuy");
            return (Criteria) this;
        }

        public Criteria andDateBuyBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("date_buy between", value1, value2, "dateBuy");
            return (Criteria) this;
        }

        public Criteria andDateBuyNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("date_buy not between", value1, value2, "dateBuy");
            return (Criteria) this;
        }

        public Criteria andDateRegistIsNull() {
            addCriterion("date_regist is null");
            return (Criteria) this;
        }

        public Criteria andDateRegistIsNotNull() {
            addCriterion("date_regist is not null");
            return (Criteria) this;
        }

        public Criteria andDateRegistEqualTo(Date value) {
            addCriterionForJDBCDate("date_regist =", value, "dateRegist");
            return (Criteria) this;
        }

        public Criteria andDateRegistNotEqualTo(Date value) {
            addCriterionForJDBCDate("date_regist <>", value, "dateRegist");
            return (Criteria) this;
        }

        public Criteria andDateRegistGreaterThan(Date value) {
            addCriterionForJDBCDate("date_regist >", value, "dateRegist");
            return (Criteria) this;
        }

        public Criteria andDateRegistGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("date_regist >=", value, "dateRegist");
            return (Criteria) this;
        }

        public Criteria andDateRegistLessThan(Date value) {
            addCriterionForJDBCDate("date_regist <", value, "dateRegist");
            return (Criteria) this;
        }

        public Criteria andDateRegistLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("date_regist <=", value, "dateRegist");
            return (Criteria) this;
        }

        public Criteria andDateRegistIn(List<Date> values) {
            addCriterionForJDBCDate("date_regist in", values, "dateRegist");
            return (Criteria) this;
        }

        public Criteria andDateRegistNotIn(List<Date> values) {
            addCriterionForJDBCDate("date_regist not in", values, "dateRegist");
            return (Criteria) this;
        }

        public Criteria andDateRegistBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("date_regist between", value1, value2, "dateRegist");
            return (Criteria) this;
        }

        public Criteria andDateRegistNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("date_regist not between", value1, value2, "dateRegist");
            return (Criteria) this;
        }

        public Criteria andDateEffNoticeIsNull() {
            addCriterion("date_eff_notice is null");
            return (Criteria) this;
        }

        public Criteria andDateEffNoticeIsNotNull() {
            addCriterion("date_eff_notice is not null");
            return (Criteria) this;
        }

        public Criteria andDateEffNoticeEqualTo(Date value) {
            addCriterionForJDBCDate("date_eff_notice =", value, "dateEffNotice");
            return (Criteria) this;
        }

        public Criteria andDateEffNoticeNotEqualTo(Date value) {
            addCriterionForJDBCDate("date_eff_notice <>", value, "dateEffNotice");
            return (Criteria) this;
        }

        public Criteria andDateEffNoticeGreaterThan(Date value) {
            addCriterionForJDBCDate("date_eff_notice >", value, "dateEffNotice");
            return (Criteria) this;
        }

        public Criteria andDateEffNoticeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("date_eff_notice >=", value, "dateEffNotice");
            return (Criteria) this;
        }

        public Criteria andDateEffNoticeLessThan(Date value) {
            addCriterionForJDBCDate("date_eff_notice <", value, "dateEffNotice");
            return (Criteria) this;
        }

        public Criteria andDateEffNoticeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("date_eff_notice <=", value, "dateEffNotice");
            return (Criteria) this;
        }

        public Criteria andDateEffNoticeIn(List<Date> values) {
            addCriterionForJDBCDate("date_eff_notice in", values, "dateEffNotice");
            return (Criteria) this;
        }

        public Criteria andDateEffNoticeNotIn(List<Date> values) {
            addCriterionForJDBCDate("date_eff_notice not in", values, "dateEffNotice");
            return (Criteria) this;
        }

        public Criteria andDateEffNoticeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("date_eff_notice between", value1, value2, "dateEffNotice");
            return (Criteria) this;
        }

        public Criteria andDateEffNoticeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("date_eff_notice not between", value1, value2, "dateEffNotice");
            return (Criteria) this;
        }

        public Criteria andDtReportIsNull() {
            addCriterion("dt_report is null");
            return (Criteria) this;
        }

        public Criteria andDtReportIsNotNull() {
            addCriterion("dt_report is not null");
            return (Criteria) this;
        }

        public Criteria andDtReportEqualTo(Date value) {
            addCriterionForJDBCDate("dt_report =", value, "dtReport");
            return (Criteria) this;
        }

        public Criteria andDtReportNotEqualTo(Date value) {
            addCriterionForJDBCDate("dt_report <>", value, "dtReport");
            return (Criteria) this;
        }

        public Criteria andDtReportGreaterThan(Date value) {
            addCriterionForJDBCDate("dt_report >", value, "dtReport");
            return (Criteria) this;
        }

        public Criteria andDtReportGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("dt_report >=", value, "dtReport");
            return (Criteria) this;
        }

        public Criteria andDtReportLessThan(Date value) {
            addCriterionForJDBCDate("dt_report <", value, "dtReport");
            return (Criteria) this;
        }

        public Criteria andDtReportLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("dt_report <=", value, "dtReport");
            return (Criteria) this;
        }

        public Criteria andDtReportIn(List<Date> values) {
            addCriterionForJDBCDate("dt_report in", values, "dtReport");
            return (Criteria) this;
        }

        public Criteria andDtReportNotIn(List<Date> values) {
            addCriterionForJDBCDate("dt_report not in", values, "dtReport");
            return (Criteria) this;
        }

        public Criteria andDtReportBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("dt_report between", value1, value2, "dtReport");
            return (Criteria) this;
        }

        public Criteria andDtReportNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("dt_report not between", value1, value2, "dtReport");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIsNull() {
            addCriterion("updated_at is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIsNotNull() {
            addCriterion("updated_at is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtEqualTo(Date value) {
            addCriterion("updated_at =", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotEqualTo(Date value) {
            addCriterion("updated_at <>", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtGreaterThan(Date value) {
            addCriterion("updated_at >", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtGreaterThanOrEqualTo(Date value) {
            addCriterion("updated_at >=", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtLessThan(Date value) {
            addCriterion("updated_at <", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtLessThanOrEqualTo(Date value) {
            addCriterion("updated_at <=", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIn(List<Date> values) {
            addCriterion("updated_at in", values, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotIn(List<Date> values) {
            addCriterion("updated_at not in", values, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtBetween(Date value1, Date value2) {
            addCriterion("updated_at between", value1, value2, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotBetween(Date value1, Date value2) {
            addCriterion("updated_at not between", value1, value2, "updatedAt");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tdx_events_issue_effect
     *
     * @mbggenerated do_not_delete_during_merge Tue Mar 20 17:52:12 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tdx_events_issue_effect
     *
     * @mbggenerated Tue Mar 20 17:52:12 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}