package com.kf.data.mybatis.mapper.tdx;

import com.kf.data.mybatis.entity.tdx.TdxCompanyAdmPenalty;
import com.kf.data.mybatis.entity.tdx.TdxCompanyAdmPenaltyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TdxCompanyAdmPenaltyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_adm_penalty
     *
     * @mbggenerated Fri Mar 16 17:23:15 CST 2018
     */
    int countByExample(TdxCompanyAdmPenaltyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_adm_penalty
     *
     * @mbggenerated Fri Mar 16 17:23:15 CST 2018
     */
    int deleteByExample(TdxCompanyAdmPenaltyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_adm_penalty
     *
     * @mbggenerated Fri Mar 16 17:23:15 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_adm_penalty
     *
     * @mbggenerated Fri Mar 16 17:23:15 CST 2018
     */
    int insert(TdxCompanyAdmPenalty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_adm_penalty
     *
     * @mbggenerated Fri Mar 16 17:23:15 CST 2018
     */
    int insertSelective(TdxCompanyAdmPenalty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_adm_penalty
     *
     * @mbggenerated Fri Mar 16 17:23:15 CST 2018
     */
    List<TdxCompanyAdmPenalty> selectByExample(TdxCompanyAdmPenaltyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_adm_penalty
     *
     * @mbggenerated Fri Mar 16 17:23:15 CST 2018
     */
    TdxCompanyAdmPenalty selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_adm_penalty
     *
     * @mbggenerated Fri Mar 16 17:23:15 CST 2018
     */
    int updateByExampleSelective(@Param("record") TdxCompanyAdmPenalty record, @Param("example") TdxCompanyAdmPenaltyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_adm_penalty
     *
     * @mbggenerated Fri Mar 16 17:23:15 CST 2018
     */
    int updateByExample(@Param("record") TdxCompanyAdmPenalty record, @Param("example") TdxCompanyAdmPenaltyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_adm_penalty
     *
     * @mbggenerated Fri Mar 16 17:23:15 CST 2018
     */
    int updateByPrimaryKeySelective(TdxCompanyAdmPenalty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_adm_penalty
     *
     * @mbggenerated Fri Mar 16 17:23:15 CST 2018
     */
    int updateByPrimaryKey(TdxCompanyAdmPenalty record);
}