package com.kf.data.mybatis.mapper.tdx;

import com.kf.data.mybatis.entity.tdx.TdxCompanyIndustry;
import com.kf.data.mybatis.entity.tdx.TdxCompanyIndustryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TdxCompanyIndustryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_industry
     *
     * @mbggenerated Tue Mar 20 17:41:17 CST 2018
     */
    int countByExample(TdxCompanyIndustryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_industry
     *
     * @mbggenerated Tue Mar 20 17:41:17 CST 2018
     */
    int deleteByExample(TdxCompanyIndustryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_industry
     *
     * @mbggenerated Tue Mar 20 17:41:17 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_industry
     *
     * @mbggenerated Tue Mar 20 17:41:17 CST 2018
     */
    int insert(TdxCompanyIndustry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_industry
     *
     * @mbggenerated Tue Mar 20 17:41:17 CST 2018
     */
    int insertSelective(TdxCompanyIndustry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_industry
     *
     * @mbggenerated Tue Mar 20 17:41:17 CST 2018
     */
    List<TdxCompanyIndustry> selectByExample(TdxCompanyIndustryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_industry
     *
     * @mbggenerated Tue Mar 20 17:41:17 CST 2018
     */
    TdxCompanyIndustry selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_industry
     *
     * @mbggenerated Tue Mar 20 17:41:17 CST 2018
     */
    int updateByExampleSelective(@Param("record") TdxCompanyIndustry record, @Param("example") TdxCompanyIndustryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_industry
     *
     * @mbggenerated Tue Mar 20 17:41:17 CST 2018
     */
    int updateByExample(@Param("record") TdxCompanyIndustry record, @Param("example") TdxCompanyIndustryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_industry
     *
     * @mbggenerated Tue Mar 20 17:41:17 CST 2018
     */
    int updateByPrimaryKeySelective(TdxCompanyIndustry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_industry
     *
     * @mbggenerated Tue Mar 20 17:41:17 CST 2018
     */
    int updateByPrimaryKey(TdxCompanyIndustry record);
}