package com.kf.data.mybatis.mapper.tdx;

import com.kf.data.mybatis.entity.tdx.TdxCompanyResearchStat;
import com.kf.data.mybatis.entity.tdx.TdxCompanyResearchStatExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TdxCompanyResearchStatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_research_stat
     *
     * @mbggenerated Wed Mar 21 15:15:12 CST 2018
     */
    int countByExample(TdxCompanyResearchStatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_research_stat
     *
     * @mbggenerated Wed Mar 21 15:15:12 CST 2018
     */
    int deleteByExample(TdxCompanyResearchStatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_research_stat
     *
     * @mbggenerated Wed Mar 21 15:15:12 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_research_stat
     *
     * @mbggenerated Wed Mar 21 15:15:12 CST 2018
     */
    int insert(TdxCompanyResearchStat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_research_stat
     *
     * @mbggenerated Wed Mar 21 15:15:12 CST 2018
     */
    int insertSelective(TdxCompanyResearchStat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_research_stat
     *
     * @mbggenerated Wed Mar 21 15:15:12 CST 2018
     */
    List<TdxCompanyResearchStat> selectByExample(TdxCompanyResearchStatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_research_stat
     *
     * @mbggenerated Wed Mar 21 15:15:12 CST 2018
     */
    TdxCompanyResearchStat selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_research_stat
     *
     * @mbggenerated Wed Mar 21 15:15:12 CST 2018
     */
    int updateByExampleSelective(@Param("record") TdxCompanyResearchStat record, @Param("example") TdxCompanyResearchStatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_research_stat
     *
     * @mbggenerated Wed Mar 21 15:15:12 CST 2018
     */
    int updateByExample(@Param("record") TdxCompanyResearchStat record, @Param("example") TdxCompanyResearchStatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_research_stat
     *
     * @mbggenerated Wed Mar 21 15:15:12 CST 2018
     */
    int updateByPrimaryKeySelective(TdxCompanyResearchStat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_research_stat
     *
     * @mbggenerated Wed Mar 21 15:15:12 CST 2018
     */
    int updateByPrimaryKey(TdxCompanyResearchStat record);
}