package com.kf.data.mybatis.mapper.tdx;

import com.kf.data.mybatis.entity.tdx.TdxCompanyMajorClient;
import com.kf.data.mybatis.entity.tdx.TdxCompanyMajorClientExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TdxCompanyMajorClientMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tdx_company_major_client
	 * @mbggenerated  Thu Mar 15 18:27:20 CST 2018
	 */
	int countByExample(TdxCompanyMajorClientExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tdx_company_major_client
	 * @mbggenerated  Thu Mar 15 18:27:20 CST 2018
	 */
	int deleteByExample(TdxCompanyMajorClientExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tdx_company_major_client
	 * @mbggenerated  Thu Mar 15 18:27:20 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tdx_company_major_client
	 * @mbggenerated  Thu Mar 15 18:27:20 CST 2018
	 */
	int insert(TdxCompanyMajorClient record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tdx_company_major_client
	 * @mbggenerated  Thu Mar 15 18:27:20 CST 2018
	 */
	int insertSelective(TdxCompanyMajorClient record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tdx_company_major_client
	 * @mbggenerated  Thu Mar 15 18:27:20 CST 2018
	 */
	List<TdxCompanyMajorClient> selectByExample(TdxCompanyMajorClientExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tdx_company_major_client
	 * @mbggenerated  Thu Mar 15 18:27:20 CST 2018
	 */
	TdxCompanyMajorClient selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tdx_company_major_client
	 * @mbggenerated  Thu Mar 15 18:27:20 CST 2018
	 */
	int updateByExampleSelective(@Param("record") TdxCompanyMajorClient record,
			@Param("example") TdxCompanyMajorClientExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tdx_company_major_client
	 * @mbggenerated  Thu Mar 15 18:27:20 CST 2018
	 */
	int updateByExample(@Param("record") TdxCompanyMajorClient record,
			@Param("example") TdxCompanyMajorClientExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tdx_company_major_client
	 * @mbggenerated  Thu Mar 15 18:27:20 CST 2018
	 */
	int updateByPrimaryKeySelective(TdxCompanyMajorClient record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tdx_company_major_client
	 * @mbggenerated  Thu Mar 15 18:27:20 CST 2018
	 */
	int updateByPrimaryKey(TdxCompanyMajorClient record);
}