package com.kf.data.mybatis.mapper.tdx;

import com.kf.data.mybatis.entity.tdx.TdxCompanyTaxRating;
import com.kf.data.mybatis.entity.tdx.TdxCompanyTaxRatingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TdxCompanyTaxRatingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_tax_rating
     *
     * @mbggenerated Thu Mar 22 14:58:44 CST 2018
     */
    int countByExample(TdxCompanyTaxRatingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_tax_rating
     *
     * @mbggenerated Thu Mar 22 14:58:44 CST 2018
     */
    int deleteByExample(TdxCompanyTaxRatingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_tax_rating
     *
     * @mbggenerated Thu Mar 22 14:58:44 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_tax_rating
     *
     * @mbggenerated Thu Mar 22 14:58:44 CST 2018
     */
    int insert(TdxCompanyTaxRating record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_tax_rating
     *
     * @mbggenerated Thu Mar 22 14:58:44 CST 2018
     */
    int insertSelective(TdxCompanyTaxRating record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_tax_rating
     *
     * @mbggenerated Thu Mar 22 14:58:44 CST 2018
     */
    List<TdxCompanyTaxRating> selectByExample(TdxCompanyTaxRatingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_tax_rating
     *
     * @mbggenerated Thu Mar 22 14:58:44 CST 2018
     */
    TdxCompanyTaxRating selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_tax_rating
     *
     * @mbggenerated Thu Mar 22 14:58:44 CST 2018
     */
    int updateByExampleSelective(@Param("record") TdxCompanyTaxRating record, @Param("example") TdxCompanyTaxRatingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_tax_rating
     *
     * @mbggenerated Thu Mar 22 14:58:44 CST 2018
     */
    int updateByExample(@Param("record") TdxCompanyTaxRating record, @Param("example") TdxCompanyTaxRatingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_tax_rating
     *
     * @mbggenerated Thu Mar 22 14:58:44 CST 2018
     */
    int updateByPrimaryKeySelective(TdxCompanyTaxRating record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_tax_rating
     *
     * @mbggenerated Thu Mar 22 14:58:44 CST 2018
     */
    int updateByPrimaryKey(TdxCompanyTaxRating record);
}