package com.kf.data.mybatis.mapper.tdx;

import com.kf.data.mybatis.entity.tdx.TdxCompanySoftwareCopyright;
import com.kf.data.mybatis.entity.tdx.TdxCompanySoftwareCopyrightExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TdxCompanySoftwareCopyrightMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_software_copyright
     *
     * @mbggenerated Wed Mar 21 16:33:37 CST 2018
     */
    int countByExample(TdxCompanySoftwareCopyrightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_software_copyright
     *
     * @mbggenerated Wed Mar 21 16:33:37 CST 2018
     */
    int deleteByExample(TdxCompanySoftwareCopyrightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_software_copyright
     *
     * @mbggenerated Wed Mar 21 16:33:37 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_software_copyright
     *
     * @mbggenerated Wed Mar 21 16:33:37 CST 2018
     */
    int insert(TdxCompanySoftwareCopyright record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_software_copyright
     *
     * @mbggenerated Wed Mar 21 16:33:37 CST 2018
     */
    int insertSelective(TdxCompanySoftwareCopyright record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_software_copyright
     *
     * @mbggenerated Wed Mar 21 16:33:37 CST 2018
     */
    List<TdxCompanySoftwareCopyright> selectByExample(TdxCompanySoftwareCopyrightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_software_copyright
     *
     * @mbggenerated Wed Mar 21 16:33:37 CST 2018
     */
    TdxCompanySoftwareCopyright selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_software_copyright
     *
     * @mbggenerated Wed Mar 21 16:33:37 CST 2018
     */
    int updateByExampleSelective(@Param("record") TdxCompanySoftwareCopyright record, @Param("example") TdxCompanySoftwareCopyrightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_software_copyright
     *
     * @mbggenerated Wed Mar 21 16:33:37 CST 2018
     */
    int updateByExample(@Param("record") TdxCompanySoftwareCopyright record, @Param("example") TdxCompanySoftwareCopyrightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_software_copyright
     *
     * @mbggenerated Wed Mar 21 16:33:37 CST 2018
     */
    int updateByPrimaryKeySelective(TdxCompanySoftwareCopyright record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_software_copyright
     *
     * @mbggenerated Wed Mar 21 16:33:37 CST 2018
     */
    int updateByPrimaryKey(TdxCompanySoftwareCopyright record);
}