package com.kf.data.mybatis.mapper.tdx;

import com.kf.data.mybatis.entity.tdx.TdxCompanyIndustryRating;
import com.kf.data.mybatis.entity.tdx.TdxCompanyIndustryRatingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TdxCompanyIndustryRatingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_industry_rating
     *
     * @mbggenerated Fri Mar 16 10:32:04 CST 2018
     */
    int countByExample(TdxCompanyIndustryRatingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_industry_rating
     *
     * @mbggenerated Fri Mar 16 10:32:04 CST 2018
     */
    int deleteByExample(TdxCompanyIndustryRatingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_industry_rating
     *
     * @mbggenerated Fri Mar 16 10:32:04 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_industry_rating
     *
     * @mbggenerated Fri Mar 16 10:32:04 CST 2018
     */
    int insert(TdxCompanyIndustryRating record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_industry_rating
     *
     * @mbggenerated Fri Mar 16 10:32:04 CST 2018
     */
    int insertSelective(TdxCompanyIndustryRating record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_industry_rating
     *
     * @mbggenerated Fri Mar 16 10:32:04 CST 2018
     */
    List<TdxCompanyIndustryRating> selectByExampleWithBLOBs(TdxCompanyIndustryRatingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_industry_rating
     *
     * @mbggenerated Fri Mar 16 10:32:04 CST 2018
     */
    List<TdxCompanyIndustryRating> selectByExample(TdxCompanyIndustryRatingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_industry_rating
     *
     * @mbggenerated Fri Mar 16 10:32:04 CST 2018
     */
    TdxCompanyIndustryRating selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_industry_rating
     *
     * @mbggenerated Fri Mar 16 10:32:04 CST 2018
     */
    int updateByExampleSelective(@Param("record") TdxCompanyIndustryRating record, @Param("example") TdxCompanyIndustryRatingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_industry_rating
     *
     * @mbggenerated Fri Mar 16 10:32:04 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") TdxCompanyIndustryRating record, @Param("example") TdxCompanyIndustryRatingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_industry_rating
     *
     * @mbggenerated Fri Mar 16 10:32:04 CST 2018
     */
    int updateByExample(@Param("record") TdxCompanyIndustryRating record, @Param("example") TdxCompanyIndustryRatingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_industry_rating
     *
     * @mbggenerated Fri Mar 16 10:32:04 CST 2018
     */
    int updateByPrimaryKeySelective(TdxCompanyIndustryRating record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_industry_rating
     *
     * @mbggenerated Fri Mar 16 10:32:04 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(TdxCompanyIndustryRating record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_industry_rating
     *
     * @mbggenerated Fri Mar 16 10:32:04 CST 2018
     */
    int updateByPrimaryKey(TdxCompanyIndustryRating record);
}