package com.kf.data.mybatis.mapper.tdx;

import com.kf.data.mybatis.entity.tdx.TdxCompanyBranch;
import com.kf.data.mybatis.entity.tdx.TdxCompanyBranchExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TdxCompanyBranchMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_branch
     *
     * @mbggenerated Fri Mar 16 13:43:24 CST 2018
     */
    int countByExample(TdxCompanyBranchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_branch
     *
     * @mbggenerated Fri Mar 16 13:43:24 CST 2018
     */
    int deleteByExample(TdxCompanyBranchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_branch
     *
     * @mbggenerated Fri Mar 16 13:43:24 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_branch
     *
     * @mbggenerated Fri Mar 16 13:43:24 CST 2018
     */
    int insert(TdxCompanyBranch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_branch
     *
     * @mbggenerated Fri Mar 16 13:43:24 CST 2018
     */
    int insertSelective(TdxCompanyBranch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_branch
     *
     * @mbggenerated Fri Mar 16 13:43:24 CST 2018
     */
    List<TdxCompanyBranch> selectByExample(TdxCompanyBranchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_branch
     *
     * @mbggenerated Fri Mar 16 13:43:24 CST 2018
     */
    TdxCompanyBranch selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_branch
     *
     * @mbggenerated Fri Mar 16 13:43:24 CST 2018
     */
    int updateByExampleSelective(@Param("record") TdxCompanyBranch record, @Param("example") TdxCompanyBranchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_branch
     *
     * @mbggenerated Fri Mar 16 13:43:24 CST 2018
     */
    int updateByExample(@Param("record") TdxCompanyBranch record, @Param("example") TdxCompanyBranchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_branch
     *
     * @mbggenerated Fri Mar 16 13:43:24 CST 2018
     */
    int updateByPrimaryKeySelective(TdxCompanyBranch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_branch
     *
     * @mbggenerated Fri Mar 16 13:43:24 CST 2018
     */
    int updateByPrimaryKey(TdxCompanyBranch record);
}