package com.kf.data.mybatis.mapper.tdx;

import com.kf.data.mybatis.entity.tdx.TdxCompanyDiv;
import com.kf.data.mybatis.entity.tdx.TdxCompanyDivExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TdxCompanyDivMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_div
     *
     * @mbggenerated Thu Mar 15 10:44:23 CST 2018
     */
    int countByExample(TdxCompanyDivExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_div
     *
     * @mbggenerated Thu Mar 15 10:44:23 CST 2018
     */
    int deleteByExample(TdxCompanyDivExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_div
     *
     * @mbggenerated Thu Mar 15 10:44:23 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_div
     *
     * @mbggenerated Thu Mar 15 10:44:23 CST 2018
     */
    int insert(TdxCompanyDiv record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_div
     *
     * @mbggenerated Thu Mar 15 10:44:23 CST 2018
     */
    int insertSelective(TdxCompanyDiv record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_div
     *
     * @mbggenerated Thu Mar 15 10:44:23 CST 2018
     */
    List<TdxCompanyDiv> selectByExample(TdxCompanyDivExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_div
     *
     * @mbggenerated Thu Mar 15 10:44:23 CST 2018
     */
    TdxCompanyDiv selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_div
     *
     * @mbggenerated Thu Mar 15 10:44:23 CST 2018
     */
    int updateByExampleSelective(@Param("record") TdxCompanyDiv record, @Param("example") TdxCompanyDivExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_div
     *
     * @mbggenerated Thu Mar 15 10:44:23 CST 2018
     */
    int updateByExample(@Param("record") TdxCompanyDiv record, @Param("example") TdxCompanyDivExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_div
     *
     * @mbggenerated Thu Mar 15 10:44:23 CST 2018
     */
    int updateByPrimaryKeySelective(TdxCompanyDiv record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_div
     *
     * @mbggenerated Thu Mar 15 10:44:23 CST 2018
     */
    int updateByPrimaryKey(TdxCompanyDiv record);
}