package com.kf.data.mybatis.mapper.tdx;

import com.kf.data.mybatis.entity.tdx.TdxCompanyBusinessModel;
import com.kf.data.mybatis.entity.tdx.TdxCompanyBusinessModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TdxCompanyBusinessModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_business_model
     *
     * @mbggenerated Thu Mar 15 18:02:52 CST 2018
     */
    int countByExample(TdxCompanyBusinessModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_business_model
     *
     * @mbggenerated Thu Mar 15 18:02:52 CST 2018
     */
    int deleteByExample(TdxCompanyBusinessModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_business_model
     *
     * @mbggenerated Thu Mar 15 18:02:52 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_business_model
     *
     * @mbggenerated Thu Mar 15 18:02:52 CST 2018
     */
    int insert(TdxCompanyBusinessModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_business_model
     *
     * @mbggenerated Thu Mar 15 18:02:52 CST 2018
     */
    int insertSelective(TdxCompanyBusinessModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_business_model
     *
     * @mbggenerated Thu Mar 15 18:02:52 CST 2018
     */
    List<TdxCompanyBusinessModel> selectByExampleWithBLOBs(TdxCompanyBusinessModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_business_model
     *
     * @mbggenerated Thu Mar 15 18:02:52 CST 2018
     */
    List<TdxCompanyBusinessModel> selectByExample(TdxCompanyBusinessModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_business_model
     *
     * @mbggenerated Thu Mar 15 18:02:52 CST 2018
     */
    TdxCompanyBusinessModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_business_model
     *
     * @mbggenerated Thu Mar 15 18:02:52 CST 2018
     */
    int updateByExampleSelective(@Param("record") TdxCompanyBusinessModel record, @Param("example") TdxCompanyBusinessModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_business_model
     *
     * @mbggenerated Thu Mar 15 18:02:52 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") TdxCompanyBusinessModel record, @Param("example") TdxCompanyBusinessModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_business_model
     *
     * @mbggenerated Thu Mar 15 18:02:52 CST 2018
     */
    int updateByExample(@Param("record") TdxCompanyBusinessModel record, @Param("example") TdxCompanyBusinessModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_business_model
     *
     * @mbggenerated Thu Mar 15 18:02:52 CST 2018
     */
    int updateByPrimaryKeySelective(TdxCompanyBusinessModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_business_model
     *
     * @mbggenerated Thu Mar 15 18:02:52 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(TdxCompanyBusinessModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_company_business_model
     *
     * @mbggenerated Thu Mar 15 18:02:52 CST 2018
     */
    int updateByPrimaryKey(TdxCompanyBusinessModel record);
}