package com.kf.data.mybatis.mapper.tdx;

import com.kf.data.mybatis.entity.tdx.TdxCompanyAbnormalOperation;
import com.kf.data.mybatis.entity.tdx.TdxCompanyAbnormalOperationExample;
import com.kf.data.mybatis.entity.tdx.TdxCompanyAbnormalOperationWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TdxCompanyAbnormalOperationMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tdx_company_abnormal_operation
	 * @mbggenerated  Fri Mar 16 17:07:25 CST 2018
	 */
	int countByExample(TdxCompanyAbnormalOperationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tdx_company_abnormal_operation
	 * @mbggenerated  Fri Mar 16 17:07:25 CST 2018
	 */
	int deleteByExample(TdxCompanyAbnormalOperationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tdx_company_abnormal_operation
	 * @mbggenerated  Fri Mar 16 17:07:25 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tdx_company_abnormal_operation
	 * @mbggenerated  Fri Mar 16 17:07:25 CST 2018
	 */
	int insert(TdxCompanyAbnormalOperationWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tdx_company_abnormal_operation
	 * @mbggenerated  Fri Mar 16 17:07:25 CST 2018
	 */
	int insertSelective(TdxCompanyAbnormalOperationWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tdx_company_abnormal_operation
	 * @mbggenerated  Fri Mar 16 17:07:25 CST 2018
	 */
	List<TdxCompanyAbnormalOperationWithBLOBs> selectByExampleWithBLOBs(TdxCompanyAbnormalOperationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tdx_company_abnormal_operation
	 * @mbggenerated  Fri Mar 16 17:07:25 CST 2018
	 */
	List<TdxCompanyAbnormalOperation> selectByExample(TdxCompanyAbnormalOperationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tdx_company_abnormal_operation
	 * @mbggenerated  Fri Mar 16 17:07:25 CST 2018
	 */
	TdxCompanyAbnormalOperationWithBLOBs selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tdx_company_abnormal_operation
	 * @mbggenerated  Fri Mar 16 17:07:25 CST 2018
	 */
	int updateByExampleSelective(@Param("record") TdxCompanyAbnormalOperationWithBLOBs record,
			@Param("example") TdxCompanyAbnormalOperationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tdx_company_abnormal_operation
	 * @mbggenerated  Fri Mar 16 17:07:25 CST 2018
	 */
	int updateByExampleWithBLOBs(@Param("record") TdxCompanyAbnormalOperationWithBLOBs record,
			@Param("example") TdxCompanyAbnormalOperationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tdx_company_abnormal_operation
	 * @mbggenerated  Fri Mar 16 17:07:25 CST 2018
	 */
	int updateByExample(@Param("record") TdxCompanyAbnormalOperation record,
			@Param("example") TdxCompanyAbnormalOperationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tdx_company_abnormal_operation
	 * @mbggenerated  Fri Mar 16 17:07:25 CST 2018
	 */
	int updateByPrimaryKeySelective(TdxCompanyAbnormalOperationWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tdx_company_abnormal_operation
	 * @mbggenerated  Fri Mar 16 17:07:25 CST 2018
	 */
	int updateByPrimaryKeyWithBLOBs(TdxCompanyAbnormalOperationWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tdx_company_abnormal_operation
	 * @mbggenerated  Fri Mar 16 17:07:25 CST 2018
	 */
	int updateByPrimaryKey(TdxCompanyAbnormalOperation record);
}