package com.kf.data.mybatis.mapper.tdx;

import com.kf.data.mybatis.entity.tdx.TdxCompanyAccountingFirm;
import com.kf.data.mybatis.entity.tdx.TdxCompanyAccountingFirmExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TdxCompanyAccountingFirmMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tdx_company_accounting_firm
	 * @mbggenerated  Thu Mar 22 17:39:21 CST 2018
	 */
	int countByExample(TdxCompanyAccountingFirmExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tdx_company_accounting_firm
	 * @mbggenerated  Thu Mar 22 17:39:21 CST 2018
	 */
	int deleteByExample(TdxCompanyAccountingFirmExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tdx_company_accounting_firm
	 * @mbggenerated  Thu Mar 22 17:39:21 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tdx_company_accounting_firm
	 * @mbggenerated  Thu Mar 22 17:39:21 CST 2018
	 */
	int insert(TdxCompanyAccountingFirm record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tdx_company_accounting_firm
	 * @mbggenerated  Thu Mar 22 17:39:21 CST 2018
	 */
	int insertSelective(TdxCompanyAccountingFirm record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tdx_company_accounting_firm
	 * @mbggenerated  Thu Mar 22 17:39:21 CST 2018
	 */
	List<TdxCompanyAccountingFirm> selectByExample(TdxCompanyAccountingFirmExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tdx_company_accounting_firm
	 * @mbggenerated  Thu Mar 22 17:39:21 CST 2018
	 */
	TdxCompanyAccountingFirm selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tdx_company_accounting_firm
	 * @mbggenerated  Thu Mar 22 17:39:21 CST 2018
	 */
	int updateByExampleSelective(@Param("record") TdxCompanyAccountingFirm record,
			@Param("example") TdxCompanyAccountingFirmExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tdx_company_accounting_firm
	 * @mbggenerated  Thu Mar 22 17:39:21 CST 2018
	 */
	int updateByExample(@Param("record") TdxCompanyAccountingFirm record,
			@Param("example") TdxCompanyAccountingFirmExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tdx_company_accounting_firm
	 * @mbggenerated  Thu Mar 22 17:39:21 CST 2018
	 */
	int updateByPrimaryKeySelective(TdxCompanyAccountingFirm record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tdx_company_accounting_firm
	 * @mbggenerated  Thu Mar 22 17:39:21 CST 2018
	 */
	int updateByPrimaryKey(TdxCompanyAccountingFirm record);
}