package com.kf.data.mybatis.mapper.tdx;

import com.kf.data.mybatis.entity.tdx.TdxEventsInvest;
import com.kf.data.mybatis.entity.tdx.TdxEventsInvestExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TdxEventsInvestMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tdx_events_invest
	 * @mbggenerated  Wed Mar 21 11:26:11 CST 2018
	 */
	int countByExample(TdxEventsInvestExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tdx_events_invest
	 * @mbggenerated  Wed Mar 21 11:26:11 CST 2018
	 */
	int deleteByExample(TdxEventsInvestExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tdx_events_invest
	 * @mbggenerated  Wed Mar 21 11:26:11 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tdx_events_invest
	 * @mbggenerated  Wed Mar 21 11:26:11 CST 2018
	 */
	int insert(TdxEventsInvest record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tdx_events_invest
	 * @mbggenerated  Wed Mar 21 11:26:11 CST 2018
	 */
	int insertSelective(TdxEventsInvest record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tdx_events_invest
	 * @mbggenerated  Wed Mar 21 11:26:11 CST 2018
	 */
	List<TdxEventsInvest> selectByExampleWithBLOBs(TdxEventsInvestExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tdx_events_invest
	 * @mbggenerated  Wed Mar 21 11:26:11 CST 2018
	 */
	List<TdxEventsInvest> selectByExample(TdxEventsInvestExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tdx_events_invest
	 * @mbggenerated  Wed Mar 21 11:26:11 CST 2018
	 */
	TdxEventsInvest selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tdx_events_invest
	 * @mbggenerated  Wed Mar 21 11:26:11 CST 2018
	 */
	int updateByExampleSelective(@Param("record") TdxEventsInvest record,
			@Param("example") TdxEventsInvestExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tdx_events_invest
	 * @mbggenerated  Wed Mar 21 11:26:11 CST 2018
	 */
	int updateByExampleWithBLOBs(@Param("record") TdxEventsInvest record,
			@Param("example") TdxEventsInvestExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tdx_events_invest
	 * @mbggenerated  Wed Mar 21 11:26:11 CST 2018
	 */
	int updateByExample(@Param("record") TdxEventsInvest record, @Param("example") TdxEventsInvestExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tdx_events_invest
	 * @mbggenerated  Wed Mar 21 11:26:11 CST 2018
	 */
	int updateByPrimaryKeySelective(TdxEventsInvest record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tdx_events_invest
	 * @mbggenerated  Wed Mar 21 11:26:11 CST 2018
	 */
	int updateByPrimaryKeyWithBLOBs(TdxEventsInvest record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tdx_events_invest
	 * @mbggenerated  Wed Mar 21 11:26:11 CST 2018
	 */
	int updateByPrimaryKey(TdxEventsInvest record);
}