package com.kf.data.mybatis.mapper.tdx;

import com.kf.data.mybatis.entity.tdx.TdxEventsIssueEffect;
import com.kf.data.mybatis.entity.tdx.TdxEventsIssueEffectExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TdxEventsIssueEffectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_events_issue_effect
     *
     * @mbggenerated Tue Mar 20 17:52:12 CST 2018
     */
    int countByExample(TdxEventsIssueEffectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_events_issue_effect
     *
     * @mbggenerated Tue Mar 20 17:52:12 CST 2018
     */
    int deleteByExample(TdxEventsIssueEffectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_events_issue_effect
     *
     * @mbggenerated Tue Mar 20 17:52:12 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_events_issue_effect
     *
     * @mbggenerated Tue Mar 20 17:52:12 CST 2018
     */
    int insert(TdxEventsIssueEffect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_events_issue_effect
     *
     * @mbggenerated Tue Mar 20 17:52:12 CST 2018
     */
    int insertSelective(TdxEventsIssueEffect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_events_issue_effect
     *
     * @mbggenerated Tue Mar 20 17:52:12 CST 2018
     */
    List<TdxEventsIssueEffect> selectByExample(TdxEventsIssueEffectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_events_issue_effect
     *
     * @mbggenerated Tue Mar 20 17:52:12 CST 2018
     */
    TdxEventsIssueEffect selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_events_issue_effect
     *
     * @mbggenerated Tue Mar 20 17:52:12 CST 2018
     */
    int updateByExampleSelective(@Param("record") TdxEventsIssueEffect record, @Param("example") TdxEventsIssueEffectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_events_issue_effect
     *
     * @mbggenerated Tue Mar 20 17:52:12 CST 2018
     */
    int updateByExample(@Param("record") TdxEventsIssueEffect record, @Param("example") TdxEventsIssueEffectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_events_issue_effect
     *
     * @mbggenerated Tue Mar 20 17:52:12 CST 2018
     */
    int updateByPrimaryKeySelective(TdxEventsIssueEffect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_events_issue_effect
     *
     * @mbggenerated Tue Mar 20 17:52:12 CST 2018
     */
    int updateByPrimaryKey(TdxEventsIssueEffect record);
}