package com.kf.data.mybatis.mapper.tdx;

import com.kf.data.mybatis.entity.tdx.TdxFinanceIndicator2016;
import com.kf.data.mybatis.entity.tdx.TdxFinanceIndicator2016Example;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TdxFinanceIndicator2016Mapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tdx_finance_indicator_2016
	 * @mbggenerated  Fri Mar 23 17:19:53 CST 2018
	 */
	int countByExample(TdxFinanceIndicator2016Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tdx_finance_indicator_2016
	 * @mbggenerated  Fri Mar 23 17:19:53 CST 2018
	 */
	int deleteByExample(TdxFinanceIndicator2016Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tdx_finance_indicator_2016
	 * @mbggenerated  Fri Mar 23 17:19:53 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tdx_finance_indicator_2016
	 * @mbggenerated  Fri Mar 23 17:19:53 CST 2018
	 */
	int insert(TdxFinanceIndicator2016 record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tdx_finance_indicator_2016
	 * @mbggenerated  Fri Mar 23 17:19:53 CST 2018
	 */
	int insertSelective(TdxFinanceIndicator2016 record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tdx_finance_indicator_2016
	 * @mbggenerated  Fri Mar 23 17:19:53 CST 2018
	 */
	List<TdxFinanceIndicator2016> selectByExample(TdxFinanceIndicator2016Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tdx_finance_indicator_2016
	 * @mbggenerated  Fri Mar 23 17:19:53 CST 2018
	 */
	TdxFinanceIndicator2016 selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tdx_finance_indicator_2016
	 * @mbggenerated  Fri Mar 23 17:19:53 CST 2018
	 */
	int updateByExampleSelective(@Param("record") TdxFinanceIndicator2016 record,
			@Param("example") TdxFinanceIndicator2016Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tdx_finance_indicator_2016
	 * @mbggenerated  Fri Mar 23 17:19:53 CST 2018
	 */
	int updateByExample(@Param("record") TdxFinanceIndicator2016 record,
			@Param("example") TdxFinanceIndicator2016Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tdx_finance_indicator_2016
	 * @mbggenerated  Fri Mar 23 17:19:53 CST 2018
	 */
	int updateByPrimaryKeySelective(TdxFinanceIndicator2016 record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tdx_finance_indicator_2016
	 * @mbggenerated  Fri Mar 23 17:19:53 CST 2018
	 */
	int updateByPrimaryKey(TdxFinanceIndicator2016 record);
}