package com.kf.data.mybatis.mapper.tdx;

import com.kf.data.mybatis.entity.tdx.TdxFinanceIndicator2014;
import com.kf.data.mybatis.entity.tdx.TdxFinanceIndicator2014Example;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TdxFinanceIndicator2014Mapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tdx_finance_indicator_2014
	 * @mbggenerated  Fri Mar 23 17:38:14 CST 2018
	 */
	int countByExample(TdxFinanceIndicator2014Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tdx_finance_indicator_2014
	 * @mbggenerated  Fri Mar 23 17:38:14 CST 2018
	 */
	int deleteByExample(TdxFinanceIndicator2014Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tdx_finance_indicator_2014
	 * @mbggenerated  Fri Mar 23 17:38:14 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tdx_finance_indicator_2014
	 * @mbggenerated  Fri Mar 23 17:38:14 CST 2018
	 */
	int insert(TdxFinanceIndicator2014 record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tdx_finance_indicator_2014
	 * @mbggenerated  Fri Mar 23 17:38:14 CST 2018
	 */
	int insertSelective(TdxFinanceIndicator2014 record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tdx_finance_indicator_2014
	 * @mbggenerated  Fri Mar 23 17:38:14 CST 2018
	 */
	List<TdxFinanceIndicator2014> selectByExample(TdxFinanceIndicator2014Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tdx_finance_indicator_2014
	 * @mbggenerated  Fri Mar 23 17:38:14 CST 2018
	 */
	TdxFinanceIndicator2014 selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tdx_finance_indicator_2014
	 * @mbggenerated  Fri Mar 23 17:38:14 CST 2018
	 */
	int updateByExampleSelective(@Param("record") TdxFinanceIndicator2014 record,
			@Param("example") TdxFinanceIndicator2014Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tdx_finance_indicator_2014
	 * @mbggenerated  Fri Mar 23 17:38:14 CST 2018
	 */
	int updateByExample(@Param("record") TdxFinanceIndicator2014 record,
			@Param("example") TdxFinanceIndicator2014Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tdx_finance_indicator_2014
	 * @mbggenerated  Fri Mar 23 17:38:14 CST 2018
	 */
	int updateByPrimaryKeySelective(TdxFinanceIndicator2014 record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tdx_finance_indicator_2014
	 * @mbggenerated  Fri Mar 23 17:38:14 CST 2018
	 */
	int updateByPrimaryKey(TdxFinanceIndicator2014 record);
}