package com.kf.data.mybatis.mapper.tdx;

import com.kf.data.mybatis.entity.tdx.TdxFinanceIndicator2017;
import com.kf.data.mybatis.entity.tdx.TdxFinanceIndicator2017Example;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TdxFinanceIndicator2017Mapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tdx_finance_indicator_2017
	 * @mbggenerated  Fri Mar 23 17:19:44 CST 2018
	 */
	int countByExample(TdxFinanceIndicator2017Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tdx_finance_indicator_2017
	 * @mbggenerated  Fri Mar 23 17:19:44 CST 2018
	 */
	int deleteByExample(TdxFinanceIndicator2017Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tdx_finance_indicator_2017
	 * @mbggenerated  Fri Mar 23 17:19:44 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tdx_finance_indicator_2017
	 * @mbggenerated  Fri Mar 23 17:19:44 CST 2018
	 */
	int insert(TdxFinanceIndicator2017 record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tdx_finance_indicator_2017
	 * @mbggenerated  Fri Mar 23 17:19:44 CST 2018
	 */
	int insertSelective(TdxFinanceIndicator2017 record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tdx_finance_indicator_2017
	 * @mbggenerated  Fri Mar 23 17:19:44 CST 2018
	 */
	List<TdxFinanceIndicator2017> selectByExample(TdxFinanceIndicator2017Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tdx_finance_indicator_2017
	 * @mbggenerated  Fri Mar 23 17:19:44 CST 2018
	 */
	TdxFinanceIndicator2017 selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tdx_finance_indicator_2017
	 * @mbggenerated  Fri Mar 23 17:19:44 CST 2018
	 */
	int updateByExampleSelective(@Param("record") TdxFinanceIndicator2017 record,
			@Param("example") TdxFinanceIndicator2017Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tdx_finance_indicator_2017
	 * @mbggenerated  Fri Mar 23 17:19:44 CST 2018
	 */
	int updateByExample(@Param("record") TdxFinanceIndicator2017 record,
			@Param("example") TdxFinanceIndicator2017Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tdx_finance_indicator_2017
	 * @mbggenerated  Fri Mar 23 17:19:44 CST 2018
	 */
	int updateByPrimaryKeySelective(TdxFinanceIndicator2017 record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tdx_finance_indicator_2017
	 * @mbggenerated  Fri Mar 23 17:19:44 CST 2018
	 */
	int updateByPrimaryKey(TdxFinanceIndicator2017 record);
}