package com.kf.data.mybatis.mapper.tdx;

import com.kf.data.mybatis.entity.tdx.TdxHistoryQuotation;
import com.kf.data.mybatis.entity.tdx.TdxHistoryQuotationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TdxHistoryQuotationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_history_quotation
     *
     * @mbggenerated Fri Mar 23 12:00:27 CST 2018
     */
    int countByExample(TdxHistoryQuotationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_history_quotation
     *
     * @mbggenerated Fri Mar 23 12:00:27 CST 2018
     */
    int deleteByExample(TdxHistoryQuotationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_history_quotation
     *
     * @mbggenerated Fri Mar 23 12:00:27 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_history_quotation
     *
     * @mbggenerated Fri Mar 23 12:00:27 CST 2018
     */
    int insert(TdxHistoryQuotation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_history_quotation
     *
     * @mbggenerated Fri Mar 23 12:00:27 CST 2018
     */
    int insertSelective(TdxHistoryQuotation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_history_quotation
     *
     * @mbggenerated Fri Mar 23 12:00:27 CST 2018
     */
    List<TdxHistoryQuotation> selectByExample(TdxHistoryQuotationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_history_quotation
     *
     * @mbggenerated Fri Mar 23 12:00:27 CST 2018
     */
    TdxHistoryQuotation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_history_quotation
     *
     * @mbggenerated Fri Mar 23 12:00:27 CST 2018
     */
    int updateByExampleSelective(@Param("record") TdxHistoryQuotation record, @Param("example") TdxHistoryQuotationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_history_quotation
     *
     * @mbggenerated Fri Mar 23 12:00:27 CST 2018
     */
    int updateByExample(@Param("record") TdxHistoryQuotation record, @Param("example") TdxHistoryQuotationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_history_quotation
     *
     * @mbggenerated Fri Mar 23 12:00:27 CST 2018
     */
    int updateByPrimaryKeySelective(TdxHistoryQuotation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_history_quotation
     *
     * @mbggenerated Fri Mar 23 12:00:27 CST 2018
     */
    int updateByPrimaryKey(TdxHistoryQuotation record);
}