package com.kf.data.mybatis.entity.online;

import java.util.Date;

public class NeeqNoticeOnline {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_notice.id
     *
     * @mbggenerated Fri Mar 23 14:41:57 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_notice.companyid
     *
     * @mbggenerated Fri Mar 23 14:41:57 CST 2018
     */
    private String companyid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_notice.notice_id
     *
     * @mbggenerated Fri Mar 23 14:41:57 CST 2018
     */
    private String noticeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_notice.code
     *
     * @mbggenerated Fri Mar 23 14:41:57 CST 2018
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_notice.securities_id
     *
     * @mbggenerated Fri Mar 23 14:41:57 CST 2018
     */
    private String securitiesId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_notice.company_name
     *
     * @mbggenerated Fri Mar 23 14:41:57 CST 2018
     */
    private String companyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_notice.disclosure_code
     *
     * @mbggenerated Fri Mar 23 14:41:57 CST 2018
     */
    private String disclosureCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_notice.title
     *
     * @mbggenerated Fri Mar 23 14:41:57 CST 2018
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_notice.publish_date
     *
     * @mbggenerated Fri Mar 23 14:41:57 CST 2018
     */
    private String publishDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_notice.publish_date_machine
     *
     * @mbggenerated Fri Mar 23 14:41:57 CST 2018
     */
    private Integer publishDateMachine;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_notice.file_path
     *
     * @mbggenerated Fri Mar 23 14:41:57 CST 2018
     */
    private String filePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_notice.file_ext
     *
     * @mbggenerated Fri Mar 23 14:41:57 CST 2018
     */
    private String fileExt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_notice.html_path
     *
     * @mbggenerated Fri Mar 23 14:41:57 CST 2018
     */
    private String htmlPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_notice.publish_type
     *
     * @mbggenerated Fri Mar 23 14:41:57 CST 2018
     */
    private String publishType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_notice.notice_type_code
     *
     * @mbggenerated Fri Mar 23 14:41:57 CST 2018
     */
    private String noticeTypeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_notice.notice_type_name
     *
     * @mbggenerated Fri Mar 23 14:41:57 CST 2018
     */
    private String noticeTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_notice.notice_classification_first_level
     *
     * @mbggenerated Fri Mar 23 14:41:57 CST 2018
     */
    private String noticeClassificationFirstLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_notice.notice_classification_second_level
     *
     * @mbggenerated Fri Mar 23 14:41:57 CST 2018
     */
    private String noticeClassificationSecondLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_notice.notice_classification_first_level_name
     *
     * @mbggenerated Fri Mar 23 14:41:57 CST 2018
     */
    private String noticeClassificationFirstLevelName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_notice.notice_classification_second_level_name
     *
     * @mbggenerated Fri Mar 23 14:41:57 CST 2018
     */
    private String noticeClassificationSecondLevelName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_notice.positiveornegative
     *
     * @mbggenerated Fri Mar 23 14:41:57 CST 2018
     */
    private String positiveornegative;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_notice.status
     *
     * @mbggenerated Fri Mar 23 14:41:57 CST 2018
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_notice.created_at
     *
     * @mbggenerated Fri Mar 23 14:41:57 CST 2018
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_notice.updated_at
     *
     * @mbggenerated Fri Mar 23 14:41:57 CST 2018
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_notice.content
     *
     * @mbggenerated Fri Mar 23 14:41:57 CST 2018
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_notice.id
     *
     * @return the value of neeq_notice.id
     *
     * @mbggenerated Fri Mar 23 14:41:57 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_notice.id
     *
     * @param id the value for neeq_notice.id
     *
     * @mbggenerated Fri Mar 23 14:41:57 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_notice.companyid
     *
     * @return the value of neeq_notice.companyid
     *
     * @mbggenerated Fri Mar 23 14:41:57 CST 2018
     */
    public String getCompanyid() {
        return companyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_notice.companyid
     *
     * @param companyid the value for neeq_notice.companyid
     *
     * @mbggenerated Fri Mar 23 14:41:57 CST 2018
     */
    public void setCompanyid(String companyid) {
        this.companyid = companyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_notice.notice_id
     *
     * @return the value of neeq_notice.notice_id
     *
     * @mbggenerated Fri Mar 23 14:41:57 CST 2018
     */
    public String getNoticeId() {
        return noticeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_notice.notice_id
     *
     * @param noticeId the value for neeq_notice.notice_id
     *
     * @mbggenerated Fri Mar 23 14:41:57 CST 2018
     */
    public void setNoticeId(String noticeId) {
        this.noticeId = noticeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_notice.code
     *
     * @return the value of neeq_notice.code
     *
     * @mbggenerated Fri Mar 23 14:41:57 CST 2018
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_notice.code
     *
     * @param code the value for neeq_notice.code
     *
     * @mbggenerated Fri Mar 23 14:41:57 CST 2018
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_notice.securities_id
     *
     * @return the value of neeq_notice.securities_id
     *
     * @mbggenerated Fri Mar 23 14:41:57 CST 2018
     */
    public String getSecuritiesId() {
        return securitiesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_notice.securities_id
     *
     * @param securitiesId the value for neeq_notice.securities_id
     *
     * @mbggenerated Fri Mar 23 14:41:57 CST 2018
     */
    public void setSecuritiesId(String securitiesId) {
        this.securitiesId = securitiesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_notice.company_name
     *
     * @return the value of neeq_notice.company_name
     *
     * @mbggenerated Fri Mar 23 14:41:57 CST 2018
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_notice.company_name
     *
     * @param companyName the value for neeq_notice.company_name
     *
     * @mbggenerated Fri Mar 23 14:41:57 CST 2018
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_notice.disclosure_code
     *
     * @return the value of neeq_notice.disclosure_code
     *
     * @mbggenerated Fri Mar 23 14:41:57 CST 2018
     */
    public String getDisclosureCode() {
        return disclosureCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_notice.disclosure_code
     *
     * @param disclosureCode the value for neeq_notice.disclosure_code
     *
     * @mbggenerated Fri Mar 23 14:41:57 CST 2018
     */
    public void setDisclosureCode(String disclosureCode) {
        this.disclosureCode = disclosureCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_notice.title
     *
     * @return the value of neeq_notice.title
     *
     * @mbggenerated Fri Mar 23 14:41:57 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_notice.title
     *
     * @param title the value for neeq_notice.title
     *
     * @mbggenerated Fri Mar 23 14:41:57 CST 2018
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_notice.publish_date
     *
     * @return the value of neeq_notice.publish_date
     *
     * @mbggenerated Fri Mar 23 14:41:57 CST 2018
     */
    public String getPublishDate() {
        return publishDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_notice.publish_date
     *
     * @param publishDate the value for neeq_notice.publish_date
     *
     * @mbggenerated Fri Mar 23 14:41:57 CST 2018
     */
    public void setPublishDate(String publishDate) {
        this.publishDate = publishDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_notice.publish_date_machine
     *
     * @return the value of neeq_notice.publish_date_machine
     *
     * @mbggenerated Fri Mar 23 14:41:57 CST 2018
     */
    public Integer getPublishDateMachine() {
        return publishDateMachine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_notice.publish_date_machine
     *
     * @param publishDateMachine the value for neeq_notice.publish_date_machine
     *
     * @mbggenerated Fri Mar 23 14:41:57 CST 2018
     */
    public void setPublishDateMachine(Integer publishDateMachine) {
        this.publishDateMachine = publishDateMachine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_notice.file_path
     *
     * @return the value of neeq_notice.file_path
     *
     * @mbggenerated Fri Mar 23 14:41:57 CST 2018
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_notice.file_path
     *
     * @param filePath the value for neeq_notice.file_path
     *
     * @mbggenerated Fri Mar 23 14:41:57 CST 2018
     */
    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_notice.file_ext
     *
     * @return the value of neeq_notice.file_ext
     *
     * @mbggenerated Fri Mar 23 14:41:57 CST 2018
     */
    public String getFileExt() {
        return fileExt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_notice.file_ext
     *
     * @param fileExt the value for neeq_notice.file_ext
     *
     * @mbggenerated Fri Mar 23 14:41:57 CST 2018
     */
    public void setFileExt(String fileExt) {
        this.fileExt = fileExt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_notice.html_path
     *
     * @return the value of neeq_notice.html_path
     *
     * @mbggenerated Fri Mar 23 14:41:57 CST 2018
     */
    public String getHtmlPath() {
        return htmlPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_notice.html_path
     *
     * @param htmlPath the value for neeq_notice.html_path
     *
     * @mbggenerated Fri Mar 23 14:41:57 CST 2018
     */
    public void setHtmlPath(String htmlPath) {
        this.htmlPath = htmlPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_notice.publish_type
     *
     * @return the value of neeq_notice.publish_type
     *
     * @mbggenerated Fri Mar 23 14:41:57 CST 2018
     */
    public String getPublishType() {
        return publishType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_notice.publish_type
     *
     * @param publishType the value for neeq_notice.publish_type
     *
     * @mbggenerated Fri Mar 23 14:41:57 CST 2018
     */
    public void setPublishType(String publishType) {
        this.publishType = publishType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_notice.notice_type_code
     *
     * @return the value of neeq_notice.notice_type_code
     *
     * @mbggenerated Fri Mar 23 14:41:57 CST 2018
     */
    public String getNoticeTypeCode() {
        return noticeTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_notice.notice_type_code
     *
     * @param noticeTypeCode the value for neeq_notice.notice_type_code
     *
     * @mbggenerated Fri Mar 23 14:41:57 CST 2018
     */
    public void setNoticeTypeCode(String noticeTypeCode) {
        this.noticeTypeCode = noticeTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_notice.notice_type_name
     *
     * @return the value of neeq_notice.notice_type_name
     *
     * @mbggenerated Fri Mar 23 14:41:57 CST 2018
     */
    public String getNoticeTypeName() {
        return noticeTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_notice.notice_type_name
     *
     * @param noticeTypeName the value for neeq_notice.notice_type_name
     *
     * @mbggenerated Fri Mar 23 14:41:57 CST 2018
     */
    public void setNoticeTypeName(String noticeTypeName) {
        this.noticeTypeName = noticeTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_notice.notice_classification_first_level
     *
     * @return the value of neeq_notice.notice_classification_first_level
     *
     * @mbggenerated Fri Mar 23 14:41:57 CST 2018
     */
    public String getNoticeClassificationFirstLevel() {
        return noticeClassificationFirstLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_notice.notice_classification_first_level
     *
     * @param noticeClassificationFirstLevel the value for neeq_notice.notice_classification_first_level
     *
     * @mbggenerated Fri Mar 23 14:41:57 CST 2018
     */
    public void setNoticeClassificationFirstLevel(String noticeClassificationFirstLevel) {
        this.noticeClassificationFirstLevel = noticeClassificationFirstLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_notice.notice_classification_second_level
     *
     * @return the value of neeq_notice.notice_classification_second_level
     *
     * @mbggenerated Fri Mar 23 14:41:57 CST 2018
     */
    public String getNoticeClassificationSecondLevel() {
        return noticeClassificationSecondLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_notice.notice_classification_second_level
     *
     * @param noticeClassificationSecondLevel the value for neeq_notice.notice_classification_second_level
     *
     * @mbggenerated Fri Mar 23 14:41:57 CST 2018
     */
    public void setNoticeClassificationSecondLevel(String noticeClassificationSecondLevel) {
        this.noticeClassificationSecondLevel = noticeClassificationSecondLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_notice.notice_classification_first_level_name
     *
     * @return the value of neeq_notice.notice_classification_first_level_name
     *
     * @mbggenerated Fri Mar 23 14:41:57 CST 2018
     */
    public String getNoticeClassificationFirstLevelName() {
        return noticeClassificationFirstLevelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_notice.notice_classification_first_level_name
     *
     * @param noticeClassificationFirstLevelName the value for neeq_notice.notice_classification_first_level_name
     *
     * @mbggenerated Fri Mar 23 14:41:57 CST 2018
     */
    public void setNoticeClassificationFirstLevelName(String noticeClassificationFirstLevelName) {
        this.noticeClassificationFirstLevelName = noticeClassificationFirstLevelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_notice.notice_classification_second_level_name
     *
     * @return the value of neeq_notice.notice_classification_second_level_name
     *
     * @mbggenerated Fri Mar 23 14:41:57 CST 2018
     */
    public String getNoticeClassificationSecondLevelName() {
        return noticeClassificationSecondLevelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_notice.notice_classification_second_level_name
     *
     * @param noticeClassificationSecondLevelName the value for neeq_notice.notice_classification_second_level_name
     *
     * @mbggenerated Fri Mar 23 14:41:57 CST 2018
     */
    public void setNoticeClassificationSecondLevelName(String noticeClassificationSecondLevelName) {
        this.noticeClassificationSecondLevelName = noticeClassificationSecondLevelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_notice.positiveornegative
     *
     * @return the value of neeq_notice.positiveornegative
     *
     * @mbggenerated Fri Mar 23 14:41:57 CST 2018
     */
    public String getPositiveornegative() {
        return positiveornegative;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_notice.positiveornegative
     *
     * @param positiveornegative the value for neeq_notice.positiveornegative
     *
     * @mbggenerated Fri Mar 23 14:41:57 CST 2018
     */
    public void setPositiveornegative(String positiveornegative) {
        this.positiveornegative = positiveornegative;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_notice.status
     *
     * @return the value of neeq_notice.status
     *
     * @mbggenerated Fri Mar 23 14:41:57 CST 2018
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_notice.status
     *
     * @param status the value for neeq_notice.status
     *
     * @mbggenerated Fri Mar 23 14:41:57 CST 2018
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_notice.created_at
     *
     * @return the value of neeq_notice.created_at
     *
     * @mbggenerated Fri Mar 23 14:41:57 CST 2018
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_notice.created_at
     *
     * @param createdAt the value for neeq_notice.created_at
     *
     * @mbggenerated Fri Mar 23 14:41:57 CST 2018
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_notice.updated_at
     *
     * @return the value of neeq_notice.updated_at
     *
     * @mbggenerated Fri Mar 23 14:41:57 CST 2018
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_notice.updated_at
     *
     * @param updatedAt the value for neeq_notice.updated_at
     *
     * @mbggenerated Fri Mar 23 14:41:57 CST 2018
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_notice.content
     *
     * @return the value of neeq_notice.content
     *
     * @mbggenerated Fri Mar 23 14:41:57 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_notice.content
     *
     * @param content the value for neeq_notice.content
     *
     * @mbggenerated Fri Mar 23 14:41:57 CST 2018
     */
    public void setContent(String content) {
        this.content = content;
    }
}