package com.kf.data.mybatis.entity.online;

import java.util.Date;

public class NeeqCompanyAdmPenaltyOnline {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company_adm_penalty.id
     *
     * @mbggenerated Wed Mar 14 10:12:21 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company_adm_penalty.company_id
     *
     * @mbggenerated Wed Mar 14 10:12:21 CST 2018
     */
    private String companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company_adm_penalty.company_name
     *
     * @mbggenerated Wed Mar 14 10:12:21 CST 2018
     */
    private String companyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company_adm_penalty.dt_effective
     *
     * @mbggenerated Wed Mar 14 10:12:21 CST 2018
     */
    private Date dtEffective;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company_adm_penalty.order_number
     *
     * @mbggenerated Wed Mar 14 10:12:21 CST 2018
     */
    private String orderNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company_adm_penalty.type
     *
     * @mbggenerated Wed Mar 14 10:12:21 CST 2018
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company_adm_penalty.agency
     *
     * @mbggenerated Wed Mar 14 10:12:21 CST 2018
     */
    private String agency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company_adm_penalty.penalty_content
     *
     * @mbggenerated Wed Mar 14 10:12:21 CST 2018
     */
    private String penaltyContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company_adm_penalty.notice_url
     *
     * @mbggenerated Wed Mar 14 10:12:21 CST 2018
     */
    private String noticeUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company_adm_penalty.legal_person
     *
     * @mbggenerated Wed Mar 14 10:12:21 CST 2018
     */
    private String legalPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company_adm_penalty.status
     *
     * @mbggenerated Wed Mar 14 10:12:21 CST 2018
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company_adm_penalty.created_at
     *
     * @mbggenerated Wed Mar 14 10:12:21 CST 2018
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company_adm_penalty.updated_at
     *
     * @mbggenerated Wed Mar 14 10:12:21 CST 2018
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company_adm_penalty.id
     *
     * @return the value of neeq_company_adm_penalty.id
     *
     * @mbggenerated Wed Mar 14 10:12:21 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company_adm_penalty.id
     *
     * @param id the value for neeq_company_adm_penalty.id
     *
     * @mbggenerated Wed Mar 14 10:12:21 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company_adm_penalty.company_id
     *
     * @return the value of neeq_company_adm_penalty.company_id
     *
     * @mbggenerated Wed Mar 14 10:12:21 CST 2018
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company_adm_penalty.company_id
     *
     * @param companyId the value for neeq_company_adm_penalty.company_id
     *
     * @mbggenerated Wed Mar 14 10:12:21 CST 2018
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company_adm_penalty.company_name
     *
     * @return the value of neeq_company_adm_penalty.company_name
     *
     * @mbggenerated Wed Mar 14 10:12:21 CST 2018
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company_adm_penalty.company_name
     *
     * @param companyName the value for neeq_company_adm_penalty.company_name
     *
     * @mbggenerated Wed Mar 14 10:12:21 CST 2018
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company_adm_penalty.dt_effective
     *
     * @return the value of neeq_company_adm_penalty.dt_effective
     *
     * @mbggenerated Wed Mar 14 10:12:21 CST 2018
     */
    public Date getDtEffective() {
        return dtEffective;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company_adm_penalty.dt_effective
     *
     * @param dtEffective the value for neeq_company_adm_penalty.dt_effective
     *
     * @mbggenerated Wed Mar 14 10:12:21 CST 2018
     */
    public void setDtEffective(Date dtEffective) {
        this.dtEffective = dtEffective;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company_adm_penalty.order_number
     *
     * @return the value of neeq_company_adm_penalty.order_number
     *
     * @mbggenerated Wed Mar 14 10:12:21 CST 2018
     */
    public String getOrderNumber() {
        return orderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company_adm_penalty.order_number
     *
     * @param orderNumber the value for neeq_company_adm_penalty.order_number
     *
     * @mbggenerated Wed Mar 14 10:12:21 CST 2018
     */
    public void setOrderNumber(String orderNumber) {
        this.orderNumber = orderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company_adm_penalty.type
     *
     * @return the value of neeq_company_adm_penalty.type
     *
     * @mbggenerated Wed Mar 14 10:12:21 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company_adm_penalty.type
     *
     * @param type the value for neeq_company_adm_penalty.type
     *
     * @mbggenerated Wed Mar 14 10:12:21 CST 2018
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company_adm_penalty.agency
     *
     * @return the value of neeq_company_adm_penalty.agency
     *
     * @mbggenerated Wed Mar 14 10:12:21 CST 2018
     */
    public String getAgency() {
        return agency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company_adm_penalty.agency
     *
     * @param agency the value for neeq_company_adm_penalty.agency
     *
     * @mbggenerated Wed Mar 14 10:12:21 CST 2018
     */
    public void setAgency(String agency) {
        this.agency = agency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company_adm_penalty.penalty_content
     *
     * @return the value of neeq_company_adm_penalty.penalty_content
     *
     * @mbggenerated Wed Mar 14 10:12:21 CST 2018
     */
    public String getPenaltyContent() {
        return penaltyContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company_adm_penalty.penalty_content
     *
     * @param penaltyContent the value for neeq_company_adm_penalty.penalty_content
     *
     * @mbggenerated Wed Mar 14 10:12:21 CST 2018
     */
    public void setPenaltyContent(String penaltyContent) {
        this.penaltyContent = penaltyContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company_adm_penalty.notice_url
     *
     * @return the value of neeq_company_adm_penalty.notice_url
     *
     * @mbggenerated Wed Mar 14 10:12:21 CST 2018
     */
    public String getNoticeUrl() {
        return noticeUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company_adm_penalty.notice_url
     *
     * @param noticeUrl the value for neeq_company_adm_penalty.notice_url
     *
     * @mbggenerated Wed Mar 14 10:12:21 CST 2018
     */
    public void setNoticeUrl(String noticeUrl) {
        this.noticeUrl = noticeUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company_adm_penalty.legal_person
     *
     * @return the value of neeq_company_adm_penalty.legal_person
     *
     * @mbggenerated Wed Mar 14 10:12:21 CST 2018
     */
    public String getLegalPerson() {
        return legalPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company_adm_penalty.legal_person
     *
     * @param legalPerson the value for neeq_company_adm_penalty.legal_person
     *
     * @mbggenerated Wed Mar 14 10:12:21 CST 2018
     */
    public void setLegalPerson(String legalPerson) {
        this.legalPerson = legalPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company_adm_penalty.status
     *
     * @return the value of neeq_company_adm_penalty.status
     *
     * @mbggenerated Wed Mar 14 10:12:21 CST 2018
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company_adm_penalty.status
     *
     * @param status the value for neeq_company_adm_penalty.status
     *
     * @mbggenerated Wed Mar 14 10:12:21 CST 2018
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company_adm_penalty.created_at
     *
     * @return the value of neeq_company_adm_penalty.created_at
     *
     * @mbggenerated Wed Mar 14 10:12:21 CST 2018
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company_adm_penalty.created_at
     *
     * @param createdAt the value for neeq_company_adm_penalty.created_at
     *
     * @mbggenerated Wed Mar 14 10:12:21 CST 2018
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company_adm_penalty.updated_at
     *
     * @return the value of neeq_company_adm_penalty.updated_at
     *
     * @mbggenerated Wed Mar 14 10:12:21 CST 2018
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company_adm_penalty.updated_at
     *
     * @param updatedAt the value for neeq_company_adm_penalty.updated_at
     *
     * @mbggenerated Wed Mar 14 10:12:21 CST 2018
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}