package com.kf.data.mybatis.entity.online;

import java.util.Date;

public class NeeqCompanyDivOnline {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company_div.id
     *
     * @mbggenerated Wed Mar 14 10:01:34 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company_div.company_id
     *
     * @mbggenerated Wed Mar 14 10:01:34 CST 2018
     */
    private String companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company_div.stock_code
     *
     * @mbggenerated Wed Mar 14 10:01:34 CST 2018
     */
    private String stockCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company_div.stock_name
     *
     * @mbggenerated Wed Mar 14 10:01:34 CST 2018
     */
    private String stockName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company_div.dt_report
     *
     * @mbggenerated Wed Mar 14 10:01:34 CST 2018
     */
    private Date dtReport;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company_div.div_dscrp
     *
     * @mbggenerated Wed Mar 14 10:01:34 CST 2018
     */
    private String divDscrp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company_div.dt_regist
     *
     * @mbggenerated Wed Mar 14 10:01:34 CST 2018
     */
    private Date dtRegist;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company_div.progress_code
     *
     * @mbggenerated Wed Mar 14 10:01:34 CST 2018
     */
    private String progressCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company_div.progress_name
     *
     * @mbggenerated Wed Mar 14 10:01:34 CST 2018
     */
    private String progressName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company_div.div_pre_tax
     *
     * @mbggenerated Wed Mar 14 10:01:34 CST 2018
     */
    private Double divPreTax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company_div.div_post_tax
     *
     * @mbggenerated Wed Mar 14 10:01:34 CST 2018
     */
    private Double divPostTax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company_div.bonus_ratio
     *
     * @mbggenerated Wed Mar 14 10:01:34 CST 2018
     */
    private Double bonusRatio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company_div.transfer_ratio
     *
     * @mbggenerated Wed Mar 14 10:01:34 CST 2018
     */
    private Double transferRatio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company_div.capital_base
     *
     * @mbggenerated Wed Mar 14 10:01:34 CST 2018
     */
    private Double capitalBase;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company_div.capital_pre_div
     *
     * @mbggenerated Wed Mar 14 10:01:34 CST 2018
     */
    private Double capitalPreDiv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company_div.capital_post_div
     *
     * @mbggenerated Wed Mar 14 10:01:34 CST 2018
     */
    private Double capitalPostDiv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company_div.dt_capital_base
     *
     * @mbggenerated Wed Mar 14 10:01:34 CST 2018
     */
    private Date dtCapitalBase;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company_div.dt_plan
     *
     * @mbggenerated Wed Mar 14 10:01:34 CST 2018
     */
    private Date dtPlan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company_div.dt_sgm
     *
     * @mbggenerated Wed Mar 14 10:01:34 CST 2018
     */
    private Date dtSgm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company_div.dt_notice
     *
     * @mbggenerated Wed Mar 14 10:01:34 CST 2018
     */
    private Date dtNotice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company_div.dt_div_ex
     *
     * @mbggenerated Wed Mar 14 10:01:34 CST 2018
     */
    private Date dtDivEx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company_div.dt_div
     *
     * @mbggenerated Wed Mar 14 10:01:34 CST 2018
     */
    private Date dtDiv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company_div.dt_listing
     *
     * @mbggenerated Wed Mar 14 10:01:34 CST 2018
     */
    private Date dtListing;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company_div.div_obj
     *
     * @mbggenerated Wed Mar 14 10:01:34 CST 2018
     */
    private String divObj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company_div.status
     *
     * @mbggenerated Wed Mar 14 10:01:34 CST 2018
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company_div.created_at
     *
     * @mbggenerated Wed Mar 14 10:01:34 CST 2018
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company_div.updated_at
     *
     * @mbggenerated Wed Mar 14 10:01:34 CST 2018
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company_div.id
     *
     * @return the value of neeq_company_div.id
     *
     * @mbggenerated Wed Mar 14 10:01:34 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company_div.id
     *
     * @param id the value for neeq_company_div.id
     *
     * @mbggenerated Wed Mar 14 10:01:34 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company_div.company_id
     *
     * @return the value of neeq_company_div.company_id
     *
     * @mbggenerated Wed Mar 14 10:01:34 CST 2018
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company_div.company_id
     *
     * @param companyId the value for neeq_company_div.company_id
     *
     * @mbggenerated Wed Mar 14 10:01:34 CST 2018
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company_div.stock_code
     *
     * @return the value of neeq_company_div.stock_code
     *
     * @mbggenerated Wed Mar 14 10:01:34 CST 2018
     */
    public String getStockCode() {
        return stockCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company_div.stock_code
     *
     * @param stockCode the value for neeq_company_div.stock_code
     *
     * @mbggenerated Wed Mar 14 10:01:34 CST 2018
     */
    public void setStockCode(String stockCode) {
        this.stockCode = stockCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company_div.stock_name
     *
     * @return the value of neeq_company_div.stock_name
     *
     * @mbggenerated Wed Mar 14 10:01:34 CST 2018
     */
    public String getStockName() {
        return stockName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company_div.stock_name
     *
     * @param stockName the value for neeq_company_div.stock_name
     *
     * @mbggenerated Wed Mar 14 10:01:34 CST 2018
     */
    public void setStockName(String stockName) {
        this.stockName = stockName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company_div.dt_report
     *
     * @return the value of neeq_company_div.dt_report
     *
     * @mbggenerated Wed Mar 14 10:01:34 CST 2018
     */
    public Date getDtReport() {
        return dtReport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company_div.dt_report
     *
     * @param dtReport the value for neeq_company_div.dt_report
     *
     * @mbggenerated Wed Mar 14 10:01:34 CST 2018
     */
    public void setDtReport(Date dtReport) {
        this.dtReport = dtReport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company_div.div_dscrp
     *
     * @return the value of neeq_company_div.div_dscrp
     *
     * @mbggenerated Wed Mar 14 10:01:34 CST 2018
     */
    public String getDivDscrp() {
        return divDscrp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company_div.div_dscrp
     *
     * @param divDscrp the value for neeq_company_div.div_dscrp
     *
     * @mbggenerated Wed Mar 14 10:01:34 CST 2018
     */
    public void setDivDscrp(String divDscrp) {
        this.divDscrp = divDscrp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company_div.dt_regist
     *
     * @return the value of neeq_company_div.dt_regist
     *
     * @mbggenerated Wed Mar 14 10:01:34 CST 2018
     */
    public Date getDtRegist() {
        return dtRegist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company_div.dt_regist
     *
     * @param dtRegist the value for neeq_company_div.dt_regist
     *
     * @mbggenerated Wed Mar 14 10:01:34 CST 2018
     */
    public void setDtRegist(Date dtRegist) {
        this.dtRegist = dtRegist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company_div.progress_code
     *
     * @return the value of neeq_company_div.progress_code
     *
     * @mbggenerated Wed Mar 14 10:01:34 CST 2018
     */
    public String getProgressCode() {
        return progressCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company_div.progress_code
     *
     * @param progressCode the value for neeq_company_div.progress_code
     *
     * @mbggenerated Wed Mar 14 10:01:34 CST 2018
     */
    public void setProgressCode(String progressCode) {
        this.progressCode = progressCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company_div.progress_name
     *
     * @return the value of neeq_company_div.progress_name
     *
     * @mbggenerated Wed Mar 14 10:01:34 CST 2018
     */
    public String getProgressName() {
        return progressName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company_div.progress_name
     *
     * @param progressName the value for neeq_company_div.progress_name
     *
     * @mbggenerated Wed Mar 14 10:01:34 CST 2018
     */
    public void setProgressName(String progressName) {
        this.progressName = progressName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company_div.div_pre_tax
     *
     * @return the value of neeq_company_div.div_pre_tax
     *
     * @mbggenerated Wed Mar 14 10:01:34 CST 2018
     */
    public Double getDivPreTax() {
        return divPreTax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company_div.div_pre_tax
     *
     * @param divPreTax the value for neeq_company_div.div_pre_tax
     *
     * @mbggenerated Wed Mar 14 10:01:34 CST 2018
     */
    public void setDivPreTax(Double divPreTax) {
        this.divPreTax = divPreTax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company_div.div_post_tax
     *
     * @return the value of neeq_company_div.div_post_tax
     *
     * @mbggenerated Wed Mar 14 10:01:34 CST 2018
     */
    public Double getDivPostTax() {
        return divPostTax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company_div.div_post_tax
     *
     * @param divPostTax the value for neeq_company_div.div_post_tax
     *
     * @mbggenerated Wed Mar 14 10:01:34 CST 2018
     */
    public void setDivPostTax(Double divPostTax) {
        this.divPostTax = divPostTax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company_div.bonus_ratio
     *
     * @return the value of neeq_company_div.bonus_ratio
     *
     * @mbggenerated Wed Mar 14 10:01:34 CST 2018
     */
    public Double getBonusRatio() {
        return bonusRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company_div.bonus_ratio
     *
     * @param bonusRatio the value for neeq_company_div.bonus_ratio
     *
     * @mbggenerated Wed Mar 14 10:01:34 CST 2018
     */
    public void setBonusRatio(Double bonusRatio) {
        this.bonusRatio = bonusRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company_div.transfer_ratio
     *
     * @return the value of neeq_company_div.transfer_ratio
     *
     * @mbggenerated Wed Mar 14 10:01:34 CST 2018
     */
    public Double getTransferRatio() {
        return transferRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company_div.transfer_ratio
     *
     * @param transferRatio the value for neeq_company_div.transfer_ratio
     *
     * @mbggenerated Wed Mar 14 10:01:34 CST 2018
     */
    public void setTransferRatio(Double transferRatio) {
        this.transferRatio = transferRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company_div.capital_base
     *
     * @return the value of neeq_company_div.capital_base
     *
     * @mbggenerated Wed Mar 14 10:01:34 CST 2018
     */
    public Double getCapitalBase() {
        return capitalBase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company_div.capital_base
     *
     * @param capitalBase the value for neeq_company_div.capital_base
     *
     * @mbggenerated Wed Mar 14 10:01:34 CST 2018
     */
    public void setCapitalBase(Double capitalBase) {
        this.capitalBase = capitalBase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company_div.capital_pre_div
     *
     * @return the value of neeq_company_div.capital_pre_div
     *
     * @mbggenerated Wed Mar 14 10:01:34 CST 2018
     */
    public Double getCapitalPreDiv() {
        return capitalPreDiv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company_div.capital_pre_div
     *
     * @param capitalPreDiv the value for neeq_company_div.capital_pre_div
     *
     * @mbggenerated Wed Mar 14 10:01:34 CST 2018
     */
    public void setCapitalPreDiv(Double capitalPreDiv) {
        this.capitalPreDiv = capitalPreDiv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company_div.capital_post_div
     *
     * @return the value of neeq_company_div.capital_post_div
     *
     * @mbggenerated Wed Mar 14 10:01:34 CST 2018
     */
    public Double getCapitalPostDiv() {
        return capitalPostDiv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company_div.capital_post_div
     *
     * @param capitalPostDiv the value for neeq_company_div.capital_post_div
     *
     * @mbggenerated Wed Mar 14 10:01:34 CST 2018
     */
    public void setCapitalPostDiv(Double capitalPostDiv) {
        this.capitalPostDiv = capitalPostDiv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company_div.dt_capital_base
     *
     * @return the value of neeq_company_div.dt_capital_base
     *
     * @mbggenerated Wed Mar 14 10:01:34 CST 2018
     */
    public Date getDtCapitalBase() {
        return dtCapitalBase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company_div.dt_capital_base
     *
     * @param dtCapitalBase the value for neeq_company_div.dt_capital_base
     *
     * @mbggenerated Wed Mar 14 10:01:34 CST 2018
     */
    public void setDtCapitalBase(Date dtCapitalBase) {
        this.dtCapitalBase = dtCapitalBase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company_div.dt_plan
     *
     * @return the value of neeq_company_div.dt_plan
     *
     * @mbggenerated Wed Mar 14 10:01:34 CST 2018
     */
    public Date getDtPlan() {
        return dtPlan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company_div.dt_plan
     *
     * @param dtPlan the value for neeq_company_div.dt_plan
     *
     * @mbggenerated Wed Mar 14 10:01:34 CST 2018
     */
    public void setDtPlan(Date dtPlan) {
        this.dtPlan = dtPlan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company_div.dt_sgm
     *
     * @return the value of neeq_company_div.dt_sgm
     *
     * @mbggenerated Wed Mar 14 10:01:34 CST 2018
     */
    public Date getDtSgm() {
        return dtSgm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company_div.dt_sgm
     *
     * @param dtSgm the value for neeq_company_div.dt_sgm
     *
     * @mbggenerated Wed Mar 14 10:01:34 CST 2018
     */
    public void setDtSgm(Date dtSgm) {
        this.dtSgm = dtSgm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company_div.dt_notice
     *
     * @return the value of neeq_company_div.dt_notice
     *
     * @mbggenerated Wed Mar 14 10:01:34 CST 2018
     */
    public Date getDtNotice() {
        return dtNotice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company_div.dt_notice
     *
     * @param dtNotice the value for neeq_company_div.dt_notice
     *
     * @mbggenerated Wed Mar 14 10:01:34 CST 2018
     */
    public void setDtNotice(Date dtNotice) {
        this.dtNotice = dtNotice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company_div.dt_div_ex
     *
     * @return the value of neeq_company_div.dt_div_ex
     *
     * @mbggenerated Wed Mar 14 10:01:34 CST 2018
     */
    public Date getDtDivEx() {
        return dtDivEx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company_div.dt_div_ex
     *
     * @param dtDivEx the value for neeq_company_div.dt_div_ex
     *
     * @mbggenerated Wed Mar 14 10:01:34 CST 2018
     */
    public void setDtDivEx(Date dtDivEx) {
        this.dtDivEx = dtDivEx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company_div.dt_div
     *
     * @return the value of neeq_company_div.dt_div
     *
     * @mbggenerated Wed Mar 14 10:01:34 CST 2018
     */
    public Date getDtDiv() {
        return dtDiv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company_div.dt_div
     *
     * @param dtDiv the value for neeq_company_div.dt_div
     *
     * @mbggenerated Wed Mar 14 10:01:34 CST 2018
     */
    public void setDtDiv(Date dtDiv) {
        this.dtDiv = dtDiv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company_div.dt_listing
     *
     * @return the value of neeq_company_div.dt_listing
     *
     * @mbggenerated Wed Mar 14 10:01:34 CST 2018
     */
    public Date getDtListing() {
        return dtListing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company_div.dt_listing
     *
     * @param dtListing the value for neeq_company_div.dt_listing
     *
     * @mbggenerated Wed Mar 14 10:01:34 CST 2018
     */
    public void setDtListing(Date dtListing) {
        this.dtListing = dtListing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company_div.div_obj
     *
     * @return the value of neeq_company_div.div_obj
     *
     * @mbggenerated Wed Mar 14 10:01:34 CST 2018
     */
    public String getDivObj() {
        return divObj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company_div.div_obj
     *
     * @param divObj the value for neeq_company_div.div_obj
     *
     * @mbggenerated Wed Mar 14 10:01:34 CST 2018
     */
    public void setDivObj(String divObj) {
        this.divObj = divObj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company_div.status
     *
     * @return the value of neeq_company_div.status
     *
     * @mbggenerated Wed Mar 14 10:01:34 CST 2018
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company_div.status
     *
     * @param status the value for neeq_company_div.status
     *
     * @mbggenerated Wed Mar 14 10:01:34 CST 2018
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company_div.created_at
     *
     * @return the value of neeq_company_div.created_at
     *
     * @mbggenerated Wed Mar 14 10:01:34 CST 2018
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company_div.created_at
     *
     * @param createdAt the value for neeq_company_div.created_at
     *
     * @mbggenerated Wed Mar 14 10:01:34 CST 2018
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company_div.updated_at
     *
     * @return the value of neeq_company_div.updated_at
     *
     * @mbggenerated Wed Mar 14 10:01:34 CST 2018
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company_div.updated_at
     *
     * @param updatedAt the value for neeq_company_div.updated_at
     *
     * @mbggenerated Wed Mar 14 10:01:34 CST 2018
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}