package com.kf.data.mybatis.entity.online;

public class NeeqHistoryQuotationOnline {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column neeq_history_quotation.id
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column neeq_history_quotation.date
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	private String date;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column neeq_history_quotation.time
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	private String time;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column neeq_history_quotation.stock_id
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	private String stockId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column neeq_history_quotation.stock_code
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	private String stockCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column neeq_history_quotation.shortname
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	private String shortname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column neeq_history_quotation.previous_price
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	private Double previousPrice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column neeq_history_quotation.open_price
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	private Double openPrice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column neeq_history_quotation.current_price
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	private Double currentPrice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column neeq_history_quotation.deal_volumn
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	private Double dealVolumn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column neeq_history_quotation.deal_sum
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	private Double dealSum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column neeq_history_quotation.deal_num
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	private Double dealNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column neeq_history_quotation.max_price
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	private Double maxPrice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column neeq_history_quotation.min_price
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	private Double minPrice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column neeq_history_quotation.static_pe
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	private Double staticPe;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column neeq_history_quotation.dynamic_pe
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	private Double dynamicPe;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column neeq_history_quotation.up_down_close
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	private Double upDownClose;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column neeq_history_quotation.up_down_last
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	private Double upDownLast;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column neeq_history_quotation.open_interest
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	private Double openInterest;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column neeq_history_quotation.sell_price_10
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	private Double sellPrice10;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column neeq_history_quotation.sell_volumn_10
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	private Double sellVolumn10;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column neeq_history_quotation.sell_price_9
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	private Double sellPrice9;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column neeq_history_quotation.sell_volumn_9
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	private Double sellVolumn9;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column neeq_history_quotation.sell_price_8
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	private Double sellPrice8;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column neeq_history_quotation.sell_volumn_8
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	private Double sellVolumn8;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column neeq_history_quotation.sell_price_7
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	private Double sellPrice7;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column neeq_history_quotation.sell_volumn_7
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	private Double sellVolumn7;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column neeq_history_quotation.sell_price_6
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	private Double sellPrice6;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column neeq_history_quotation.sell_volumn_6
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	private Double sellVolumn6;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column neeq_history_quotation.sell_price_5
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	private Double sellPrice5;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column neeq_history_quotation.sell_volumn_5
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	private Double sellVolumn5;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column neeq_history_quotation.sell_price_4
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	private Double sellPrice4;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column neeq_history_quotation.sell_volumn_4
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	private Double sellVolumn4;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column neeq_history_quotation.sell_price_3
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	private Double sellPrice3;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column neeq_history_quotation.sell_volumn_3
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	private Double sellVolumn3;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column neeq_history_quotation.sell_price_2
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	private Double sellPrice2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column neeq_history_quotation.sell_volumn_2
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	private Double sellVolumn2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column neeq_history_quotation.sell_price_1
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	private Double sellPrice1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column neeq_history_quotation.sell_volumn_1
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	private Double sellVolumn1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column neeq_history_quotation.buy_price_1
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	private Double buyPrice1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column neeq_history_quotation.buy_volumn_1
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	private Double buyVolumn1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column neeq_history_quotation.buy_price_2
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	private Double buyPrice2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column neeq_history_quotation.buy_volumn_2
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	private Double buyVolumn2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column neeq_history_quotation.buy_price_3
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	private Double buyPrice3;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column neeq_history_quotation.buy_volumn_3
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	private Double buyVolumn3;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column neeq_history_quotation.buy_price_4
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	private Double buyPrice4;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column neeq_history_quotation.buy_volumn_4
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	private Double buyVolumn4;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column neeq_history_quotation.buy_price_5
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	private Double buyPrice5;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column neeq_history_quotation.buy_volumn_5
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	private Double buyVolumn5;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column neeq_history_quotation.buy_price_6
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	private Double buyPrice6;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column neeq_history_quotation.buy_volumn_6
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	private Double buyVolumn6;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column neeq_history_quotation.buy_price_7
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	private Double buyPrice7;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column neeq_history_quotation.buy_volumn_7
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	private Double buyVolumn7;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column neeq_history_quotation.buy_price_8
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	private Double buyPrice8;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column neeq_history_quotation.buy_volumn_8
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	private Double buyVolumn8;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column neeq_history_quotation.buy_price_9
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	private Double buyPrice9;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column neeq_history_quotation.buy_volumn_9
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	private Double buyVolumn9;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column neeq_history_quotation.buy_price_10
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	private Double buyPrice10;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column neeq_history_quotation.buy_volumn_10
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	private Double buyVolumn10;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column neeq_history_quotation.up_down_rate_close
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	private Double upDownRateClose;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column neeq_history_quotation.pe_rate
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	private Double peRate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column neeq_history_quotation.trans_rate
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	private Double transRate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column neeq_history_quotation.pb_rate
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	private Double pbRate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column neeq_history_quotation.market_value
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	private Double marketValue;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column neeq_history_quotation.avarage_price
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	private Double avaragePrice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column neeq_history_quotation.total_value
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	private Double totalValue;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column neeq_history_quotation.change_range_rate
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	private Double changeRangeRate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column neeq_history_quotation.id
	 * @return  the value of neeq_history_quotation.id
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column neeq_history_quotation.id
	 * @param id  the value for neeq_history_quotation.id
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column neeq_history_quotation.date
	 * @return  the value of neeq_history_quotation.date
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public String getDate() {
		return date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column neeq_history_quotation.date
	 * @param date  the value for neeq_history_quotation.date
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public void setDate(String date) {
		this.date = date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column neeq_history_quotation.time
	 * @return  the value of neeq_history_quotation.time
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public String getTime() {
		return time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column neeq_history_quotation.time
	 * @param time  the value for neeq_history_quotation.time
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public void setTime(String time) {
		this.time = time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column neeq_history_quotation.stock_id
	 * @return  the value of neeq_history_quotation.stock_id
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public String getStockId() {
		return stockId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column neeq_history_quotation.stock_id
	 * @param stockId  the value for neeq_history_quotation.stock_id
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public void setStockId(String stockId) {
		this.stockId = stockId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column neeq_history_quotation.stock_code
	 * @return  the value of neeq_history_quotation.stock_code
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public String getStockCode() {
		return stockCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column neeq_history_quotation.stock_code
	 * @param stockCode  the value for neeq_history_quotation.stock_code
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public void setStockCode(String stockCode) {
		this.stockCode = stockCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column neeq_history_quotation.shortname
	 * @return  the value of neeq_history_quotation.shortname
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public String getShortname() {
		return shortname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column neeq_history_quotation.shortname
	 * @param shortname  the value for neeq_history_quotation.shortname
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public void setShortname(String shortname) {
		this.shortname = shortname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column neeq_history_quotation.previous_price
	 * @return  the value of neeq_history_quotation.previous_price
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public Double getPreviousPrice() {
		return previousPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column neeq_history_quotation.previous_price
	 * @param previousPrice  the value for neeq_history_quotation.previous_price
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public void setPreviousPrice(Double previousPrice) {
		this.previousPrice = previousPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column neeq_history_quotation.open_price
	 * @return  the value of neeq_history_quotation.open_price
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public Double getOpenPrice() {
		return openPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column neeq_history_quotation.open_price
	 * @param openPrice  the value for neeq_history_quotation.open_price
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public void setOpenPrice(Double openPrice) {
		this.openPrice = openPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column neeq_history_quotation.current_price
	 * @return  the value of neeq_history_quotation.current_price
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public Double getCurrentPrice() {
		return currentPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column neeq_history_quotation.current_price
	 * @param currentPrice  the value for neeq_history_quotation.current_price
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public void setCurrentPrice(Double currentPrice) {
		this.currentPrice = currentPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column neeq_history_quotation.deal_volumn
	 * @return  the value of neeq_history_quotation.deal_volumn
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public Double getDealVolumn() {
		return dealVolumn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column neeq_history_quotation.deal_volumn
	 * @param dealVolumn  the value for neeq_history_quotation.deal_volumn
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public void setDealVolumn(Double dealVolumn) {
		this.dealVolumn = dealVolumn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column neeq_history_quotation.deal_sum
	 * @return  the value of neeq_history_quotation.deal_sum
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public Double getDealSum() {
		return dealSum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column neeq_history_quotation.deal_sum
	 * @param dealSum  the value for neeq_history_quotation.deal_sum
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public void setDealSum(Double dealSum) {
		this.dealSum = dealSum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column neeq_history_quotation.deal_num
	 * @return  the value of neeq_history_quotation.deal_num
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public Double getDealNum() {
		return dealNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column neeq_history_quotation.deal_num
	 * @param dealNum  the value for neeq_history_quotation.deal_num
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public void setDealNum(Double dealNum) {
		this.dealNum = dealNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column neeq_history_quotation.max_price
	 * @return  the value of neeq_history_quotation.max_price
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public Double getMaxPrice() {
		return maxPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column neeq_history_quotation.max_price
	 * @param maxPrice  the value for neeq_history_quotation.max_price
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public void setMaxPrice(Double maxPrice) {
		this.maxPrice = maxPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column neeq_history_quotation.min_price
	 * @return  the value of neeq_history_quotation.min_price
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public Double getMinPrice() {
		return minPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column neeq_history_quotation.min_price
	 * @param minPrice  the value for neeq_history_quotation.min_price
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public void setMinPrice(Double minPrice) {
		this.minPrice = minPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column neeq_history_quotation.static_pe
	 * @return  the value of neeq_history_quotation.static_pe
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public Double getStaticPe() {
		return staticPe;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column neeq_history_quotation.static_pe
	 * @param staticPe  the value for neeq_history_quotation.static_pe
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public void setStaticPe(Double staticPe) {
		this.staticPe = staticPe;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column neeq_history_quotation.dynamic_pe
	 * @return  the value of neeq_history_quotation.dynamic_pe
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public Double getDynamicPe() {
		return dynamicPe;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column neeq_history_quotation.dynamic_pe
	 * @param dynamicPe  the value for neeq_history_quotation.dynamic_pe
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public void setDynamicPe(Double dynamicPe) {
		this.dynamicPe = dynamicPe;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column neeq_history_quotation.up_down_close
	 * @return  the value of neeq_history_quotation.up_down_close
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public Double getUpDownClose() {
		return upDownClose;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column neeq_history_quotation.up_down_close
	 * @param upDownClose  the value for neeq_history_quotation.up_down_close
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public void setUpDownClose(Double upDownClose) {
		this.upDownClose = upDownClose;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column neeq_history_quotation.up_down_last
	 * @return  the value of neeq_history_quotation.up_down_last
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public Double getUpDownLast() {
		return upDownLast;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column neeq_history_quotation.up_down_last
	 * @param upDownLast  the value for neeq_history_quotation.up_down_last
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public void setUpDownLast(Double upDownLast) {
		this.upDownLast = upDownLast;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column neeq_history_quotation.open_interest
	 * @return  the value of neeq_history_quotation.open_interest
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public Double getOpenInterest() {
		return openInterest;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column neeq_history_quotation.open_interest
	 * @param openInterest  the value for neeq_history_quotation.open_interest
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public void setOpenInterest(Double openInterest) {
		this.openInterest = openInterest;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column neeq_history_quotation.sell_price_10
	 * @return  the value of neeq_history_quotation.sell_price_10
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public Double getSellPrice10() {
		return sellPrice10;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column neeq_history_quotation.sell_price_10
	 * @param sellPrice10  the value for neeq_history_quotation.sell_price_10
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public void setSellPrice10(Double sellPrice10) {
		this.sellPrice10 = sellPrice10;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column neeq_history_quotation.sell_volumn_10
	 * @return  the value of neeq_history_quotation.sell_volumn_10
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public Double getSellVolumn10() {
		return sellVolumn10;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column neeq_history_quotation.sell_volumn_10
	 * @param sellVolumn10  the value for neeq_history_quotation.sell_volumn_10
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public void setSellVolumn10(Double sellVolumn10) {
		this.sellVolumn10 = sellVolumn10;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column neeq_history_quotation.sell_price_9
	 * @return  the value of neeq_history_quotation.sell_price_9
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public Double getSellPrice9() {
		return sellPrice9;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column neeq_history_quotation.sell_price_9
	 * @param sellPrice9  the value for neeq_history_quotation.sell_price_9
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public void setSellPrice9(Double sellPrice9) {
		this.sellPrice9 = sellPrice9;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column neeq_history_quotation.sell_volumn_9
	 * @return  the value of neeq_history_quotation.sell_volumn_9
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public Double getSellVolumn9() {
		return sellVolumn9;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column neeq_history_quotation.sell_volumn_9
	 * @param sellVolumn9  the value for neeq_history_quotation.sell_volumn_9
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public void setSellVolumn9(Double sellVolumn9) {
		this.sellVolumn9 = sellVolumn9;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column neeq_history_quotation.sell_price_8
	 * @return  the value of neeq_history_quotation.sell_price_8
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public Double getSellPrice8() {
		return sellPrice8;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column neeq_history_quotation.sell_price_8
	 * @param sellPrice8  the value for neeq_history_quotation.sell_price_8
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public void setSellPrice8(Double sellPrice8) {
		this.sellPrice8 = sellPrice8;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column neeq_history_quotation.sell_volumn_8
	 * @return  the value of neeq_history_quotation.sell_volumn_8
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public Double getSellVolumn8() {
		return sellVolumn8;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column neeq_history_quotation.sell_volumn_8
	 * @param sellVolumn8  the value for neeq_history_quotation.sell_volumn_8
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public void setSellVolumn8(Double sellVolumn8) {
		this.sellVolumn8 = sellVolumn8;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column neeq_history_quotation.sell_price_7
	 * @return  the value of neeq_history_quotation.sell_price_7
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public Double getSellPrice7() {
		return sellPrice7;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column neeq_history_quotation.sell_price_7
	 * @param sellPrice7  the value for neeq_history_quotation.sell_price_7
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public void setSellPrice7(Double sellPrice7) {
		this.sellPrice7 = sellPrice7;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column neeq_history_quotation.sell_volumn_7
	 * @return  the value of neeq_history_quotation.sell_volumn_7
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public Double getSellVolumn7() {
		return sellVolumn7;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column neeq_history_quotation.sell_volumn_7
	 * @param sellVolumn7  the value for neeq_history_quotation.sell_volumn_7
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public void setSellVolumn7(Double sellVolumn7) {
		this.sellVolumn7 = sellVolumn7;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column neeq_history_quotation.sell_price_6
	 * @return  the value of neeq_history_quotation.sell_price_6
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public Double getSellPrice6() {
		return sellPrice6;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column neeq_history_quotation.sell_price_6
	 * @param sellPrice6  the value for neeq_history_quotation.sell_price_6
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public void setSellPrice6(Double sellPrice6) {
		this.sellPrice6 = sellPrice6;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column neeq_history_quotation.sell_volumn_6
	 * @return  the value of neeq_history_quotation.sell_volumn_6
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public Double getSellVolumn6() {
		return sellVolumn6;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column neeq_history_quotation.sell_volumn_6
	 * @param sellVolumn6  the value for neeq_history_quotation.sell_volumn_6
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public void setSellVolumn6(Double sellVolumn6) {
		this.sellVolumn6 = sellVolumn6;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column neeq_history_quotation.sell_price_5
	 * @return  the value of neeq_history_quotation.sell_price_5
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public Double getSellPrice5() {
		return sellPrice5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column neeq_history_quotation.sell_price_5
	 * @param sellPrice5  the value for neeq_history_quotation.sell_price_5
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public void setSellPrice5(Double sellPrice5) {
		this.sellPrice5 = sellPrice5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column neeq_history_quotation.sell_volumn_5
	 * @return  the value of neeq_history_quotation.sell_volumn_5
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public Double getSellVolumn5() {
		return sellVolumn5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column neeq_history_quotation.sell_volumn_5
	 * @param sellVolumn5  the value for neeq_history_quotation.sell_volumn_5
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public void setSellVolumn5(Double sellVolumn5) {
		this.sellVolumn5 = sellVolumn5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column neeq_history_quotation.sell_price_4
	 * @return  the value of neeq_history_quotation.sell_price_4
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public Double getSellPrice4() {
		return sellPrice4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column neeq_history_quotation.sell_price_4
	 * @param sellPrice4  the value for neeq_history_quotation.sell_price_4
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public void setSellPrice4(Double sellPrice4) {
		this.sellPrice4 = sellPrice4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column neeq_history_quotation.sell_volumn_4
	 * @return  the value of neeq_history_quotation.sell_volumn_4
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public Double getSellVolumn4() {
		return sellVolumn4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column neeq_history_quotation.sell_volumn_4
	 * @param sellVolumn4  the value for neeq_history_quotation.sell_volumn_4
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public void setSellVolumn4(Double sellVolumn4) {
		this.sellVolumn4 = sellVolumn4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column neeq_history_quotation.sell_price_3
	 * @return  the value of neeq_history_quotation.sell_price_3
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public Double getSellPrice3() {
		return sellPrice3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column neeq_history_quotation.sell_price_3
	 * @param sellPrice3  the value for neeq_history_quotation.sell_price_3
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public void setSellPrice3(Double sellPrice3) {
		this.sellPrice3 = sellPrice3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column neeq_history_quotation.sell_volumn_3
	 * @return  the value of neeq_history_quotation.sell_volumn_3
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public Double getSellVolumn3() {
		return sellVolumn3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column neeq_history_quotation.sell_volumn_3
	 * @param sellVolumn3  the value for neeq_history_quotation.sell_volumn_3
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public void setSellVolumn3(Double sellVolumn3) {
		this.sellVolumn3 = sellVolumn3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column neeq_history_quotation.sell_price_2
	 * @return  the value of neeq_history_quotation.sell_price_2
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public Double getSellPrice2() {
		return sellPrice2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column neeq_history_quotation.sell_price_2
	 * @param sellPrice2  the value for neeq_history_quotation.sell_price_2
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public void setSellPrice2(Double sellPrice2) {
		this.sellPrice2 = sellPrice2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column neeq_history_quotation.sell_volumn_2
	 * @return  the value of neeq_history_quotation.sell_volumn_2
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public Double getSellVolumn2() {
		return sellVolumn2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column neeq_history_quotation.sell_volumn_2
	 * @param sellVolumn2  the value for neeq_history_quotation.sell_volumn_2
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public void setSellVolumn2(Double sellVolumn2) {
		this.sellVolumn2 = sellVolumn2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column neeq_history_quotation.sell_price_1
	 * @return  the value of neeq_history_quotation.sell_price_1
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public Double getSellPrice1() {
		return sellPrice1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column neeq_history_quotation.sell_price_1
	 * @param sellPrice1  the value for neeq_history_quotation.sell_price_1
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public void setSellPrice1(Double sellPrice1) {
		this.sellPrice1 = sellPrice1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column neeq_history_quotation.sell_volumn_1
	 * @return  the value of neeq_history_quotation.sell_volumn_1
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public Double getSellVolumn1() {
		return sellVolumn1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column neeq_history_quotation.sell_volumn_1
	 * @param sellVolumn1  the value for neeq_history_quotation.sell_volumn_1
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public void setSellVolumn1(Double sellVolumn1) {
		this.sellVolumn1 = sellVolumn1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column neeq_history_quotation.buy_price_1
	 * @return  the value of neeq_history_quotation.buy_price_1
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public Double getBuyPrice1() {
		return buyPrice1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column neeq_history_quotation.buy_price_1
	 * @param buyPrice1  the value for neeq_history_quotation.buy_price_1
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public void setBuyPrice1(Double buyPrice1) {
		this.buyPrice1 = buyPrice1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column neeq_history_quotation.buy_volumn_1
	 * @return  the value of neeq_history_quotation.buy_volumn_1
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public Double getBuyVolumn1() {
		return buyVolumn1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column neeq_history_quotation.buy_volumn_1
	 * @param buyVolumn1  the value for neeq_history_quotation.buy_volumn_1
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public void setBuyVolumn1(Double buyVolumn1) {
		this.buyVolumn1 = buyVolumn1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column neeq_history_quotation.buy_price_2
	 * @return  the value of neeq_history_quotation.buy_price_2
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public Double getBuyPrice2() {
		return buyPrice2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column neeq_history_quotation.buy_price_2
	 * @param buyPrice2  the value for neeq_history_quotation.buy_price_2
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public void setBuyPrice2(Double buyPrice2) {
		this.buyPrice2 = buyPrice2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column neeq_history_quotation.buy_volumn_2
	 * @return  the value of neeq_history_quotation.buy_volumn_2
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public Double getBuyVolumn2() {
		return buyVolumn2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column neeq_history_quotation.buy_volumn_2
	 * @param buyVolumn2  the value for neeq_history_quotation.buy_volumn_2
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public void setBuyVolumn2(Double buyVolumn2) {
		this.buyVolumn2 = buyVolumn2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column neeq_history_quotation.buy_price_3
	 * @return  the value of neeq_history_quotation.buy_price_3
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public Double getBuyPrice3() {
		return buyPrice3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column neeq_history_quotation.buy_price_3
	 * @param buyPrice3  the value for neeq_history_quotation.buy_price_3
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public void setBuyPrice3(Double buyPrice3) {
		this.buyPrice3 = buyPrice3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column neeq_history_quotation.buy_volumn_3
	 * @return  the value of neeq_history_quotation.buy_volumn_3
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public Double getBuyVolumn3() {
		return buyVolumn3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column neeq_history_quotation.buy_volumn_3
	 * @param buyVolumn3  the value for neeq_history_quotation.buy_volumn_3
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public void setBuyVolumn3(Double buyVolumn3) {
		this.buyVolumn3 = buyVolumn3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column neeq_history_quotation.buy_price_4
	 * @return  the value of neeq_history_quotation.buy_price_4
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public Double getBuyPrice4() {
		return buyPrice4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column neeq_history_quotation.buy_price_4
	 * @param buyPrice4  the value for neeq_history_quotation.buy_price_4
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public void setBuyPrice4(Double buyPrice4) {
		this.buyPrice4 = buyPrice4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column neeq_history_quotation.buy_volumn_4
	 * @return  the value of neeq_history_quotation.buy_volumn_4
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public Double getBuyVolumn4() {
		return buyVolumn4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column neeq_history_quotation.buy_volumn_4
	 * @param buyVolumn4  the value for neeq_history_quotation.buy_volumn_4
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public void setBuyVolumn4(Double buyVolumn4) {
		this.buyVolumn4 = buyVolumn4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column neeq_history_quotation.buy_price_5
	 * @return  the value of neeq_history_quotation.buy_price_5
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public Double getBuyPrice5() {
		return buyPrice5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column neeq_history_quotation.buy_price_5
	 * @param buyPrice5  the value for neeq_history_quotation.buy_price_5
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public void setBuyPrice5(Double buyPrice5) {
		this.buyPrice5 = buyPrice5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column neeq_history_quotation.buy_volumn_5
	 * @return  the value of neeq_history_quotation.buy_volumn_5
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public Double getBuyVolumn5() {
		return buyVolumn5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column neeq_history_quotation.buy_volumn_5
	 * @param buyVolumn5  the value for neeq_history_quotation.buy_volumn_5
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public void setBuyVolumn5(Double buyVolumn5) {
		this.buyVolumn5 = buyVolumn5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column neeq_history_quotation.buy_price_6
	 * @return  the value of neeq_history_quotation.buy_price_6
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public Double getBuyPrice6() {
		return buyPrice6;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column neeq_history_quotation.buy_price_6
	 * @param buyPrice6  the value for neeq_history_quotation.buy_price_6
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public void setBuyPrice6(Double buyPrice6) {
		this.buyPrice6 = buyPrice6;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column neeq_history_quotation.buy_volumn_6
	 * @return  the value of neeq_history_quotation.buy_volumn_6
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public Double getBuyVolumn6() {
		return buyVolumn6;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column neeq_history_quotation.buy_volumn_6
	 * @param buyVolumn6  the value for neeq_history_quotation.buy_volumn_6
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public void setBuyVolumn6(Double buyVolumn6) {
		this.buyVolumn6 = buyVolumn6;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column neeq_history_quotation.buy_price_7
	 * @return  the value of neeq_history_quotation.buy_price_7
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public Double getBuyPrice7() {
		return buyPrice7;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column neeq_history_quotation.buy_price_7
	 * @param buyPrice7  the value for neeq_history_quotation.buy_price_7
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public void setBuyPrice7(Double buyPrice7) {
		this.buyPrice7 = buyPrice7;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column neeq_history_quotation.buy_volumn_7
	 * @return  the value of neeq_history_quotation.buy_volumn_7
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public Double getBuyVolumn7() {
		return buyVolumn7;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column neeq_history_quotation.buy_volumn_7
	 * @param buyVolumn7  the value for neeq_history_quotation.buy_volumn_7
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public void setBuyVolumn7(Double buyVolumn7) {
		this.buyVolumn7 = buyVolumn7;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column neeq_history_quotation.buy_price_8
	 * @return  the value of neeq_history_quotation.buy_price_8
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public Double getBuyPrice8() {
		return buyPrice8;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column neeq_history_quotation.buy_price_8
	 * @param buyPrice8  the value for neeq_history_quotation.buy_price_8
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public void setBuyPrice8(Double buyPrice8) {
		this.buyPrice8 = buyPrice8;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column neeq_history_quotation.buy_volumn_8
	 * @return  the value of neeq_history_quotation.buy_volumn_8
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public Double getBuyVolumn8() {
		return buyVolumn8;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column neeq_history_quotation.buy_volumn_8
	 * @param buyVolumn8  the value for neeq_history_quotation.buy_volumn_8
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public void setBuyVolumn8(Double buyVolumn8) {
		this.buyVolumn8 = buyVolumn8;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column neeq_history_quotation.buy_price_9
	 * @return  the value of neeq_history_quotation.buy_price_9
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public Double getBuyPrice9() {
		return buyPrice9;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column neeq_history_quotation.buy_price_9
	 * @param buyPrice9  the value for neeq_history_quotation.buy_price_9
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public void setBuyPrice9(Double buyPrice9) {
		this.buyPrice9 = buyPrice9;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column neeq_history_quotation.buy_volumn_9
	 * @return  the value of neeq_history_quotation.buy_volumn_9
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public Double getBuyVolumn9() {
		return buyVolumn9;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column neeq_history_quotation.buy_volumn_9
	 * @param buyVolumn9  the value for neeq_history_quotation.buy_volumn_9
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public void setBuyVolumn9(Double buyVolumn9) {
		this.buyVolumn9 = buyVolumn9;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column neeq_history_quotation.buy_price_10
	 * @return  the value of neeq_history_quotation.buy_price_10
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public Double getBuyPrice10() {
		return buyPrice10;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column neeq_history_quotation.buy_price_10
	 * @param buyPrice10  the value for neeq_history_quotation.buy_price_10
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public void setBuyPrice10(Double buyPrice10) {
		this.buyPrice10 = buyPrice10;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column neeq_history_quotation.buy_volumn_10
	 * @return  the value of neeq_history_quotation.buy_volumn_10
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public Double getBuyVolumn10() {
		return buyVolumn10;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column neeq_history_quotation.buy_volumn_10
	 * @param buyVolumn10  the value for neeq_history_quotation.buy_volumn_10
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public void setBuyVolumn10(Double buyVolumn10) {
		this.buyVolumn10 = buyVolumn10;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column neeq_history_quotation.up_down_rate_close
	 * @return  the value of neeq_history_quotation.up_down_rate_close
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public Double getUpDownRateClose() {
		return upDownRateClose;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column neeq_history_quotation.up_down_rate_close
	 * @param upDownRateClose  the value for neeq_history_quotation.up_down_rate_close
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public void setUpDownRateClose(Double upDownRateClose) {
		this.upDownRateClose = upDownRateClose;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column neeq_history_quotation.pe_rate
	 * @return  the value of neeq_history_quotation.pe_rate
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public Double getPeRate() {
		return peRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column neeq_history_quotation.pe_rate
	 * @param peRate  the value for neeq_history_quotation.pe_rate
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public void setPeRate(Double peRate) {
		this.peRate = peRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column neeq_history_quotation.trans_rate
	 * @return  the value of neeq_history_quotation.trans_rate
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public Double getTransRate() {
		return transRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column neeq_history_quotation.trans_rate
	 * @param transRate  the value for neeq_history_quotation.trans_rate
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public void setTransRate(Double transRate) {
		this.transRate = transRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column neeq_history_quotation.pb_rate
	 * @return  the value of neeq_history_quotation.pb_rate
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public Double getPbRate() {
		return pbRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column neeq_history_quotation.pb_rate
	 * @param pbRate  the value for neeq_history_quotation.pb_rate
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public void setPbRate(Double pbRate) {
		this.pbRate = pbRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column neeq_history_quotation.market_value
	 * @return  the value of neeq_history_quotation.market_value
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public Double getMarketValue() {
		return marketValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column neeq_history_quotation.market_value
	 * @param marketValue  the value for neeq_history_quotation.market_value
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public void setMarketValue(Double marketValue) {
		this.marketValue = marketValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column neeq_history_quotation.avarage_price
	 * @return  the value of neeq_history_quotation.avarage_price
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public Double getAvaragePrice() {
		return avaragePrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column neeq_history_quotation.avarage_price
	 * @param avaragePrice  the value for neeq_history_quotation.avarage_price
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public void setAvaragePrice(Double avaragePrice) {
		this.avaragePrice = avaragePrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column neeq_history_quotation.total_value
	 * @return  the value of neeq_history_quotation.total_value
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public Double getTotalValue() {
		return totalValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column neeq_history_quotation.total_value
	 * @param totalValue  the value for neeq_history_quotation.total_value
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public void setTotalValue(Double totalValue) {
		this.totalValue = totalValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column neeq_history_quotation.change_range_rate
	 * @return  the value of neeq_history_quotation.change_range_rate
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public Double getChangeRangeRate() {
		return changeRangeRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column neeq_history_quotation.change_range_rate
	 * @param changeRangeRate  the value for neeq_history_quotation.change_range_rate
	 * @mbggenerated  Thu Mar 22 16:38:16 CST 2018
	 */
	public void setChangeRangeRate(Double changeRangeRate) {
		this.changeRangeRate = changeRangeRate;
	}
}