package com.kf.data.mybatis.entity.online;

import java.util.Date;

public class NeeqCompanyCopyrightOnline {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company_copyright.id
     *
     * @mbggenerated Wed Mar 14 10:17:16 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company_copyright.company_id
     *
     * @mbggenerated Wed Mar 14 10:17:16 CST 2018
     */
    private String companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company_copyright.company_name
     *
     * @mbggenerated Wed Mar 14 10:17:16 CST 2018
     */
    private String companyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company_copyright.name
     *
     * @mbggenerated Wed Mar 14 10:17:16 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company_copyright.shortname
     *
     * @mbggenerated Wed Mar 14 10:17:16 CST 2018
     */
    private String shortname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company_copyright.type
     *
     * @mbggenerated Wed Mar 14 10:17:16 CST 2018
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company_copyright.registration_number
     *
     * @mbggenerated Wed Mar 14 10:17:16 CST 2018
     */
    private String registrationNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company_copyright.classification_num
     *
     * @mbggenerated Wed Mar 14 10:17:16 CST 2018
     */
    private String classificationNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company_copyright.version
     *
     * @mbggenerated Wed Mar 14 10:17:16 CST 2018
     */
    private String version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company_copyright.register_date
     *
     * @mbggenerated Wed Mar 14 10:17:16 CST 2018
     */
    private String registerDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company_copyright.register_date_machine
     *
     * @mbggenerated Wed Mar 14 10:17:16 CST 2018
     */
    private Integer registerDateMachine;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company_copyright.copyright_owner_id
     *
     * @mbggenerated Wed Mar 14 10:17:16 CST 2018
     */
    private String copyrightOwnerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company_copyright.copyright_owner
     *
     * @mbggenerated Wed Mar 14 10:17:16 CST 2018
     */
    private String copyrightOwner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company_copyright.nationality
     *
     * @mbggenerated Wed Mar 14 10:17:16 CST 2018
     */
    private String nationality;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company_copyright.create_date_machine
     *
     * @mbggenerated Wed Mar 14 10:17:16 CST 2018
     */
    private Integer createDateMachine;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company_copyright.create_date
     *
     * @mbggenerated Wed Mar 14 10:17:16 CST 2018
     */
    private String createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company_copyright.published_date_machine
     *
     * @mbggenerated Wed Mar 14 10:17:16 CST 2018
     */
    private Integer publishedDateMachine;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company_copyright.published_date
     *
     * @mbggenerated Wed Mar 14 10:17:16 CST 2018
     */
    private String publishedDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company_copyright.author_name
     *
     * @mbggenerated Wed Mar 14 10:17:16 CST 2018
     */
    private String authorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company_copyright.status
     *
     * @mbggenerated Wed Mar 14 10:17:16 CST 2018
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company_copyright.created_at
     *
     * @mbggenerated Wed Mar 14 10:17:16 CST 2018
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company_copyright.updated_at
     *
     * @mbggenerated Wed Mar 14 10:17:16 CST 2018
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company_copyright.id
     *
     * @return the value of neeq_company_copyright.id
     *
     * @mbggenerated Wed Mar 14 10:17:16 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company_copyright.id
     *
     * @param id the value for neeq_company_copyright.id
     *
     * @mbggenerated Wed Mar 14 10:17:16 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company_copyright.company_id
     *
     * @return the value of neeq_company_copyright.company_id
     *
     * @mbggenerated Wed Mar 14 10:17:16 CST 2018
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company_copyright.company_id
     *
     * @param companyId the value for neeq_company_copyright.company_id
     *
     * @mbggenerated Wed Mar 14 10:17:16 CST 2018
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company_copyright.company_name
     *
     * @return the value of neeq_company_copyright.company_name
     *
     * @mbggenerated Wed Mar 14 10:17:16 CST 2018
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company_copyright.company_name
     *
     * @param companyName the value for neeq_company_copyright.company_name
     *
     * @mbggenerated Wed Mar 14 10:17:16 CST 2018
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company_copyright.name
     *
     * @return the value of neeq_company_copyright.name
     *
     * @mbggenerated Wed Mar 14 10:17:16 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company_copyright.name
     *
     * @param name the value for neeq_company_copyright.name
     *
     * @mbggenerated Wed Mar 14 10:17:16 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company_copyright.shortname
     *
     * @return the value of neeq_company_copyright.shortname
     *
     * @mbggenerated Wed Mar 14 10:17:16 CST 2018
     */
    public String getShortname() {
        return shortname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company_copyright.shortname
     *
     * @param shortname the value for neeq_company_copyright.shortname
     *
     * @mbggenerated Wed Mar 14 10:17:16 CST 2018
     */
    public void setShortname(String shortname) {
        this.shortname = shortname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company_copyright.type
     *
     * @return the value of neeq_company_copyright.type
     *
     * @mbggenerated Wed Mar 14 10:17:16 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company_copyright.type
     *
     * @param type the value for neeq_company_copyright.type
     *
     * @mbggenerated Wed Mar 14 10:17:16 CST 2018
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company_copyright.registration_number
     *
     * @return the value of neeq_company_copyright.registration_number
     *
     * @mbggenerated Wed Mar 14 10:17:16 CST 2018
     */
    public String getRegistrationNumber() {
        return registrationNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company_copyright.registration_number
     *
     * @param registrationNumber the value for neeq_company_copyright.registration_number
     *
     * @mbggenerated Wed Mar 14 10:17:16 CST 2018
     */
    public void setRegistrationNumber(String registrationNumber) {
        this.registrationNumber = registrationNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company_copyright.classification_num
     *
     * @return the value of neeq_company_copyright.classification_num
     *
     * @mbggenerated Wed Mar 14 10:17:16 CST 2018
     */
    public String getClassificationNum() {
        return classificationNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company_copyright.classification_num
     *
     * @param classificationNum the value for neeq_company_copyright.classification_num
     *
     * @mbggenerated Wed Mar 14 10:17:16 CST 2018
     */
    public void setClassificationNum(String classificationNum) {
        this.classificationNum = classificationNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company_copyright.version
     *
     * @return the value of neeq_company_copyright.version
     *
     * @mbggenerated Wed Mar 14 10:17:16 CST 2018
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company_copyright.version
     *
     * @param version the value for neeq_company_copyright.version
     *
     * @mbggenerated Wed Mar 14 10:17:16 CST 2018
     */
    public void setVersion(String version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company_copyright.register_date
     *
     * @return the value of neeq_company_copyright.register_date
     *
     * @mbggenerated Wed Mar 14 10:17:16 CST 2018
     */
    public String getRegisterDate() {
        return registerDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company_copyright.register_date
     *
     * @param registerDate the value for neeq_company_copyright.register_date
     *
     * @mbggenerated Wed Mar 14 10:17:16 CST 2018
     */
    public void setRegisterDate(String registerDate) {
        this.registerDate = registerDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company_copyright.register_date_machine
     *
     * @return the value of neeq_company_copyright.register_date_machine
     *
     * @mbggenerated Wed Mar 14 10:17:16 CST 2018
     */
    public Integer getRegisterDateMachine() {
        return registerDateMachine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company_copyright.register_date_machine
     *
     * @param registerDateMachine the value for neeq_company_copyright.register_date_machine
     *
     * @mbggenerated Wed Mar 14 10:17:16 CST 2018
     */
    public void setRegisterDateMachine(Integer registerDateMachine) {
        this.registerDateMachine = registerDateMachine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company_copyright.copyright_owner_id
     *
     * @return the value of neeq_company_copyright.copyright_owner_id
     *
     * @mbggenerated Wed Mar 14 10:17:16 CST 2018
     */
    public String getCopyrightOwnerId() {
        return copyrightOwnerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company_copyright.copyright_owner_id
     *
     * @param copyrightOwnerId the value for neeq_company_copyright.copyright_owner_id
     *
     * @mbggenerated Wed Mar 14 10:17:16 CST 2018
     */
    public void setCopyrightOwnerId(String copyrightOwnerId) {
        this.copyrightOwnerId = copyrightOwnerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company_copyright.copyright_owner
     *
     * @return the value of neeq_company_copyright.copyright_owner
     *
     * @mbggenerated Wed Mar 14 10:17:16 CST 2018
     */
    public String getCopyrightOwner() {
        return copyrightOwner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company_copyright.copyright_owner
     *
     * @param copyrightOwner the value for neeq_company_copyright.copyright_owner
     *
     * @mbggenerated Wed Mar 14 10:17:16 CST 2018
     */
    public void setCopyrightOwner(String copyrightOwner) {
        this.copyrightOwner = copyrightOwner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company_copyright.nationality
     *
     * @return the value of neeq_company_copyright.nationality
     *
     * @mbggenerated Wed Mar 14 10:17:16 CST 2018
     */
    public String getNationality() {
        return nationality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company_copyright.nationality
     *
     * @param nationality the value for neeq_company_copyright.nationality
     *
     * @mbggenerated Wed Mar 14 10:17:16 CST 2018
     */
    public void setNationality(String nationality) {
        this.nationality = nationality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company_copyright.create_date_machine
     *
     * @return the value of neeq_company_copyright.create_date_machine
     *
     * @mbggenerated Wed Mar 14 10:17:16 CST 2018
     */
    public Integer getCreateDateMachine() {
        return createDateMachine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company_copyright.create_date_machine
     *
     * @param createDateMachine the value for neeq_company_copyright.create_date_machine
     *
     * @mbggenerated Wed Mar 14 10:17:16 CST 2018
     */
    public void setCreateDateMachine(Integer createDateMachine) {
        this.createDateMachine = createDateMachine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company_copyright.create_date
     *
     * @return the value of neeq_company_copyright.create_date
     *
     * @mbggenerated Wed Mar 14 10:17:16 CST 2018
     */
    public String getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company_copyright.create_date
     *
     * @param createDate the value for neeq_company_copyright.create_date
     *
     * @mbggenerated Wed Mar 14 10:17:16 CST 2018
     */
    public void setCreateDate(String createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company_copyright.published_date_machine
     *
     * @return the value of neeq_company_copyright.published_date_machine
     *
     * @mbggenerated Wed Mar 14 10:17:16 CST 2018
     */
    public Integer getPublishedDateMachine() {
        return publishedDateMachine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company_copyright.published_date_machine
     *
     * @param publishedDateMachine the value for neeq_company_copyright.published_date_machine
     *
     * @mbggenerated Wed Mar 14 10:17:16 CST 2018
     */
    public void setPublishedDateMachine(Integer publishedDateMachine) {
        this.publishedDateMachine = publishedDateMachine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company_copyright.published_date
     *
     * @return the value of neeq_company_copyright.published_date
     *
     * @mbggenerated Wed Mar 14 10:17:16 CST 2018
     */
    public String getPublishedDate() {
        return publishedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company_copyright.published_date
     *
     * @param publishedDate the value for neeq_company_copyright.published_date
     *
     * @mbggenerated Wed Mar 14 10:17:16 CST 2018
     */
    public void setPublishedDate(String publishedDate) {
        this.publishedDate = publishedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company_copyright.author_name
     *
     * @return the value of neeq_company_copyright.author_name
     *
     * @mbggenerated Wed Mar 14 10:17:16 CST 2018
     */
    public String getAuthorName() {
        return authorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company_copyright.author_name
     *
     * @param authorName the value for neeq_company_copyright.author_name
     *
     * @mbggenerated Wed Mar 14 10:17:16 CST 2018
     */
    public void setAuthorName(String authorName) {
        this.authorName = authorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company_copyright.status
     *
     * @return the value of neeq_company_copyright.status
     *
     * @mbggenerated Wed Mar 14 10:17:16 CST 2018
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company_copyright.status
     *
     * @param status the value for neeq_company_copyright.status
     *
     * @mbggenerated Wed Mar 14 10:17:16 CST 2018
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company_copyright.created_at
     *
     * @return the value of neeq_company_copyright.created_at
     *
     * @mbggenerated Wed Mar 14 10:17:16 CST 2018
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company_copyright.created_at
     *
     * @param createdAt the value for neeq_company_copyright.created_at
     *
     * @mbggenerated Wed Mar 14 10:17:16 CST 2018
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company_copyright.updated_at
     *
     * @return the value of neeq_company_copyright.updated_at
     *
     * @mbggenerated Wed Mar 14 10:17:16 CST 2018
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company_copyright.updated_at
     *
     * @param updatedAt the value for neeq_company_copyright.updated_at
     *
     * @mbggenerated Wed Mar 14 10:17:16 CST 2018
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}