package com.kf.data.mybatis.entity.online;

import java.util.Date;

public class NeeqCompanyOnline {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company.id
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company.company_id
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    private String companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company.stock_id
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    private String stockId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company.code
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    private Integer code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company.name
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company.shortname
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    private String shortname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company.transfer_mode
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    private String transferMode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company.industryid
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    private String industryid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company.industry_code
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    private String industryCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company.industry_name
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    private String industryName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company.special_id
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    private String specialId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company.special_name
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    private String specialName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company.accounting_firm_shortname
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    private String accountingFirmShortname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company.accounting_firm_id
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    private String accountingFirmId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company.law_firm_shortname
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    private String lawFirmShortname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company.law_firm_id
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    private String lawFirmId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company.area
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    private String area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company.city_id
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    private String cityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company.city_code
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    private String cityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company.city_name
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    private String cityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company.area_id
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    private String areaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company.dt_list_appr
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    private Date dtListAppr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company.listing_date
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    private String listingDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company.dt_trans_start
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    private Date dtTransStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company.website
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    private String website;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company.address
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company.office_address
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    private String officeAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company.phone
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company.postcode
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    private String postcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company.type
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company.listing_date_machine
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    private Integer listingDateMachine;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company.fax
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    private String fax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company.legal_representative
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    private String legalRepresentative;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company.legal_representative_id
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    private String legalRepresentativeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company.secretaries
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    private String secretaries;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company.secretaries_id
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    private String secretariesId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company.employees_num
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    private Double employeesNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company.total_stock_equity
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    private Double totalStockEquity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company.english_name
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    private String englishName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company.email
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company.delisted_date
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    private String delistedDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company.delisted_date_machine
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    private Integer delistedDateMachine;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company.after_delisted
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    private String afterDelisted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company.market_making_num
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    private Integer marketMakingNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company.list_status_id
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    private String listStatusId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company.list_status_name
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    private String listStatusName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company.area_code
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    private String areaCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company.status
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company.created_at
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company.updated_at
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neeq_company.main_business
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    private String mainBusiness;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company.id
     *
     * @return the value of neeq_company.id
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company.id
     *
     * @param id the value for neeq_company.id
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company.company_id
     *
     * @return the value of neeq_company.company_id
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company.company_id
     *
     * @param companyId the value for neeq_company.company_id
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company.stock_id
     *
     * @return the value of neeq_company.stock_id
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    public String getStockId() {
        return stockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company.stock_id
     *
     * @param stockId the value for neeq_company.stock_id
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    public void setStockId(String stockId) {
        this.stockId = stockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company.code
     *
     * @return the value of neeq_company.code
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    public Integer getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company.code
     *
     * @param code the value for neeq_company.code
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    public void setCode(Integer code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company.name
     *
     * @return the value of neeq_company.name
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company.name
     *
     * @param name the value for neeq_company.name
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company.shortname
     *
     * @return the value of neeq_company.shortname
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    public String getShortname() {
        return shortname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company.shortname
     *
     * @param shortname the value for neeq_company.shortname
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    public void setShortname(String shortname) {
        this.shortname = shortname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company.transfer_mode
     *
     * @return the value of neeq_company.transfer_mode
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    public String getTransferMode() {
        return transferMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company.transfer_mode
     *
     * @param transferMode the value for neeq_company.transfer_mode
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    public void setTransferMode(String transferMode) {
        this.transferMode = transferMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company.industryid
     *
     * @return the value of neeq_company.industryid
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    public String getIndustryid() {
        return industryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company.industryid
     *
     * @param industryid the value for neeq_company.industryid
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    public void setIndustryid(String industryid) {
        this.industryid = industryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company.industry_code
     *
     * @return the value of neeq_company.industry_code
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    public String getIndustryCode() {
        return industryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company.industry_code
     *
     * @param industryCode the value for neeq_company.industry_code
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    public void setIndustryCode(String industryCode) {
        this.industryCode = industryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company.industry_name
     *
     * @return the value of neeq_company.industry_name
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    public String getIndustryName() {
        return industryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company.industry_name
     *
     * @param industryName the value for neeq_company.industry_name
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    public void setIndustryName(String industryName) {
        this.industryName = industryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company.special_id
     *
     * @return the value of neeq_company.special_id
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    public String getSpecialId() {
        return specialId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company.special_id
     *
     * @param specialId the value for neeq_company.special_id
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    public void setSpecialId(String specialId) {
        this.specialId = specialId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company.special_name
     *
     * @return the value of neeq_company.special_name
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    public String getSpecialName() {
        return specialName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company.special_name
     *
     * @param specialName the value for neeq_company.special_name
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    public void setSpecialName(String specialName) {
        this.specialName = specialName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company.accounting_firm_shortname
     *
     * @return the value of neeq_company.accounting_firm_shortname
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    public String getAccountingFirmShortname() {
        return accountingFirmShortname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company.accounting_firm_shortname
     *
     * @param accountingFirmShortname the value for neeq_company.accounting_firm_shortname
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    public void setAccountingFirmShortname(String accountingFirmShortname) {
        this.accountingFirmShortname = accountingFirmShortname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company.accounting_firm_id
     *
     * @return the value of neeq_company.accounting_firm_id
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    public String getAccountingFirmId() {
        return accountingFirmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company.accounting_firm_id
     *
     * @param accountingFirmId the value for neeq_company.accounting_firm_id
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    public void setAccountingFirmId(String accountingFirmId) {
        this.accountingFirmId = accountingFirmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company.law_firm_shortname
     *
     * @return the value of neeq_company.law_firm_shortname
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    public String getLawFirmShortname() {
        return lawFirmShortname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company.law_firm_shortname
     *
     * @param lawFirmShortname the value for neeq_company.law_firm_shortname
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    public void setLawFirmShortname(String lawFirmShortname) {
        this.lawFirmShortname = lawFirmShortname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company.law_firm_id
     *
     * @return the value of neeq_company.law_firm_id
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    public String getLawFirmId() {
        return lawFirmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company.law_firm_id
     *
     * @param lawFirmId the value for neeq_company.law_firm_id
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    public void setLawFirmId(String lawFirmId) {
        this.lawFirmId = lawFirmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company.area
     *
     * @return the value of neeq_company.area
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company.area
     *
     * @param area the value for neeq_company.area
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    public void setArea(String area) {
        this.area = area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company.city_id
     *
     * @return the value of neeq_company.city_id
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    public String getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company.city_id
     *
     * @param cityId the value for neeq_company.city_id
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    public void setCityId(String cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company.city_code
     *
     * @return the value of neeq_company.city_code
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    public String getCityCode() {
        return cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company.city_code
     *
     * @param cityCode the value for neeq_company.city_code
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    public void setCityCode(String cityCode) {
        this.cityCode = cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company.city_name
     *
     * @return the value of neeq_company.city_name
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company.city_name
     *
     * @param cityName the value for neeq_company.city_name
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    public void setCityName(String cityName) {
        this.cityName = cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company.area_id
     *
     * @return the value of neeq_company.area_id
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    public String getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company.area_id
     *
     * @param areaId the value for neeq_company.area_id
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    public void setAreaId(String areaId) {
        this.areaId = areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company.dt_list_appr
     *
     * @return the value of neeq_company.dt_list_appr
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    public Date getDtListAppr() {
        return dtListAppr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company.dt_list_appr
     *
     * @param dtListAppr the value for neeq_company.dt_list_appr
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    public void setDtListAppr(Date dtListAppr) {
        this.dtListAppr = dtListAppr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company.listing_date
     *
     * @return the value of neeq_company.listing_date
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    public String getListingDate() {
        return listingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company.listing_date
     *
     * @param listingDate the value for neeq_company.listing_date
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    public void setListingDate(String listingDate) {
        this.listingDate = listingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company.dt_trans_start
     *
     * @return the value of neeq_company.dt_trans_start
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    public Date getDtTransStart() {
        return dtTransStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company.dt_trans_start
     *
     * @param dtTransStart the value for neeq_company.dt_trans_start
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    public void setDtTransStart(Date dtTransStart) {
        this.dtTransStart = dtTransStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company.website
     *
     * @return the value of neeq_company.website
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    public String getWebsite() {
        return website;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company.website
     *
     * @param website the value for neeq_company.website
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    public void setWebsite(String website) {
        this.website = website;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company.address
     *
     * @return the value of neeq_company.address
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company.address
     *
     * @param address the value for neeq_company.address
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company.office_address
     *
     * @return the value of neeq_company.office_address
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    public String getOfficeAddress() {
        return officeAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company.office_address
     *
     * @param officeAddress the value for neeq_company.office_address
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    public void setOfficeAddress(String officeAddress) {
        this.officeAddress = officeAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company.phone
     *
     * @return the value of neeq_company.phone
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company.phone
     *
     * @param phone the value for neeq_company.phone
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company.postcode
     *
     * @return the value of neeq_company.postcode
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    public String getPostcode() {
        return postcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company.postcode
     *
     * @param postcode the value for neeq_company.postcode
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    public void setPostcode(String postcode) {
        this.postcode = postcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company.type
     *
     * @return the value of neeq_company.type
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company.type
     *
     * @param type the value for neeq_company.type
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company.listing_date_machine
     *
     * @return the value of neeq_company.listing_date_machine
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    public Integer getListingDateMachine() {
        return listingDateMachine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company.listing_date_machine
     *
     * @param listingDateMachine the value for neeq_company.listing_date_machine
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    public void setListingDateMachine(Integer listingDateMachine) {
        this.listingDateMachine = listingDateMachine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company.fax
     *
     * @return the value of neeq_company.fax
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company.fax
     *
     * @param fax the value for neeq_company.fax
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    public void setFax(String fax) {
        this.fax = fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company.legal_representative
     *
     * @return the value of neeq_company.legal_representative
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    public String getLegalRepresentative() {
        return legalRepresentative;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company.legal_representative
     *
     * @param legalRepresentative the value for neeq_company.legal_representative
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    public void setLegalRepresentative(String legalRepresentative) {
        this.legalRepresentative = legalRepresentative;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company.legal_representative_id
     *
     * @return the value of neeq_company.legal_representative_id
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    public String getLegalRepresentativeId() {
        return legalRepresentativeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company.legal_representative_id
     *
     * @param legalRepresentativeId the value for neeq_company.legal_representative_id
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    public void setLegalRepresentativeId(String legalRepresentativeId) {
        this.legalRepresentativeId = legalRepresentativeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company.secretaries
     *
     * @return the value of neeq_company.secretaries
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    public String getSecretaries() {
        return secretaries;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company.secretaries
     *
     * @param secretaries the value for neeq_company.secretaries
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    public void setSecretaries(String secretaries) {
        this.secretaries = secretaries;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company.secretaries_id
     *
     * @return the value of neeq_company.secretaries_id
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    public String getSecretariesId() {
        return secretariesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company.secretaries_id
     *
     * @param secretariesId the value for neeq_company.secretaries_id
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    public void setSecretariesId(String secretariesId) {
        this.secretariesId = secretariesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company.employees_num
     *
     * @return the value of neeq_company.employees_num
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    public Double getEmployeesNum() {
        return employeesNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company.employees_num
     *
     * @param employeesNum the value for neeq_company.employees_num
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    public void setEmployeesNum(Double employeesNum) {
        this.employeesNum = employeesNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company.total_stock_equity
     *
     * @return the value of neeq_company.total_stock_equity
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    public Double getTotalStockEquity() {
        return totalStockEquity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company.total_stock_equity
     *
     * @param totalStockEquity the value for neeq_company.total_stock_equity
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    public void setTotalStockEquity(Double totalStockEquity) {
        this.totalStockEquity = totalStockEquity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company.english_name
     *
     * @return the value of neeq_company.english_name
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    public String getEnglishName() {
        return englishName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company.english_name
     *
     * @param englishName the value for neeq_company.english_name
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    public void setEnglishName(String englishName) {
        this.englishName = englishName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company.email
     *
     * @return the value of neeq_company.email
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company.email
     *
     * @param email the value for neeq_company.email
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company.delisted_date
     *
     * @return the value of neeq_company.delisted_date
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    public String getDelistedDate() {
        return delistedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company.delisted_date
     *
     * @param delistedDate the value for neeq_company.delisted_date
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    public void setDelistedDate(String delistedDate) {
        this.delistedDate = delistedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company.delisted_date_machine
     *
     * @return the value of neeq_company.delisted_date_machine
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    public Integer getDelistedDateMachine() {
        return delistedDateMachine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company.delisted_date_machine
     *
     * @param delistedDateMachine the value for neeq_company.delisted_date_machine
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    public void setDelistedDateMachine(Integer delistedDateMachine) {
        this.delistedDateMachine = delistedDateMachine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company.after_delisted
     *
     * @return the value of neeq_company.after_delisted
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    public String getAfterDelisted() {
        return afterDelisted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company.after_delisted
     *
     * @param afterDelisted the value for neeq_company.after_delisted
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    public void setAfterDelisted(String afterDelisted) {
        this.afterDelisted = afterDelisted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company.market_making_num
     *
     * @return the value of neeq_company.market_making_num
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    public Integer getMarketMakingNum() {
        return marketMakingNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company.market_making_num
     *
     * @param marketMakingNum the value for neeq_company.market_making_num
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    public void setMarketMakingNum(Integer marketMakingNum) {
        this.marketMakingNum = marketMakingNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company.list_status_id
     *
     * @return the value of neeq_company.list_status_id
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    public String getListStatusId() {
        return listStatusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company.list_status_id
     *
     * @param listStatusId the value for neeq_company.list_status_id
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    public void setListStatusId(String listStatusId) {
        this.listStatusId = listStatusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company.list_status_name
     *
     * @return the value of neeq_company.list_status_name
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    public String getListStatusName() {
        return listStatusName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company.list_status_name
     *
     * @param listStatusName the value for neeq_company.list_status_name
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    public void setListStatusName(String listStatusName) {
        this.listStatusName = listStatusName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company.area_code
     *
     * @return the value of neeq_company.area_code
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    public String getAreaCode() {
        return areaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company.area_code
     *
     * @param areaCode the value for neeq_company.area_code
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    public void setAreaCode(String areaCode) {
        this.areaCode = areaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company.status
     *
     * @return the value of neeq_company.status
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company.status
     *
     * @param status the value for neeq_company.status
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company.created_at
     *
     * @return the value of neeq_company.created_at
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company.created_at
     *
     * @param createdAt the value for neeq_company.created_at
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company.updated_at
     *
     * @return the value of neeq_company.updated_at
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company.updated_at
     *
     * @param updatedAt the value for neeq_company.updated_at
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neeq_company.main_business
     *
     * @return the value of neeq_company.main_business
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    public String getMainBusiness() {
        return mainBusiness;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neeq_company.main_business
     *
     * @param mainBusiness the value for neeq_company.main_business
     *
     * @mbggenerated Wed Mar 14 10:07:19 CST 2018
     */
    public void setMainBusiness(String mainBusiness) {
        this.mainBusiness = mainBusiness;
    }
}